### PR TITLE
Add WebDAV support via a `restic web` subcommand

### PR DESCRIPTION
**Pull request by wrouesnel**
This PR adds a webdav endpoint to restic, built on top of the existing FUSE filesystem abstractions and the `golang.org/x/net/webdav` library.

I have tested it with the GVFS WebDAV browser, and it works correctly. Symlinks in the target repository are ignored by the WebDAV endpoint as WebDAV has no concept of them (though they could be handled as file-aliases via a command line flag - but the default behavior is "rsync-safe" in that you can't overwrite your working symlinks by copying out of webdav mountpoint).

Missing functionality:
* The `restic web` command should expose a basic filesystem browser via a web-browser. Implementing a composed http.Fileserver / webdav.Handler interface should be able to support this.

* Allow building the FUSE abstractions on Windows. At the moment they are gated behind build tags for unix-likes only, but the webdav endpoint should work as a Windows remote filesystem endpoint (and this is the case where it is most useful).

### CODE REVIEW

**Comment by fd0** [comment]
Hey, thanks for your contribution! Is this PR ready for a review? What about the style issues identified by Hound?

**Comment by wrouesnel** [comment]
Me and hound disagree? :) I'll fix them.

I need to plan some time to see how this can be built and used on Windows (which the FUSE sections are tagged out at the moment) since that was a motivating factor for it. Also looks like the CI builds didn't like it :(

**Comment by fd0** [comment]
Great, I'm looking forward to it. Just let me know if you get stuck anywhere, I'm glad to help out.

**Comment by fd0** [comment]
Hey, did you find the time yet to have a look? Do you have any questions I can assist you with? :smiley:

**Comment by fd0** [comment]
Since there was no feedback for a while I'm going to close this PR for now. Please feel free to add a comment or get in touch when you want to work on it again. I'll be happy to provide feedback and guidance if needed :)

**Pull request closed without merging**
