### PR TITLE
Add support for Google Cloud Storage (including Nearline).

### PR DESCRIPTION
**Pull request by kurin**
This adds support for GCS per #211.

There are a few improvements that can be made on top of this, especially fixing GetReader so that it doesn't throw away extraneous bytes.

### CODE REVIEW

**Comment by fw42** [comment]
This is impossible to review (the diff is too big for GitHub to display). Can you split this into two branches (and two PRs)? One that only has the dependencies and then another PR (against that first branch) that has your actual code contributions to restic?

**Comment by kurin** [comment]
Can do.

**Comment by fd0** [comment]
I must say that I find the large amount of code this backend depends on frightening...

**Comment by fd0** [comment]
Code is in #304, Deps in #303.

**Comment by abourget** [comment]
Any news on this ? I'd be glad to use restic with Google Storage too.

**Pull request closed without merging**
