### PR TITLE
Add possibility to specify extra repo for "hot" data

### LINKED ISSUE #2504: restic with "cold" storage (here: OVH Cloud Archive)
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic -r rclone:ovh:test2 -p key-restic snapshots`

Output is:
```
Load(<key/1bd3e4429a>, 0, 0) returned error, retrying after 720.254544ms: <key/1bd3e4429a> does not exist
```
repeated a couple of times with changing retry times and then:
`Fatal: <key/1bd3e4429a> does not exist`

When using
`RCLONE_VERBOSE=2 restic -r rclone:ovh:test2 -p key-restic snapshots`
you see:
```
rclone: 2019/12/07 12:40:04 DEBUG : Swift container test2: GET /file-5577006791947779410
rclone: 2019/12/07 12:40:04 DEBUG : file-5577006791947779410: GET request error: object not found
rclone: 2019/12/07 12:40:04 DEBUG : Swift container test2: HEAD /config
rclone: 2019/12/07 12:40:05 DEBUG : Swift container test2: GET /keys/
rclone: 2019/12/07 12:40:05 DEBUG : keys: list request
rclone: 2019/12/07 12:40:06 DEBUG : Swift container test2: GET /keys/1bd3e4429a441fd7546efdfa1bc7c41333d548b0a1ecb5dea3fd1f9ef16c205f
rclone: 2019/12/07 12:40:07 DEBUG : 1bd3e4429a441fd7546efdfa1bc7c41333d548b0a1ecb5dea3fd1f9ef16c205f: Get request open error: try again after 2019-12-07T12:50:07.317400358+01:00 (9m59.999921857s)
Load(<key/1bd3e4429a>, 0, 0) returned error, retrying after 720.254544ms: <key/1bd3e4429a> does not exist
```

Similar behavior with other restic commands, like `backup` etc.

If you wait long enough and redo the command, restic works fine. However, the issue occurs with

- key files
- config file
- lock files

Therefore you might have to repeat and wait quite often before the requested operation is performed.

Another issue is, that the above files are not cached and therefore once you manage to get these files "warm" in the backend, you can do your operations. But if they get "cold" again, you again come in the original mentioned issue. 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone to access OVH via swift.
The rclone config is directly as provided by OVH.
test2 is a bucket in [OVH Cloud Archive](https://www.ovh.com/world/public-cloud/cloud-archive/)

Expected behavior
-----------------

- restic should wait until the data is ready to access. Ideally giving a hint that it is waiting.
- restic should cache config file, key files and lock files.

Actual behavior
---------------

- restic stops without performing the requested observation when data is not yet ready to access
- config file, key files and lock files are not cached.

Steps to reproduce the behavior
-------------------------------

- create an bucket in OVH Cloud Archive
- run restic init on this bucket
- wait some time to let the data become "cold"
- perform the commands given above

Do you have any idea what may have caused this?
-----------------------------------------------
restic is not prepared to using a "cold" backend.

Do you have an idea how to solve the issue?
-------------------------------------------
1. I would suggest adding an option which allows restic to wait even for a real long time if it doesn't receive the data for a backend
2. Even better would be to get and use the information how long we have to wait. Then just wait long enough and display to the user that you are waiting.
3. Another improvement would be to use the waiting time an try to get other files you need from the backend. Ideally restic should try to start the warmup-process for as many files as possible.
4. Implement caching for key files, the config file and lock files. I think this involves following steps:

- Optionally organize caches by repo string instead of repo ID to make caching of key files and config files possible
- Add key files, config files and lock files to the cache implementation in `internal/cache`
- Check which commands need improvement to use the cache information

I would like to work on 1. and 4. and appreciate any help!

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I do my daily backups with restic and like it very much! I especially like the possibility to directly backup to a cloud storage. Before I used other backup tools to backup to a local disc and sync the backup to a cloud storage. This solution failed badly once I had a problem with my USB hub which destroyed my local disc backup (and consequently my cloud storage copy)
Moreover using restic backup --stdin for DB backups is just great and makes me very happy :smile:

### LINKED ISSUE #2611: Support Scaleway C14 Glacier Class?
I Suspect Restic will already support C14's standard class since it's S3 compatible, but it would be nice if it could also support the Glacier Glass, I presume indexes.etc would need to be kept at standard, but it would be nice if the data could be stored with the Glacier Class, at least older data.

https://www.scaleway.com/en/docs/object-storage-glacier/

Unlike AWS there's no retrieval fees, just a delay + whatever storage costs would be incurred for keeping the data in the standard tier for as long as it needs to be there (to access it)

### LINKED ISSUE #2817: S3 Glacier
Guys, I really need to use Glacier to do backups.

I am doing it, but I get this message sometimes.

image

I would like restic has a feature that wherever this happens, he ask me if if I want to request the file to be restored from Glacier to S3 so I can try run again later.
Then in some hours I can try the backup again.
Restic don't need to wait the file to be restored. Once it's restored, it will follow the s3 lifecycle and stay available for some days.

This feature would make restic unbeatable. By far the cheapest way to do backup.

Something like `restic backup --always-restore-from-glacier=yes`

I don't know how to program in go. I if knew I could try to change the code.
Also, instead of listing just the prefix of the s3 file that is on glacier, he could list the entire file, so I can parse the errors and try to fix it if other script to try again restic later. I have many files...

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Adds an option `--repo-hot` to specify a "hot repo" that is used for hot data, i.e. for all repository files except data pack files. The repo specified by `--repo` is still fully written and a complete restic repository, but only read if a pack data file is accessed. So, this can be stored in some "cold storage" or storage with very high latency while many restic commands still work. Usually the "hot repo" only takes a small fraction of the space used by the complete repository. See #3202 for the discussion. This PR implements the "cache-aproach".

The "hot repo" is marked by an extra data field in the Config file and some additional tests are added to check that only correct combiniations of "hot repo" and cold (i.e. standard) repo can be used. However, if a "hot repo" is openend by older restic versions, it will not give good errors, but seems like a broken repo.

Open points are:

- [ ] depends on #2856 which is not reviewed yet
- [x] add checks to the  `check` command that same files exist in hot and "complete" repo
- [x] add checks to the  `check --read-data` command that read and check all files from the "complete" repo
- [x] add some test case, especially test that the "complete" repo is not read except for data pack files
- [x] add ability to create a "hot repo" from an existing "complete" repo

Usage is:
```
restic -r <cold-repo> --repo-hot <hot-repo> init
restic -r <cold-repo> --repo-hot <hot-repo> backup /path/to/backup
restic -r <cold-repo> --repo-hot <hot-repo> backup /path/to/backup // follow-up backup
restic -r <cold-repo> --repo-hot <hot-repo> snapshots
restic -r <cold-repo> --repo-hot <hot-repo> check
restic -r <cold-repo> --repo-hot <hot-repo> forget --prune --repack-cacheable-only  <policy>
```
All the above commands do not read anything from `<cold-repo>`, just list the files therein or remove them during prune. In `<hot-repo>`, only the metadata is saved.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

see #3202 and the references therein.
IMO this closes #2504, closes #2611, closes #2817

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by lenzls** [comment]
> - [ ] depends on Simplify cache logic #2856 which is not reviewed yet

Just wanted to mention, that the PR in question is now merged. No stress though.

**Comment by sashokbg** [comment]
Hello and thank you for this great project ! When can the here-mentioned PR be merged ? Can I help somehow with it ?

**Comment by sashokbg** [comment]
@aawsome I have tested your code with OVH Cloud Archive (cold storage) and both backup and restore worked well.
The only drawback was that the first restore failed since cold storage files are not available immediately. It may be interesting to add some "unfreeze" feature ? I think S3 has the same behavior - you need to first initialize a retrieval job and wait for it to finish.

**Comment by aawsome** [comment]
@sashokbg I made #3303 which would allow `restore --dry-run --warm-up`.
This should work with OVH Coldstorage and other cold backend which allow to "warm up" by just trying to access a file. I'm also using the combination of this PR with OVH, but I have to admit that I never actually had to really restore a snapshot as this is only my second backup additional to one with a local backend...

**Comment by sashokbg** [comment]
@aawsome all of this looks awesome good job ! Isn't the current PR merge-able already ?

**Comment by aawsome** [comment]
> @aawsome all of this looks awesome good job ! Isn't the current PR merge-able already ?

No, it is not. There has been changes in master in between which introduced conflicts which need to be resolved.
However, I won't work on this PR until there are good chances that it will get merged in near future.

So changes are that this feature is implemented in rustic first.

**Comment by aawsome** [comment]
> So changes are that this feature is implemented in rustic first.

This functionality is now available on rustic main, see https://github.com/rustic-rs/rustic/issues/44, and will be part of the next rustic release.

**Comment by Kulgar** [comment]
Awesome job! I'd like to see this PR merged too as I would like to use restic with ovh cloud archive too. 

Anyway we could help?

**Comment by labkode** [comment]
Same here (CERN), this functionality is very important so we can consolidate the usage of restic for both hot data (disk-based Ceph S3) and cold (internal tape library).

**Comment by MichaelEischer** [comment]
The main missing part is probably time to review it, think about the design and what is necessary to properly support cold storage in restic. My backlog for PRs to review and bugs to fix / things to improve is unfortunately way too long :-/ .

**Comment by labkode** [comment]
@MichaelEischer can you get in touch with me by mail at hugo.gonzalez.labrador.cern.ch, we may have a way to speed up that process for review.

**Comment by aawsome** [comment]
@labkode Did you try out rustic where I already implemented this functionality?

**Pull request closed without merging**
