### PR TITLE
Increase the granularity of the "keep within" snapshot retention policy

### PR DESCRIPTION
**Pull request by plumbeo**
What is the purpose of this change? What does it change?
--------------------------------------------------------

Increase the minimum granularity of the time ranges accepted by the `restic forget --keep-within` command from a daily granularity to an hourly granularity.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Yes, in issue #2089.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by plumbeo** [comment]
I didn't add new tests covering the change to snapshot_policy_test.go yet because I'm not sure about how to generate the testdata.

**Comment by fd0** [comment]
Nice idea, I like it! Add the tests to `snapshot_policy_test.go`, then run the tests with `go test -v -update -run TestApplyPolicy`, then inspect the new (updated) files in `testdata/`. If they look good (the results are correct), commit the files. This technique uses so-called "golden" files to compare the result of an operation with the expected result without manually having to write the long and complicated files.

**Review by fd0 — CHANGES_REQUESTED** [review]
Add the tests, then I think this change is good to be merged. Thanks!

**Comment by plumbeo** [comment]
@fd0 I just pushed a modified commit that also add tests. Also, in the option description wasn't "older" supposed to be "newer"?

**Comment by fd0** [comment]
> Also, in the option description wasn't "older" supposed to be "newer"?

Huh, I think you're right!

**Review by fd0 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
