### PR TITLE
Handle SIGINFO on all supported platforms

### PR DESCRIPTION
**Pull request by valpackett**
Not just darwin (#1082)

### CODE REVIEW

**Comment by gregf** [comment]
Correct me if I'm wrong, but doesn't Linux support this to? I think they are using this functionality in the newer coreutils for dd. If you pass dd progress=status and hit ^t you get a progress update.

**Comment by myfreeweb** [comment]
@gregf I guess your terminal is set up to send `SIGUSR1` on Ctrl-T. Linux does not have `SIGINFO`.

**Comment by gregf** [comment]
Interesting, thanks for clearing that up.

**Comment by fd0** [comment]
Looks great!

**Pull request merged**
