### PR TITLE
Handle pack loading errors in rebuild-index

### PR DESCRIPTION
**Pull request by benmur**
Errors returned from backend.LoadAll() were not handled, leading to
these fatal errors from the unpacker trying to read the size from the end of
an empty buffer:

`seeking to read header length failed: bytes.Reader.Seek: negative position`

This change takes care of returning on error, as well as showing which pack
failed to load and validating pack integrity.

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for your contribution. Looks good and I'd like to merge it, could you run `gofmt` on the files so the integration test will succeed?

**Comment by benmur** [comment]
Sorry about that. I actually ran `gofmt -w **/*.go` but somehow it did not do anything so I assumed all was good. I'll have a look in a few.

**Comment by fd0** [comment]
Great, thanks. I'd suggest installing the `fmt-check` hook, but you already know about that one ;)

**Comment by benmur** [comment]
@fd0 branch updated, thanks for your patience!

**Comment by fd0** [comment]
Of course, thanks for your contribution!

**Pull request merged**
