### PR TITLE
Add "-x", "--one-file-system" option

### LINKED ISSUE #370: Add --exclude-other-filesystem support
From duplicity:

> --exclude-other-filesystems
>   Exclude files on file systems (identified by device number) other than the  file  system  the  root  of  the source directory is on.

Given

> /dev/mapper/sys-root on / 
> proc on /proc
> /dev/mapper/sys-home on /home

The following would backup **/** but not **/home** nor **/proc**

> restic backup / --exclude-other-filesystem

### PR DESCRIPTION
**Pull request by rfjakob**
Equivalent to rsync's "-x" option.

Closes #370

### CODE REVIEW

**Comment by rfjakob** [comment]
Closes #370

**Comment by fd0** [comment]
Hey, that already looks great! Let me know if you need any assistance.

**Comment by pvgoran** [comment]
Maybe use `--one-file-system` as the long option name, like `rsync` and `tar` do?

**Comment by rfjakob** [comment]
Slowly getting there ;)

**Comment by rfjakob** [comment]
The problem with `--one-file-system` is that it may be more than one, because we can have more than one source directory! Duplicity uses `--exclude-other-filesystems`.

**Comment by fd0** [comment]
Hm. Usually I'm all for using the same arguments as other popular tools, but in this case I think `--one-file-system` is not a good fit since there may be several file systems. Running `restic backup --exclude-other-filesystems / /mnt/foo /mnt/bar` should backup at least from the three FS that are listed.

So, I'd go for `--exclude-other-filesystems`. This also matches the other exclude options.

**Comment by fd0** [comment]
Ok, we agree, great!

**Comment by rfjakob** [comment]
BTW while I am waiting for the CI to complete: Can I run the test suite locally? This is what I get from a naive attempt:
```
$ go run run_integration_tests.go
unknown CI environment
exit status 1
```

**Comment by fd0** [comment]
The `run_integration_tests.go` is just for CI, it sets up things and so on. You can use `gb test` locally. It won't run things that depend on external services, e.g. the s3 backend isn't tested, but for this issue it should work just fine.

**Comment by rfjakob** [comment]
Found it, it's documented in CONTRIBUTING.md, thanks!

**Comment by fd0** [comment]
The last error is about the stdlib `errors` package, use `restic/errors` for awesome stacktraces (provided by https://github.com/pkg/errors)

**Comment by pvgoran** [comment]
Well, IDK, both `tar` and `rsync` can have multiple path arguments as well. For `rsync`, the man page even explicitly says that `--one-file-system` does not interfere with specifying paths from different filesystems.

BTW, `attic` uses `--do-not-cross-mountpoints`, which is a more verbose and non-ambiguous variant.

**Comment by rfjakob** [comment]
CI passes, should be good to merge.

I don't care too much about the name, but I do care about having the feature, so let's not bikeshed this too much.

**Comment by rfjakob** [comment]
That tar and rsync both use "--one-file-system" and both allow multiple source directories actually convinced me to rename it. @fd0 you file with that?

**Comment by fd0** [comment]
I'm okay with that ;)

**Review by fd0 — APPROVED** [review]
LGTM :+1:

**Comment by fd0** [comment]
Hm, I think there's a somewhat obscure issue with the current implementation. I'm not sure if it's worth opening an issue about (and fixing it), so maybe we can discuss it here.

At the moment we have a list of allowed device IDs, and when the dirs given on the command line are walked, restic checks that items are located on one of the allowed devices.

But what happens when one of the allowed devices is mounted below one of the other directories? Let's say, `/dev/sda1` is mounted at `/mnt/foo` and again at `/mnt/bar/baz/foo`, then running `restic backup --one-file-system /mnt/foo /mnt/bar` would walk down to `/mnt/bar/baz/foo`, because it is in the list of allowed devices. The same may happen when there's a bind mount... Do we need to handle this case?

ping @rfjakob

**Comment by pvgoran** [comment]
IMHO it should be handled. Adding an additional backup target to the command line should not have such far-reaching consequences as modifying the scope of existing backup targets.

**Comment by pvgoran** [comment]
I'd prefer even bind mounts to be detected and skipped, but it may be difficult to implement this well (device ID will no longer help us), and rsync doesn't do it. :)

**Comment by rfjakob** [comment]
Maybe we should check if the device id is different from that of the
respective parent dir. This effectively skips all mountpoints.

**Comment by pvgoran** [comment]
Except for inner-filesystem binds.

**Comment by fd0** [comment]
What about having just one allowed device ID per directory passed to the `backup` command? We could make `map[string]uint64` and select the longest matching prefix with the current path from the keys of that map to find the current device ID.

**Comment by pvgoran** [comment]
I don't know how the scanning process work, but maybe it can remember the "root" directory (the backup target passed to restic) from where the file/directory that's currently being scanned originated?

**Comment by fd0** [comment]
I've created a new issue for this, let's move the discussion there: https://github.com/restic/restic/issues/645

**Pull request merged**
