### PR TITLE
sftp ReadDir: add path to return error messages (gh-1323)

### LINKED ISSUE #1323: SFTP Permission denied do not say what path failed, and sometimes error silently
## Output of `restic version`

restic version
restic 0.7.2 (v0.7.2-0-g5b1e4df1)
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?

restic backup -x /

## What backend/server/service did you use?

sftp

## Expected behavior

SSH Permission denied "/path/to/repo/file"

## Actual behavior

SSH Permission denied [unknown file]

## Steps to reproduce the behavior

I had mounted a disk with my repo on it remotely but with the wrong user ids..

I chowned a bunch of files to the right id when I found out my mistake, but some
got missed after it had been cancelled

## Do you have any idea what may have caused this?

I was a bit silly.

## Do you have an idea how to solve the issue?

Add the path to the file that caused the error message.

If the key files are unreadable it silently fails with no error at all (this was a little scary)

### PR DESCRIPTION
**Pull request by armhold**
also fix missing "Close" string in debug log fmt

Closes #1323

### CODE REVIEW

**Review by fd0 — APPROVED** [review]
Oh, great catch!

FYI: Include the GitHub issue ID like this `#1323`, then it will be automatically linked in the UI (and there'll be a backlink in the issue): #1323

For GitHub, it is best practice to mention the issue ID in the text of the pull request, so there will be nice links back and forth between the issue and the PR.

I've added the text `Closes #1323` to the PR message, so the issue will be closed automatically when the PR is merged.

**Comment by armhold** [comment]
Sorry about the misplaced issue ID. I thought including "gh-1323" in both the commit text as well as the PR "subject" line would cover it, but I guess not. :-)

**Comment by fd0** [comment]
No worries, I was surprised that GitHub even linked the `gh-1323` text. :)

**Comment by armhold** [comment]
Yeah "gh-FOO" is a standard shortcut for github commits and they get automatically linked. The "#foo" one was news to me. :-)

**Pull request merged**
