### PR TITLE
Add --ignore-inode option to backup cmd.

### PR DESCRIPTION
**Pull request by giacomocariello**
What is the purpose of this change? What does it change?
--------------------------------------------------------

This PR adds --ignore-inode option to backup command, in order to support those filesystems that don't support fixed inodes, typically Fuse, pCloud, etc.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

It was already discussed #1631.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by pabs3** [comment]
This reduced the amount of time it took for converting my rdiff-backup snapshots to restic snapshots from over an hour to under 8 minutes. I would love to see it merged into restic mainline.

**Review by fd0 — CHANGES_REQUESTED** [review]
Thank you very much for your contribution! I've had a look at the code, while it get's the job done, a *lot* of places must be touched to pass in an option of type `ModifiedIgnores`, which only has one field. That feels overly generic to me.

I'd like to propose a different approach:
 * Add a new field to the `Archiver` struct, `IgnoreInode bool`
 * Change the signature of `fileChanged` like this:
```go
func fileChanged(fi os.FileInfo, node *restic.Node, ignoreInode bool) bool
```
 * Pass the `arch.IgnoreInode` to `fileChanged`

The default value for the bool is false, so the inode is checked.

What do you think? Please let me know if you need any help!

Other nitpick: Can you please remove the trailing `.` from the summary line fro the commit messages? Thanks!

**Comment by giacomocariello** [comment]
@fd0 yup, no problem on my side. I'll try and apply your requests. The idea of having a struct to handle multiple types of ignore flags was probably overengineered at this stage.

**Comment by fd0** [comment]
Hey, are you still interested in working on this? Is there anything you need, or are you stuck?

**Comment by robvalca** [comment]
I'm really interested in this feature, do you know if it will go in, finally? :)

**Comment by fd0** [comment]
@robvalca this PR is incomplete, it looks like @giacomocariello did not have the time to rework it yet. So we need to wait until this happens (or somebody else volunteers to do it) :)

**Comment by robvalca** [comment]
@fd0, @giacomocariello  do you think that I could take on this? I'm newbie in golang (and btw in github collab) but with the work already done and some help I think that I could finish this. :)

**Pull request closed without merging**
