### PR TITLE
Set default value for password-file flag from env

### PR DESCRIPTION
**Pull request by donat-b**
Allows defining password file path as RESTIC_PASSWORD_FILE=/foo

### CODE REVIEW

**Comment by donat-b** [comment]
Rebased to master.

**Comment by fd0** [comment]
LGTM, thanks!

**Comment by donat-b** [comment]
By the way, are these variables documented anywhere besides cli help?

**Comment by fd0** [comment]
Not yet, no. The `RESTIC_PASSWORD` and `RESTIC_REPOSITORY` are documented in the manual: https://restic.readthedocs.io/en/latest/manual.html#local

**Pull request merged**
