### PR TITLE
Fix ModTime for directories

### LINKED ISSUE #24: Correctly restore timestamps
Some timestamps for directories are not restored, this should be corrected.

### PR DESCRIPTION
**Pull request by fw42**
Fixes https://github.com/restic/restic/issues/24.

But a similar issue exists with symlinks. It seems that it's currently not possible to call the [lutimes](http://linux.die.net/man/3/lutimes) system call to change symlink timestamps (without dereferencing the link). I'm gonna open a separate GitHub issue for that after this PR is merged.

### CODE REVIEW

**Comment by fw42** [comment]
A fix for this has been merged upstream 8 days ago (https://go-review.googlesource.com/#/c/9379/).

**Comment by fw42** [comment]
Looks like I made coverails unhappy :-/

I don't think it's worth it to add a unit test for this new function. The code has just as much test coverage as before via the shell scripts.

**Comment by fd0** [comment]
I've set the failure threshhold to 5%, I hope that this is the right value. The meaning of the fields in the coveralls settings panel aren't explained anywhere.

This should also be gone once #179 is done, afterwards the integration tests count towards the coverage.

**Comment by fw42** [comment]
Does this solution make sense to you? Iterate over the directories a second time at the end. Or is that too inefficient?

**Comment by fd0** [comment]
Looks good to me. We could also fix the timestamps for dirs right after all nodes have been restored to, before returning from `restoreTo()`, what do you think?

**Comment by fw42** [comment]
Hm not sure what you mean by that. We need to do this **after** all non-dirs have already been restored.

**Comment by fd0** [comment]
Yeah, I know, but we can do this directly after all the nodes in a dir have been created, no need to iterate a second time.

**Comment by fw42** [comment]
You mean right after [this](https://github.com/restic/restic/blob/1fb8e332ce031e92a210bab5ac6e00b720eac0c9/restorer.go#L57) returns?

**Comment by fw42** [comment]
oh, you already did that.

**Comment by fd0** [comment]
Exactly. ;)

**Comment by fw42** [comment]
works for me :rocket:

**Comment by fd0** [comment]
since travis and coveralls are happy, I'm merging this.

**Pull request merged**
