### PR TITLE
backup: Fix possible deadlock of scanner goroutine

### LINKED ISSUE #2834: restic backup hangs forever most of the times
Output of `restic version`
--------------------------
`restic 0.9.6 (v0.9.6-249-g2c72924f) compiled with go1.14.3 on linux/amd64` but also happens with `restic 0.9.6 compiled with go1.13.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
$ restic --cacert /root/.restic/ca-bundle.pem --cache-dir /home/.cache/restic backup --exclude-caches --one-file-system --exclude /var/log/lastlog -v / /home /var/lib/mysql_binlog
open repository
lock repository
load index files
using parent snapshot a9f3206e
start scan on [/ /home /var/lib/mysql_binlog]
start backup on [/ /home /var/lib/mysql_binlog]
```
No further output. When invoking with `-vv` the scanned/backuped files are printed (`/var` being the last entry), but eventually no further output appears.

Environment:
```
RESTIC_REPOSITORY=s3:https://<redacted>:9000/<redacted>
RESTIC_PASSWORD=<redacted>
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3/Minio in a Docker container: `minio/minio:RELEASE.2020-07-13T18-09-56Z` - was using an older version before and updated to the latest version.

Expected behavior
-----------------
Perform a backup and exit with status code `0` after several hours.

Actual behavior
---------------
Backups are started once per day. With only a few exceptions the restic process runs "forever" and I killed it every time once it was running for several days. In the past, backups finished after a few hours.
The odd thing is, `restic snapshots` shows a snapshot was created, but the restic process creating this very snapshot still hasn't finished.
When the process seems to have stalled, `strace` shows the following (excerpt):
<details>
  <summary>strace -e trace=file -f -p $(pidof restic)</summary>

```
$ strace -e trace=file -f -p $(pidof restic)
strace: Process 1820 attached with 19 threads
[pid  1829] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1832] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1828] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1991] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1830] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1992] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid 32217] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1830] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid 17224] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
...
```
</details>

<details>
  <summary>strace -f -p $(pidof restic)</summary>

```
$ strace -f -p $(pidof restic)
strace: Process 1820 attached with 19 threads
[pid 32217] futex(0xc00048ebc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 17224] futex(0xc000101d48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  3202] futex(0xc000100f48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1992] futex(0xc00048e148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1990] futex(0xc0001012c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1834] futex(0xc0001004c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1833] futex(0xc00048e848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1832] futex(0xc000202148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1830] futex(0xc0001824c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1829] futex(0xc0000ee148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1828] futex(0xc000182148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1827] futex(0x1479978, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1825] futex(0x1479a80, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1824] futex(0xc00006e4c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] restart_syscall(<... resuming interrupted restart_syscall ...> <unfinished ...>
[pid  1820] futex(0x144f628, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 0, NULL, 660846458731897) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... restart_syscall resumed>) = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=998351272} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 4400, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4217995752368244) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999120646} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 9976, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4193702090911558) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=815346751} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 9979, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4429449491030384) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] <... futex resumed>)        = 1
[pid  1991] <... futex resumed>)        = 0
[pid  1991] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] <... nanosleep resumed>NULL) = 0
[pid  1991] futex(0xc00048ebc8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 32217] <... futex resumed>)        = 0
[pid 32217] futex(0xc00048ebc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1991] write(6, "\27\3\3\0\23\315\370\367w\211\302\"\265\25L%\32315\350\262\24\314\266", 24 <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1991] <... write resumed>)        = 24
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1991] epoll_ctl(3, EPOLL_CTL_DEL, 6, 0xc0000a06ac <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1991] <... epoll_ctl resumed>)    = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] close(6)                    = 0
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 769, NULL, 0) = 0
[pid  1991] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1826] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] <... nanosleep resumed>NULL) = 0
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=179382066} <unfinished ...>
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 2516917869055365) = 0
[pid  1835] epoll_pwait(3, 
```
</details>

Steps to reproduce the behavior
-------------------------------
As far as I can tell the issue is not reliable reproducible. It appears with 0.9.6 and recent beta builds.
I've also run a debug build of restic (`restic 0.9.6 compiled with go1.14 on linux/amd64`) and while this build takes significantly longer to perform a backup and fills the `DEBUG_LOG` file, it worked every single time (or maybe I just haven't tried often enough?).

Do you have any idea what may have caused this?
-----------------------------------------------
No, but since we've deployed restic on hundreds of machines with basically identical configuration I suspect this single machine is the root cause. Unfortunately I have no clue what this might be and to the best of my knowledge the machine in question also does not differ significantly from others.

Do you have an idea how to solve the issue?
-------------------------------------------
Well, no. What I've tried so far:
- rebooted machine and fsck'ed all filesystems (ext4, xfs) 
- tried different restic builds and a debug build of version 0.9.6
- backed up to a new repository

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic really has proven itself over time and I'm looking forward for future improvements. Thank you everyone who is contributing lately and keeps the project alive!

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
If the backup operation is canceled at just the wrong moment, then it is possible that the scanner or other parts of restic hang while trying to report some progress updates. This can happen as a cancellation also causes the progress UI goroutine to exit and therefore the calls to report progress get stuck permanently.

This PR adds an additional channel which serves as an escape hatch in that case, see the commit message for further details.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
The bug showed up in the stacktrace in Issue https://github.com/restic/restic/issues/2834#issuecomment-699874185 .

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- ~~[ ] I have added documentation for the changes (in the manual)~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by lorenzbausch** [comment]
Tried this fix on a host where restic backup was hanging previously and backup completed just fine :muscle:

**Comment by lorenzbausch** [comment]
Confirming that this also works on another host, nice :+1:

**Review by fd0 — APPROVED** [review]
LGTM

**Comment by lorenzbausch** [comment]
Thank you :)

**Pull request merged**
