### PR TITLE
Only restore blobs which don't exist locally

### LINKED ISSUE #407: Make restore resumeable.
I just tested restore and noticed, that I (maybe) can't download all by data from my sftp source until the next DSL reconnect. When reconnecting, the connection of course breaks and restore fails.

When I start a new restore to resume, all old files are overwritten once again.

It would be nice to be able to resume restore, for example be checking if already in the restore-dir present files are already the same as those which would be restored and therefore be skiped to save time.

For now, this is only a test to check restore, so there is no need for quick hot-fixes like restoring seperate dirs with include/exclude.

### PR DESCRIPTION
**Pull request by Novex**
* If we can, calculate the hash of the part of the local file that the blob corresponds to
  * If it matches then we already have the data and can skip fetching it
  * This should significantly improve the speed of remote restores when a local dataset already exists

This should allow for resumable restores, which resolves #407 and possibly also #200 (if I understand it correctly)

### CODE REVIEW

**Comment by fd0** [comment]
Thanks again for your contribution! I think it's a good idea, but we'll need to handle a few corner cases. I'll add more comments in the evening (Europe here).

**Comment by Novex** [comment]
No worries! Looking forward to them :)

**Comment by Novex** [comment]
No pressure, just following up as to whether you had a chance to take a look at this?

**Comment by fd0** [comment]
Thanks for asking: I was a bit busy this week and did not have the time yet, sorry.

**Comment by Novex** [comment]
No worries at all - I know that feeling :)

**Comment by fd0** [comment]
So, I have some feedback for you: I've thought a lot about how to handle this and I think that modifying files directly is a bad idea because it can easily go wrong. Suppose a user restores their home directory while a program is still running and both restic and the program modify the same file. The result will almost always be a corrupt file, which is a bad idea.

I had a look what other programs do and I like the approach implemented by rsync: By default, if a destination file already exists, it creates a new temp file with a random name right next to it, starts reading the already present file and copies any valid content from the old to the temp file (for restic this means running a chunker on the old file and copying any blobs that should be present in the new file). All blobs not present in the old file are fetched from the repo and written to the new file. Once the new file is complete, rename the new (temp) file to the old one so that it is atomically replaced.

What do you think? Are you interested in implementing this approach? I'd be glad to assist!

I'm going to close this PR since I won't merge the code in this form.

**Comment by Novex** [comment]
Fantastic point! I'm happy to have a crack at implementing it.

Just so I have this clear:
* The current default behaviour of restic restore when a file exists is to overwrite each chunk of the file currently being restored in-place
  * Which leads to many of the risks you mentioned, eg. another program modifying the file/inconsistent results should restic fail
* We want to change it so the default behaviour is to instead restore the the file currently being restored beside the existing one, then atomically replace the existing one on success
  * A safer option, but has the downside of temporarily requiring twice as much disk space as the size of the currently restored file
* In addition, we want to add a new flag `--inplace` to restore the original default behaviour with the optimisation of only overwriting chunks which have changed

Does that sound about right?

**Comment by fd0** [comment]
That's mostly right, just a small correction to the first point: the current behavior is to create a new file which replaces any old file that may exist via the flag `O_CREATE` to the `os.OpenFile` call here: https://github.com/restic/restic/blob/master/src/restic/node.go#L195 The flag tells the kernel to either create the file (file does not exist yet) or truncate it (file already exists).

**Comment by fd0** [comment]
Let's create a new issue and transfer the discussion and todo list there.

**Pull request closed without merging**
