### PR TITLE
Add JSON support for the restore progress bar

### LINKED ISSUE #3413: json output for restore command
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.15.8 on windows/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
New functionality : Needed a json output for the restore command.
With it, UI can do report for long operation.
The same output structure as backup was very good.

When I am trying : `.\restic.exe restore latest -r "g:\backup\repo" --target "g:\tmp\"  --json`
There is no json output.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Report user progress of restore command in [resticterm](https://github.com/GPh83/resticterm).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes.
Very happy of this good tool.
Thanks

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Add rudimentary JSON output for restore command. There is no progress for the `restore --verify` option so far (but also progress bar in the normal text output).

The JSON format is in parts copied from that used by the backup command.

TODOs:
- [x] The error output is still plain text and is not synchronized with the progress bar updates
- [x] Finalize format of JSON output

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Fixes #3413

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- ~~[ ] I have added documentation for relevant changes (in the manual).~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
Sample output:
```
{"message_type":"status","percent_done":0,"total_files":341,"total_bytes":491885}
{"message_type":"status","percent_done":0.002789074629979167,"total_files":652,"files_done":25,"total_bytes":21859580,"bytes_done":60968}
{"message_type":"status","percent_done":0.2789919568445505,"total_files":652,"files_done":581,"total_bytes":21859580,"bytes_done":6098647}
{"message_type":"status","percent_done":0.6608266490024054,"total_files":652,"files_done":635,"total_bytes":21859580,"bytes_done":14445393}
{"message_type":"status","percent_done":1,"total_files":652,"files_done":651,"total_bytes":21859580,"bytes_done":21859580}
{"message_type":"summary","total_files":652,"files_done":652,"total_bytes":21859580,"bytes_done":21859580}
```

**Comment by MichaelEischer** [comment]
I've replaced `done` in the field names with `restored` except for the `percent_done` field.

**Review by MichaelEischer — COMMENTED** [review]
LGTM.

**Comment by GPh83** [comment]
Thanks

**Pull request merged**
