### PR TITLE
Update tests to Go 1.19

### PR DESCRIPTION
**Pull request by lbausch**
What does this PR change? What problem does it solve?
-----------------------------------------------------

With Go 1.19 being released, I gave it a shot and updated GitHub Actions to test against Go 1.19

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Not that I'm aware of.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by lbausch** [comment]
- [ ] golangci/golangci-lint-action@v2 needs a new release to support v1.48
- [ ] some tests fail with 1.19, need to examine further

**Comment by lbausch** [comment]
It seems like `TestApplyPolicy` fails because the sorting of snapshots differs when checking with `cmp.Equal(want.Keep, keep, cmpOpts)`.
The [1.19 release notes](https://go.dev/doc/go1.19#sort) mention that the sorting algorithm has been rewritten to use pattern-defeating quicksort and `ApplyPolicy` in `internal/restic/snapshot_policy.go` actually calls `sort.Sort(list)`. Might this be the reason and if so, would altering the testdata be a feasible approach?

**Comment by MichaelEischer** [comment]
> The [1.19 release notes](https://go.dev/doc/go1.19#sort) mention that the sorting algorithm has been rewritten to use pattern-defeating quicksort and `ApplyPolicy` in `internal/restic/snapshot_policy.go` actually calls `sort.Sort(list)`. Might this be the reason and if so, what's a feasible approach here? Altering the testdata might possibly break the tests running against older Go versions.

That is exactly the problem. `sort.Sort` is not guaranteed to be stable according to the documentation, yet the tests relied on a specific order among snapshots with identical timestamps (sorting is exclusively based on the timestamp!). Thus the order changed. My suggestion (see the commit I've pushed) would be to switch to stable sorting for the snapshots, as I don't see a meaningful order for these snapshots. The stable order should remain consistent across Go version, so we won't run into problems there.

**Comment by lbausch** [comment]
Great, thank you @MichaelEischer! Do we need a changelog entry for the new Go version?

**Comment by MichaelEischer** [comment]
@lbausch I don't think we need a changelog entry. We're just adding support for an additional version, but not removing one.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks a lot! I already ran into the test failures with Go 1.19 a few times.

**Pull request merged**
