### PR TITLE
fuse: added symlink 'latest' to snapshots-dir

### PR DESCRIPTION
**Pull request by mungomat**
I am not sure about 'a.Nlink = 1'

### CODE REVIEW

**Comment by fd0** [comment]
Good idea, let me know when you need help with the integration tests! At the moment, this test is failing: https://travis-ci.org/restic/restic/jobs/276993945#L598:

https://github.com/restic/restic/blob/01c486d4863adcbd269a614f255c86d7123e0f72/cmd/restic/integration_fuse_test.go#L100-L103

You need to test for the presence of the `latest` link, and add one to the number of expected entries.

**Comment by mungomat** [comment]
Now the test cases check for 'latest' symlink and the expected number of files is adjusted. Unfortunately the current error message is not telling me enough (Index has old format, lstat: [...] no such file

**Comment by fd0** [comment]
I'll have a look, the messages that are included there are from other tests.

**Comment by fd0** [comment]
So, my analysis: The Travis log shows that `TestMount` failed, so we'll just run that:
```
$ cd cmd/restic
$ go test -v -run TestMount
=== RUN   TestMount
Now serving the repository at /tmp/restic-test-153362927/mount
Don't forget to umount after quitting!
Now serving the repository at /tmp/restic-test-153362927/mount
Don't forget to umount after quitting!
Now serving the repository at /tmp/restic-test-153362927/mount
Don't forget to umount after quitting!
Now serving the repository at /tmp/restic-test-153362927/mount
Don't forget to umount after quitting!
--- FAIL: TestMount (1.39s)
        testing.go:30: using low-security KDF parameters for test
        testing.go:30: using low-security KDF parameters for test
        lock.go:77: setting lock timeout to 0s
        integration_test.go:51: repository initialized at /tmp/restic-test-153362927/repo
        integration_fuse_test.go:86: checking for 0 snapshots: []
        integration_fuse_test.go:47: mounted directory is ready
        integration_fuse_test.go:97: found 0 snapshots in repo: []
        integration_fuse_test.go:100: found 0 snapshots in fuse mount: []
        integration_fuse_test.go:113: Symlink latest isn't present in fuse dir
        integration_fuse_test.go:66: directory /tmp/restic-test-153362927/mount umounted
        integration_test.go:55: backing up [/tmp/restic-test-153362927/testdata]
        integration_fuse_test.go:86: checking for 1 snapshots: [06560e04]
        integration_fuse_test.go:47: mounted directory is ready
        integration_fuse_test.go:97: found 1 snapshots in repo: [06560e0412b58eac81cbf6dc9ddb960387178030eee191655f5d8030d223ff06]
        integration_fuse_test.go:100: found 2 snapshots in fuse mount: [2017-09-20T12:17:38+02:00 latest]
        integration_fuse_test.go:66: directory /tmp/restic-test-153362927/mount umounted
        integration_test.go:55: backing up [/tmp/restic-test-153362927/testdata]
        integration_fuse_test.go:86: checking for 2 snapshots: [06560e04 65a9af4a]
        integration_fuse_test.go:47: mounted directory is ready
        integration_fuse_test.go:97: found 2 snapshots in repo: [65a9af4a53a2827284e829e423ed2987d80cf9fe45954c1864ab9b10e2e95213 06560e0412b58eac81cbf6dc9ddb960387178030eee191655f5d8030d223ff06]
        integration_fuse_test.go:100: found 3 snapshots in fuse mount: [2017-09-20T12:17:38+02:00 2017-09-20T12:17:38+02:00-1 latest]
        integration_fuse_test.go:66: directory /tmp/restic-test-153362927/mount umounted
        integration_test.go:55: backing up [/tmp/restic-test-153362927/testdata]
        integration_fuse_test.go:86: checking for 3 snapshots: [06560e04 65a9af4a a75b6872]
        integration_fuse_test.go:47: mounted directory is ready
        integration_fuse_test.go:97: found 3 snapshots in repo: [a75b6872a9692af717f6b58bb3c5d6c3f640680b14f9d5e51f72f1ad682507bc 65a9af4a53a2827284e829e423ed2987d80cf9fe45954c1864ab9b10e2e95213 06560e0412b58eac81cbf6dc9ddb960387178030eee191655f5d8030d223ff06]
        integration_fuse_test.go:100: found 4 snapshots in fuse mount: [2017-09-20T12:17:38+02:00 2017-09-20T12:17:38+02:00-1 2017-09-20T12:17:38+02:00-2 latest]
        integration_fuse_test.go:66: directory /tmp/restic-test-153362927/mount umounted
FAIL
exit status 1
FAIL    github.com/restic/restic/cmd/restic     1.395s
```

Let's see what's going on here, the relevant error messages are:
```
--- FAIL: TestMount (1.39s)
        [...]
        integration_fuse_test.go:97: found 0 snapshots in repo: []
        integration_fuse_test.go:100: found 0 snapshots in fuse mount: []
        integration_fuse_test.go:113: Symlink latest isn't present in fuse dir
        [...]
```

So the repo is mounted, there are zero snapshots, and also the `latest` symlink isn't present. That's the error.

You need to change in `checkSnapshots()` so that it only checks for the presence of `latest` when there's more than zero snaphots.

**Review by fd0 — APPROVED** [review]
Awesome, thank you very much for your contribution!

**Pull request merged**
