### PR TITLE
Dynamically increase pack size with repository size

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Currently packs are written once they reach the size of 4MB. In practice this leads to average pack sizes of around 4.7 MiB.
This means that large repositories contain of a large amount of pack files, e.g.
1 GiB -> ~200 pack files
1 TiB -> ~205,000 pack files (!)
1 PB -> ~215,000,000 pack files (!!!) 

Lots of small pack files pose problems in some cases, e.g. performance issues or high costs with some storage providers. Moreover with a lower number of pack files memory usage is a bit reduced.

In #2750 it is proposed to let users specify the pack size. A sensible choice would be to choose a pack size of `sqrt(reposize in GB) * 4 MiB`. This would lead to 
1 GiB -> ~256 pack files a 4 MiB
1 TiB -> ~8,200 pack files a 128 MiB
1 PiB -> ~260,000 pack files a 4 GiB
This would however need a priori knowledge of the repository size.

Hence this PR uses the current reposize to determine the pack size by the above formula and therefore dynamically increases the pack size with growing repo size.
This dynamic increase roughly doubles the number of the pack files compared to the table above.

For very small repos a pack size of 4MiB is still targeted and for very large repos (> 1 PiB) the pack size is limited to 4076 MiB such that including pack headers the total pack will not exceed 4 GiB.
Moreover, the number of blobs per pack is limited such that no problems with large pack headers or index files occur.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
see #2750 and the references therein.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by aawsome** [comment]
The argument why the dynamic increase of pack file size roughly doubles the number of files is the following:

Having a repo of `x_total` GiB and a constant pack size of `sqrt(x_total) * 4MiB`, you have around
```x_total * 1024 / (sqrt(x_total) * 4) = 256 * sqrt(x_total)```
pack files.

If you use a dynamic pack file size of `sqrt(x) * 4MiB` where `x` is the current pack size in GB, your number of pack files is around
```
integral_0^{x_total}  1024 / (sqrt(x) *4) dx = 256 integral_0^{x_total}  1 / sqrt(x) = 256 * 2 * sqrt(x_total)
```

**Comment by vejnar** [comment]
In my opinion, this is a great idea: number of files for large repositories is really a problem in my case and that solution wouldn't require any config from users. However, I would really like having `smallestPackSize` exposed as an option, similarly to what #2750 is proposing.

**Comment by aawsome** [comment]
@vejnar Of course we could easily add an option to adapt this into the `MinPackSize()` function I introduced here. However one of the more difficult discussions #2750  was whether we should or shouldn't make such technical options available to users. I personally like having more options; but I also fully support the philosophy of restic being "opinionated".

In any case you can compile your own version with a changed constant. With this PR this would be the `smallestPackSize` constant in `internal/repository/repository.go`.

**Comment by aawsome** [comment]
There is one drawback in the "dynamic" increase of pack sizes: You still get some small (first) packs even for large repositories.

I think this can be tackled in a follow-up PR which should change `prune` in the following way:
- determine the used repo size after pruning (this is already done in `prune`)
- compute the preferred pack size for this target state
- mark some packs that are way too small (or way too large) for repacking within `prune`

This would allow to swing in the pack sizes if a "constant" repo size is reached.

**Comment by wzrdtales** [comment]
hit this while trying to understand why min-packsize was removed. Especially on slower devices it is beneficial to have upfront bigger pack files since too many small pack files will destroy performance completely...

**Comment by pjannesen** [comment]
hit this while trying to understand why min-packsize was removed. Especially on slower devices it is beneficial to have upfront bigger pack files since too many small pack files will destroy performance completely...

_Originally posted by @wzrdtales in https://github.com/restic/restic/issues/3367#issuecomment-836589646_

Same for me. Restic works great if you have a lot of small files (like software development) and the target is a local SDD. If you use Restic under windows and the target is an external HD a packsize of 4MB is a disaster!

To make Restic work in all different environments there must be a way to specify the min-packsize. 

PS: The standard of 4 MB is low. The default of duplicati is 50MB if I am correct.

**Comment by aawsome** [comment]
Closing this as I won't invest more time here.
If anyone wants to try out dynamically increasing pack sizes, I'd recommend to switch to [rustic](https://github.com/rustic-rs/rustic)

**Pull request closed without merging**
