### PR TITLE
Add swift backend

### PR DESCRIPTION
**Pull request by fd0**
Supersedes #648

### CODE REVIEW

**Comment by fd0** [comment]
Waiting for review by @byo, @jayme-github.

**Comment by byo** [comment]
Just a quick update, I did some tests yesterday and doing some more tests on larger dataset today. 

Nothing blocking this feature for me so far, one issue most likely related to temporary issue at OVH's swift backend.

Other issue is that I can't rebuild index (which was advised when doing repository check) - could be caused by the fact that my current repo is a mix of three repository layouts (I'm doing copy instead of moving files just in case). Here's the error msg, I didn't yet have time to investigate it:

```
# ./restic rebuild-index
counting files in repo
[0:03] 0.18%  79 / 44189 packs
pack 00096d34 already present in the index
restic/index.(*Index).AddPack
	/tmp/restic-build-767832204/src/restic/index/index.go:169
restic/index.New
	/tmp/restic-build-767832204/src/restic/index/index.go:61
main.rebuildIndex
	/tmp/restic-build-767832204/src/cmds/restic/cmd_rebuild_index.go:53
main.runRebuildIndex
	/tmp/restic-build-767832204/src/cmds/restic/cmd_rebuild_index.go:41
main.glob..func14
	/tmp/restic-build-767832204/src/cmds/restic/cmd_rebuild_index.go:19
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-767832204/src/github.com/spf13/cobra/command.go:631
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-767832204/src/github.com/spf13/cobra/command.go:710
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-767832204/src/github.com/spf13/cobra/command.go:669
main.main
	/tmp/restic-build-767832204/src/cmds/restic/main.go:60
runtime.main
	/usr/local/go/src/runtime/proc.go:183
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2086
```

Migration script: https://gist.github.com/byo/dc21c47c5ed1320f0f85bb6dcf8cf9c8

**Comment by fd0** [comment]
Oh yes, that is indeed caused by a mix of different repository layouts: The pack file `00096d34` is present more than once in the repo. It will go away when you remove the old files.

**Comment by byo** [comment]
No more errors / warnings after cleaning up my swift repository. Works fine on ~100GB of data to backup.

**Comment by fd0** [comment]
Nice, then I can merge this!

**Comment by fd0** [comment]
I've cleaned up the commits a bit and pushed them, when the CI tests are happy I'll merge this (so it'll be in the next release).

**Comment by jayme-github** [comment]
Migrated my repos yesterday. New snapshots as well as restore working as expected. Thanks @fd0!

**Comment by fd0** [comment]
Great, thanks for the feedback!

**Comment by byo** [comment]
Testing master for few days, works flawlessly so far. Thanks @fd0 for taking care of this!

**Comment by namsral** [comment]
Compiled restic from master (`gbd7d5a4`) to include support for OpenStack Swift but I can't initialize the repository:

```sh
$ source openrc.sh
Please enter your OpenStack Password:
$ restic version
restic 0.6.1 (v0.6.1-71-gbd7d5a4)
compiled with go1.8.3 on linux/amd64

$ restic -r swift:restic:/huxley init
enter password for new backend:
enter password again:
create key in backend at swift:restic:/var failed: client.PutObject: Object Corrupted
```

**Comment by fd0** [comment]
Please open a new issue and create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs). Thanks!

**Comment by namsral** [comment]
Ok, see https://github.com/restic/restic/issues/1039

**Pull request merged**
