### PR TITLE
Feat support for azure custom domain

### PR DESCRIPTION
**Pull request by konidev20**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Microsoft allows you to map custom domains to Storage Accounts. [Map a custom domain to an Azure Blob Storage endpoint](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name)

This PR adds support for restic to Microsoft Storage Accounts with custom domains. The idea is to add an environment variable `AZURE_CUSTOM_DOMAIN` to allow a user to specify the custom domain. If this environment variable is not set, it will default to `core.windows.net`; if `AZURE_ENDPOINT_SUFFIX` is configured, it will set that.

~~The second step is, that if your custom domain has not been configured with a certificate, we should allow the user to force the usage of HTTP. The user here is expected to explicitly specify that using the option `-o usehttp=true` (this is similar to the S3 implementation, which allows for HTTP connections). The option of specifying `-o usehttp=true` will only be available for custom domains.~~

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
https://github.com/restic/restic/issues/4438 -> ~~here I had proposed to add support for HTTP connections universally for Microsoft Blob Storage, at that time we concluded that we could add this when we had a good enough reason. I do believe, with custom domains, we have a good reason to enable HTTP connections for it. ~~

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
> I do believe, with custom domains, we have a good reason to enable HTTP connections for it.

My last reply to that suggestion in #4438 was that this is insecure. It doesn't matter whether the HTTP connection is towards a custom domain or the default azure domain name. In particular, as the default azure domain name always support HTTPS, there's no need to support HTTP. Just use the default domain name if you can't setup HTTPS for the custom domain. Just to be clear, I'm strictly opposed to adding `-o usehttp=true`.

I'd also like to know more about the use case, right now this PR and the previous issue just look like "we're adding this because we can". The custom domain example I can find usually just refer to accessing (reading) files via the custom domain. Does uploading files actually work?

**Comment by konidev20** [comment]
> I'd also like to know more about the use case, right now this PR and the previous issue just look like "we're adding this because we can". 

Yes, adding this because we can for now. There are use cases where a system administrator might whitelist only specific domains through which data can be accessed/uploaded; behind a firewall. You might argue that whitelisting `core.windows.net` might do the trick, but we should give the user flexibility to choose how they configure their environments. Since the storage provider allows for such connections, there is definitely a use case out there. I was experimenting with changing backends dynamically by setting up only `backup.contoso.com/repo` and switching Azure regions and even to an S3-compatible storage just by using the custom domain name. 

>  Just use the default domain name if you can't set up HTTPS for the custom domain.

Okay. That restricts the way users will be able to use the Microsoft Blob Storage for backups. As a tool, we must not restrict the way users are able to use the application, because we deem it to be insecure. The user can be in varied environments with different needs. The requirement of the user having to explicitly specify `-o usehttp=true` means the user is aware of the risk of that operation. 

> The custom domain example I can find usually just refers to accessing (reading) files via the custom domain. Does uploading files actually work?

Yes. I have added integration tests and it has passed. I have tested backups and restores on my machine and it worked, with and without HTTP.

**Comment by konidev20** [comment]
[Edit] Let me add one more thing: Just because Azure provides some feature, this does not automatically mean that restic should support it. Adding a feature for which there's no need in restic, just to have a "reason" to add another is just nonsense. [/Edit] 
 
 Okay, I will agree to disagree. Sorry for wasting your time.

**Comment by rawtaz** [comment]
Sorry if this is a stupid question, but using a custom domain to me seems like a separate thing than whether you encrypt traffic or not. Why would you not want to use HTTPS even when you use a custom domain? Even if there's a point to use a custom domain, I don't see why one would want to send their credentials unencrypted.

**Comment by konidev20** [comment]
@MichaelEischer can I remove the HTTP code?

**Comment by rawtaz** [comment]
It was just a curious question, since that part is quite unclear.

**Comment by konidev20** [comment]
> Sorry if this is a stupid question, but using a custom domain to me seems like a separate thing than whether you encrypt traffic or not. Why would you not want to use HTTPS even when you use a custom domain? Even if there's a point to use a custom domain, I don't see why one would want to send their credentials unencrypted.

If I'm in a virtual network, with a custom DNS setup. The threat model for me is that the communication is within the network.

If I use `core.windows.net` connections can go over the internet in the case of Azure.

**Comment by rawtaz** [comment]
> If I'm in a virtual network, with a custom DNS setup. The threat model for me is that the communication is within the network.

If it's internal systems, it ought to be even simpler for you to secure the communication with HTTPS.

**Comment by konidev20** [comment]
> > If I'm in a virtual network, with a custom DNS setup. The threat model for me is that the communication is within the network.
> 
> If it's internal systems, it ought to be even simpler for you to secure the communication with HTTPS.

Okay.

**Pull request closed without merging**
