### PR TITLE
Add command self-update

### PR DESCRIPTION
**Pull request by fd0**
What is the purpose of this change? What does it change?
--------------------------------------------------------

It adds a command called `self-update` which downloads the latest released version of restic from GitHub and replacing the current binary with it. It does not rely on any external program (so it'll work everywhere), but still verifies the GPG signature using the embedded GPG public key.

I've long wanted to add such a thing, but worried about feature creep. So, today I took the opportunity and built something, and it turned out that it's rather easy to do. I hope that this command makes it much easier for users to upgrade restic, reducing a lot of the friction of the current (very manual) process. In addition, it provides users with a nice, clean built-in way that is a bit more secure than just using a shell script and curl: since the GPG key is included in the binary and used during verification, a potential Man-in-the-Middle is detected and the upgrade fails, assuming the initial restic binary has not been tampered with.

By default, the `self-update` command is hidden behind the `selfupdate` built tag, which is only set when restic is built using `build.go`. The reason for this is that downstream distributions will then not include the command by default, so users are encouraged to use the platform-specific distribution mechanism.

Sample run:

    $ restic version
    restic 0.9.1 compiled with go1.10.3 on linux/amd64
    
    $ restic self-update
    find latest release of restic at GitHub
    latest version is 0.9.2
    download file SHA256SUMS
    download SHA256SUMS
    download file SHA256SUMS
    download SHA256SUMS.asc
    GPG signature verification succeeded
    download restic_0.9.2_linux_amd64.bz2
    downloaded restic_0.9.2_linux_amd64.bz2
    saved 12115904 bytes in ./restic
    successfully updated restic to version 0.9.2
    
    $ restic version
    restic 0.9.2 compiled with go1.10.3 on linux/amd64

So, this PR is meant to gather some feedback on the new command. What do you think?

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

https://github.com/restic/restic/issues/1930

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by chrestomanci** [comment]
Perhaps this is the wrong place to ask, but I would like it if there was a --dry-run switch on this, so that I can add a restic self-update to my daily cron, and have it stay silent if there are no updates, or send me an email if there are some so that I ran run the update when I next login.

Alternatively, just create a restic-announce mailing list that I can subscribe to to find out when there is a new version.

**Comment by fd0** [comment]
Interesting idea, thanks. While there is no mailing list, we have a blog at https://restic.net/blog, and GitHub provides an XML/Atom feed for releases here: https://github.com/restic/restic/releases.atom

**Comment by wscott** [comment]
It is a little funny that 'restic self-update' appear to update the restic binary in the current directory. I would have expected it to figure out which restic binary I am currently executing and update that one.  (You have to look at argv[0] and PATH to figure this out.)

And if this is the expected behavior then running 'restic self-update' in a directory without a restic binary should give an error or at least print a message that a new copy of restic is being written to the current directory rather than updating the restic the user just ran.

**Comment by klemensn** [comment]
Looks like it took more than three years for someone wanting to disable?
See #4100.

**Pull request merged**
