### PR TITLE
Update vendored deps

### LINKED ISSUE #1093: Update vendored deps (especially minio-go)
Just a reminder issue to update the vendored dependencies, especially minio-go.

### PR DESCRIPTION
**Pull request by fd0**
Closes #1093

### CODE REVIEW

**Comment by tmcarr** [comment]
What vendoring tool is restic using? Is there a timeline on getting it ported to dep?

**Comment by fd0** [comment]
restic uses `gb` and `gb vendor`. Due to the different project layout used with `gb`, it may not so easy to switch to `dep`. I haven't had a look yet, is `dep` already done/stable?

**Comment by tmcarr** [comment]
It was announced at gophercon the other day that it is production ready and stable. 

Merging it into the core toolchain has yet to happen though.

**Comment by fd0** [comment]
Ah, thanks for the info. I haven't seen that announcement yet.

**Pull request merged**
