### PR TITLE
check: Remove filesize counter

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Remove file size counter in `check` and adds a comment referring to #1887.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

No, I found it while reviewing #3106 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- I have not added tests for all changes in this PR
- I have not added documentation for the changes (in the manual)
- There's no new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by MichaelEischer** [comment]
If I understand the old archiver implementation (restic before 0.9.0) correctly, then the `Size` field of a node and its chunk list might be inconsistent:

https://github.com/restic/restic/blob/272ccec7e16f74aaad771ace8a1774ccfdfe249b/internal/archiver/archiver.go#L211

**Comment by aawsome** [comment]
> If I understand the old archiver implementation (restic before 0.9.0) correctly, then the `Size` field of a node and its chunk list might be inconsistent:
> 
> [](https://github.com/restic/restic/blob/272ccec7e16f74aaad771ace8a1774ccfdfe249b/internal/archiver/archiver.go#L211)

Ok, but it might still be worth to show a warning in that case.. So what should we do?

- print a warning in that case (compared to the orphaned pack warning)?
- or remove the code that calculates the size from the contents and add a comment that this is not checked on purpose?

**Comment by MichaelEischer** [comment]
The size check was removed in #1887 after throwing errors which can't be fixed at users. And I don't see any reliable way to distinguish pre and post 0.9.0 snapshots. So it's probably best to remove the dead counter.

**Comment by aawsome** [comment]
Changed this PR such that it removes the counter and adds a comment referring to #1887.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
