### PR TITLE
Update "forget" documentation (append-only mode security considerations, add references)

### PR DESCRIPTION
**Pull request by lgommans**
As discussed in #3498.

Removing data based on a policy when the attacker had the opportunity to add data to your repository comes with some considerations. This is added to the `060_forget.rst` documentation.

That document is also updated to reflect that restic now considers the current system time while running `forget` (it changed in 0.12.1, more specifically #3416).

References to the security considerations section are added:

- In `restic forget --help`
- In the threat model (`design.rst`)
- In the (`030_*`) setup section where an append-only setup is referenced

A reference is also to be added to the `rest-server` readme's append-only paragraph (see [this commit in my fork](https://github.com/lgommans/rest-server/commit/d4c3233e92aee997b98ec947c4b4c8dec99ab3c0) for a draft).

This commit also resolves a typo (amount->number for countable noun), changes a password length recommendation into the metric that actually matters when creating passwords (entropy) since I was editing these doc files anyway, and updates the outdated copyright year in `conf.py`.

Some wording in `060_forget` (line 21..22) is changed to clarify what "forget" and "prune" do, to avoid making it sound like `forget` does not remove any data.

One open question:

- Is it possible to add links within the documentation? There are two places where I think it would be helpful to link directly to the added paragraph, but I don't see intra-documentation links elsewhere. The `:ref:` syntax is only within the same file and I'm not sure if `:doc:` is enabled or if it's the right syntax.

Checklist
---------

- [x] Build the docs to see if it all renders correctly
- [x] Resolve the two TODOs regarding adding links to the relevant page and section

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- n/a I have added tests for all code changes.
- n/a I have added documentation for relevant changes (in the manual). *[Not applicable I think, unless there is a changelog for documentation]*
- n/a There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- n/a I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by lgommans** [comment]
Created https://restic-test-for-merge-request.readthedocs.io/en/latest to check that it builds correctly. Fixed one typo, looks good to me now.

One question still for the reStructuredText experts here: is there a way to create links, e.g. to link from `design.rst` into (preferably a subsection of) `060_forget.rst`? Or would it be acceptable to just specify the filename as it is on readthedocs, i.e. link to `060_forget.html#security-considerations-in-append-only-mode`?

**Comment by lgommans** [comment]
Pinging @MichaelEischer since you were involved in the previous conversation and for some reason it seems nobody is looking at this simple documentation change.

**Comment by rawtaz** [comment]
@lgommans A few things:

- I am solely responsible for the delay in reviewing of this PR.
- I had taken the liberty to make some changes, in a commit of my own intended to be added atop yours, since I felt it was too complicated to ask for them in review comments.
- However, I accidentally messed up your branch and this closed the PR. Terribly sorry about that!

Can you possibly push your latest commit (`13502869c`) to the master branch in your restic repository on GitHub? Then you should be able to re-open this PR, and I should hopefully be able to add my commit (I'll try not to mess up this time). I can't do it myself since I no longer have access to the branch since it was closed.

Apologies for any inconvenience :/

**Comment by lgommans** [comment]
No worries!

I don't have it locally anymore (the number of locally downloaded repositories was getting out of hand), but it looks like the commits are still on GitHub if one directly references them. Afaik github will show everything I do live in this pull request so... bear with me, I'm going to figure out this works on the go :)

**Comment by lgommans** [comment]
Ah, one thing: should I squash them while I'm at it?

**Comment by rawtaz** [comment]
Thanks for your kind understanding :D

Yeah, feel totally free to squash your commits. And if you want to be even more advanced you can remove the "Update man page: restic-forget.1" commit, as those man pages are automatically generated when a new version is built for release.

If it's too messy for you to figure out, i still have your commits locally, so in worst case I can open a new PR with it (which should then still have you as the original author of the commits), or another alternative is if you can give me access to your master branch in your restic repo outside of this PR. A bit silly but then I could push to there and this PR can then be re-opened.

**Comment by lgommans** [comment]
If then it's just one push command for you when I give you access, that sounds by far the easiest. I added you as collaborator :)

**Comment by rawtaz** [comment]
Thank you. I pushed yours and my commit to your master branch, and that worked fine.

However, despite the Commit tab here in this PR saying "restic: master was force-pushed and no longer has any new commits. Pushing new commits will allow the pull request to be re-opened.", this PR still remains closed and I don't see any button to re-open it.

I tried adding another commit to the same branch, to really make sure the branch got a *new* commit, but that didn't change anything. I don't suppose you see any way to re-open this, in the interface for this PR or even in your repository's master branch view?

**Comment by lgommans** [comment]
Seems like there are no buttons available to me either. I can create a new pull request though, shall I do that instead?

**Comment by rawtaz** [comment]
Yeah, I checked with some GitHub community folks and didn't get any other suggestions there, so let's just create a new PR.

I have removed the man page commit and squashed the remaining ones by you, and pushed that and my commit to a new branch in your repository, the one you can find here: https://github.com/lgommans/restic/tree/forget-security

On that page you should be able to create a new PR :)

**Pull request closed without merging**
