### PR TITLE
Feat AWS Assume Role add duration in seconds

### PR DESCRIPTION
**Pull request by konidev20**
What does this PR change? What problem does it solve?
-----------------------------------------------------
This is w.r.t #4474  which was merged. The AWS AssumeRole endpoint provides the ability to specify the duration in seconds for the validity of the token. Refer: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

I see that it was missed in the previous linked PR. The `minio` library used does provide the ability to specify the duration in seconds under the `STSAssumeRoleOptions`.

I want the ability to change the duration in seconds for which the AssumeRole token is issued. I have some long running operation and want to keep 12 hours as the validity for the token I am using.

One thing to note here:
The `minio` library implicitly considers `DurationInSeconds` greater than 3600 seconds. I have updated the documentation as well highlighting the same.

If the environment variable is not set, it is simply ignored and the default value of 3600 seconds is implicitly accepted. 

This must be documented since, AWS AssumeRole allows you to specify durations between 900 and 43200 seconds. Since, `minio` allows only values above 3600 seconds we need to add it.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Related to #4474

Checklist
---------
- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
I'm not entirely sure I get the point of this PR. As far as I can tell, minio should be able to request a new token once the old one has expired.

**Comment by konidev20** [comment]
Yes. Tweaking the duration for the validity of the STS token issued through the AssumeRole API is something I desire to change. 

Example instead of renewing it every 1 hour, I want to be able to specify it to renew every 3 hours. 

It's just another configuration value to be added. It would be helpful for me.

**Comment by MichaelEischer** [comment]
> Example instead of renewing it every 1 hour, I want to be able to specify it to renew every 3 hours.

But what is the underlying reason for changing `DurationInSeconds`? So far you've only explained what the PR does, but not why. Which problem does the PR solve? 

> This doesn't affect the functionality, want this as a possible configuration option.

A configuration option that just exists in order to exist, doesn't make sense. Either there is a reason why the option is necessary or we shouldn't add the option.

**Comment by konidev20** [comment]
One of the use cases I am looking for is the ability to skew the requests for STS token renewal when I have lots of parallel backup jobs running to S3. I don't want 100 pods to make the same request for token renewal which can overload my STS endpoint. 

Another one is to reduce the number of requests to the STS API. If I know a backup/restore job will be taking 10+ hours I might as well get a token for 12 hours (the max limit of the AssumeRole endpoint).

**Comment by rawtaz** [comment]
@konidev20 Can you please clarify further - do you have an actual problem right now with your 100 pods, and if so what is it in concrete terms? And in what way would 100 pods renewing their tokens overload the STS service? After all, the default value has been set by upstream to one hour, so I'd expect them to be quite prepared for renewals to happen as frequently as one hour.

**Comment by konidev20** [comment]
Nevermind, found another way. https://repost.aws/knowledge-center/iam-sts-throttling-error

**Pull request closed without merging**
