### PR TITLE
Onedrive backend

### PR DESCRIPTION
**Pull request by chbmuc**
This is a first draft of a new storage backend for Microsoft Onedrive. Some things are still on my TODO-List, but it is already working:
- [x] Folder creation on first access
- [x] List() is limited to 200 items (could be increased easily, but I think support for paging would be better)

Apart from that, review comments or other feedback would be appreciated.

Onedrive uses OAUTH for authentication. At the moment you need to provide a config file with the token credentials, Client-ID and Client-Secret. I think it would be best, to provide a helper application with a local webserver to ease the generation of the token. 

Client-ID and Client-Secret can be obtained in the Microsoft Developer Center. I've seen that rclone is providing them in the source code,  but I'm unsure if this is admissible.

### CODE REVIEW

**Comment by fd0** [comment]
Hey, thanks a lot for your contribution! Is there a test service that we can use during CI tests for this backend? What's the difference between `Client-ID`, `Client-Secret` and the OAuth token?

**Comment by chbmuc** [comment]
- The problem with CI tests is, that I don't know of any onedrive service except the one from Microsoft. To upload files, we need an account. Free accounts are available, but we have to keep the credentials secret, to avoid abuse.
- Every "onedrive client application" needs to be registered with Microsoft. You can do this in the developer center, but you have to agree to the Terms of Service. Upon registration, you get a Client-ID and a Client-Secret for you application (see also: https://auth0.com/docs/connections/social/microsoft-account).
- Access to a users onedrive account is authenticated with a token. For permanent access we need a "refresh token" (see https://dev.onedrive.com/auth/msa_oauth.htm - chapter "Code flow"). I'll provide a helper application for this as an example.
- Reading the configuration from environment variables should be possible. I just thought, that generating a file would improve usability.

**Comment by chbmuc** [comment]
- Folder creation is now working
- Paging for long List() is implemented

**Comment by fd0** [comment]
May I suggest that you install the `check-fmt` pre-commit hook as described here https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches

**Comment by fd0** [comment]
So, in order to make the current CI tests pass, you'll need to reformat the following files with `gofmt`:
```
not formatted with `gofmt`:
src/restic/cmd/restic/global.go
src/restic/location/location.go
```

**Comment by fd0** [comment]
I've asked the rclone people about their decision to just include the Client-Secret in the source code: https://github.com/ncw/rclone/issues/372

**Comment by chbmuc** [comment]
I've fixed the formatting and did a rebase

**Comment by fd0** [comment]
Just a quick heads-up: I haven't forgotten, I just don't have any time at the moment.

**Comment by dbadrian** [comment]
Has there been any progress on this lately? I am very interested in this feature.

I wish I could help (myself) and help finish this, but I have no time to learn Go first XD. I am happy to help in testing, if there is any need.

**Comment by fd0** [comment]
I'm sorry to acknowledge that there hasn't been any progress. The blocker here is that we (as a project) need to decide how we handle backends for third-party services, especially in terms of testing. This also applies to the request for an Amazon OneDrive backend, you can find the discussion here: https://github.com/restic/restic/issues/212#issuecomment-230400007

**Comment by gngeorgiev** [comment]
Hey guys, I am not sure why you have problems with the CI, maybe I am missing something. You can have a free account right? Then, in travis you can encrypt the credentials or provide them with environment variables https://docs.travis-ci.com/user/environment-variables.

**Comment by fd0** [comment]
I'm going to close this PR for now, since the questions outlined #212 need to be answered before I'll merge any code. We can always open the PR again (or start a new one).

**Pull request closed without merging**
