### PR TITLE
travis: update go versions

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by zcalusic** [comment]
I tried this already in #1012, but unfortunately versions of Go Travis uses in that case are not the latest one. :(

**Comment by dvrkps** [comment]
Please look again, i think that travis use correct versions now.

**Comment by zcalusic** [comment]
Yeah, judged by my other project, the versions are now up to date. We can only hope it stays that way, otherwise 1.x.y notation doesn't make much sense.

**Review by fd0 — APPROVED** [review]
Thanks!

**Pull request merged**
