### PR TITLE
Remove unused function

### PR DESCRIPTION
**Pull request by rubiojr**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Removes dead code.

I found this while working on some code examples for https://github.com/rubiojr/rapi, and realized it's not being used elsewhere, It'd need to be added to the [MasterIndex](https://github.com/restic/restic/blob/bb4b3481a655237f1b308f799d31c387c21b3691/internal/restic/repository.go#L61) interface first to be useful.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

No.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by rubiojr** [comment]
I can see how being able to iterate over all the indices and listing the packed blobs in a given pack file could be useful. Should this be added to the `MasterIndex` interface instead?

**Comment by rubiojr** [comment]
Originally added in https://github.com/restic/restic/pull/252.

**Comment by greatroar** [comment]
LGTM. If it's unused, it makes no sense to put it on the interface. That just makes it harder to tell that it's unused.

I can't see in the git log where this method was ever used. It might have been there only to satisfy an interface that MasterIndex had to implement for structural reasons.

**Review by greatroar — APPROVED** [review]

**Comment by rubiojr** [comment]
> I can't see in the git log where this method was ever used. It might have been there only to satisfy an interface that MasterIndex had to implement for structural reasons.

It was used in the PR I linked, https://github.com/restic/restic/pull/252/files#diff-c14c8bb41c84cbf71a6c3920a39185cec018509b676b969b3476a9107260efefR111 in particular. Some refactoring go rid of that code I guess.

**Comment by aawsome** [comment]
In #2842, I added a function that yields all blobs grouped by pack. This is what is acually needed for rebuilding the index. The `ListPack` is not only unused within `MasterIndex`, also the implementation in `Index` is quite inefficient (loops over all entries to filter out the ones in the given pack).

**Comment by greatroar** [comment]
This PR cherry-picks cleanly onto #2842; tests pass too.

**Comment by rubiojr** [comment]
@aawsome please feel free to cherry pick this into your PR, if y'all want it removed and makes things easier for you.

**Comment by aawsome** [comment]
> @aawsome please feel free to cherry pick this into your PR, if y'all want it removed and makes things easier for you.

We can let the topics stay independent. I just wanted to mention that the `ListPack` may be totally removed, this would fit in this PR.

As `ListPack` IMO is also not suitable for my PR (for performance reasons), I made an extra function which is included in my PR.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
