### PR TITLE
Update github.com/kurin/blazer

### PR DESCRIPTION
**Pull request by fd0**
Reduces cost-intensive list_files API calls.

### CODE REVIEW

**Comment by fd0** [comment]
@kurin it seems something is broken here:
```
--- FAIL: TestBackendB2 (170.83s)
    --- FAIL: TestBackendB2/TestLoad (18.35s)
    	tests.go:26: rand initialized with seed 1496737493190213538
    	tests.go:140: saved 15119229 bytes as <data/0d1e0eb4f4>
    	tests.go:204: Load, l 14780398, o 200043, len(d) 14780398, getlen 14780398
    	tests.go:205: Load(14780398, 200043) wrong number of bytes read: want 14780398, got 14919186
FAIL
```

**Comment by fd0** [comment]
Let me know if you need instructions on running the CI tests yourself. It boils down to setting the environment variables: https://github.com/restic/restic/blob/update-blazer/src/restic/backend/b2/b2_test.go#L23-L30

**Comment by kurin** [comment]
I'll take a look.

**Comment by kurin** [comment]
I'm able to reproduce this locally.

**Comment by kurin** [comment]
I can confirm that this is a bug in blazer.

**Comment by kurin** [comment]
I've pushed the test and the fix to blazer/master and have confirmed that it fixes the issue after a gb vendor update.

**Comment by fd0** [comment]
Updated again, waiting for the CI tests.

**Comment by fd0** [comment]
Looks good, thanks!

**Pull request merged**
