### PR TITLE
Load the index and search subtree

### PR DESCRIPTION
**Pull request by bchapuis**
The index was not loaded and the recursive tree walk was not working.

### CODE REVIEW

**Comment by bchapuis** [comment]
Fix for #289.

**Comment by fw42** [comment]
Thanks for the fix! Could you add a regression test?

**Comment by bchapuis** [comment]
@fw42 Thank your for your feedback. I improved the tests for the find method. Can we close this issue?

**Comment by fd0** [comment]
Thanks for taking care of this, I'll have a look and merge this in the evening.

**Pull request merged**
