### PR TITLE
Building restic + rclone as a library

### PR DESCRIPTION
**Pull request by jdeng**
What is the purpose of this change? What does it change?
--------------------------------------------------------
Building restic + rclone as a library will allow developers to build applications to access files stored in the Cloud via restic + rclone natively on multiple platforms including mobile.

There are 3 parts in the change: a new backend `inproc` to embed rclone as an http.RoundTripper via the rest backend which is only additional, moving 3 functions in `cmd/restic/global.go` to `cmd/global/global.go` so that they can be reused, and exposing some types and functions in `cmd/global/api.go`.

This requires some small change in rclone. See https://github.com/rclone/rclone/pull/4460/files
 
A code example can be found here: https://gist.github.com/jdeng/81f64666c61d143d5d3d9fb88f1f64dd

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
No. The code change is relatively small (except for global.go reorganization) and mostly glue code, so I hope this can be upstreamed. 

Checklist
---------

- [ ] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by rawtaz** [comment]
Hmm, restic as a library has already been discussed in https://github.com/restic/restic/issues/833, https://github.com/restic/restic/issues/1089 and one-way in https://github.com/restic/restic/issues/2804. Not sure anything changed on that part.

**Comment by jdeng** [comment]
I think previous discussion was aiming at a more elegant and thorough change of the code structure, while this is more like a workaround without making significant changes to the codebase. The downside is that there is no guarantee on the API stability which is still much better than no API at all, IMO.

Another bonus point is that this also allows embedding of rclone which greatly expands its usability.

**Comment by rawtaz** [comment]
Embedding rclone has been discussed a couple of times as well and it's not been encouraged I'm afraid :/

**Comment by jdeng** [comment]
I think the point is to provide options to developers. I don't expect embedding rclone is a popular use case, but having all pieces in one binary across multiple platforms including mobile along with golang's tooling is quite appealing at least to some developers IMO. For example, I can build an app that pulls data from my personal restic data on Google Drive. This way I can avoid my data being scanned by the cloud providers.

**Comment by greatroar** [comment]
@jdeng, your use case can be satisfied by a fork as well as an API client. The API option just shifts the maintenance burden to the central project.

**Comment by jdeng** [comment]
To be clear, the API change is actually just one file with some alias of types and functions. It is probably less than .1% of total lines of code in restic. The problem is that the current code structure (everything is under internal) has prohibited usage of embedding restic as a library and this is a workaround without changing it. It acts like a header file in C/C++.

This is not elegant but it will make the certain developers' life much easier.  Instead of maintaining a local copy of fork and/or maintaining a separate binary, the same functionality can be achieved with just one single import.

```
const (
	DataBlob = restic.DataBlob
	TreeBlob = restic.TreeBlob
)

// types
type Repository = restic.Repository
type Node = restic.Node
type Tree = restic.Tree
type TagList = restic.TagList
type Cache = cache.Cache
type Options = options.Options

// functions
var FindLatestSnapshot = restic.FindLatestSnapshot
var LoadSnapshot = restic.LoadSnapshot
var NewBlobBuffer = restic.NewBlobBuffer
var CiphertextLength = restic.CiphertextLength
var NewRepository = repository.New
var NewCache = cache.New
```

**Comment by fd0** [comment]
This PR does two very different things:
 1. Add a new API to call restic from within another Go project
 2. Embed rclone as a new backend

Both need to be discussed separately. I've outline my thoughts for the first point a few times already: We (as a project) struggle already with maintaining one interface (the restic binary with the JSON API), even more since the last time we discussed this feature request. Adding another API (which even exposes internal things that we cannot change afterwards without breaking the API contract) will add to this burden. Therefore, my initial response would be to reject this feature request, at least for now.

Embedding rclone is an interesting thought. On the upside, people don't need to install and maintain rclone. On the downside, this also adds to our maintenance burden. Restic would inherit all dependencies from rclone, we would need to closely follow rclone's release cycle and we would be force do to a release whenever there's a security issue in rclone. I'm undecided if it's a good idea for us (as a project). Let's open an issue for this feature request and discuss it there before implementing it.

I'm closing this PR for now. Please feel free to add further comments, thanks!

**Pull request closed without merging**
