### PR TITLE
forget: Add reason to keep snapshots

### LINKED ISSUE #1235: forget: display reason why a snapshot is kept
When running restic --forget, display the reason why each snapshot is kept, f.e. for `--keep-daily 2`

## Expected behavior

```
23 snapshots:                                                                                                                                                         
ID        Date                 Host        Tags    Reason      Directory 
------------------------------------------------------------------------------
12345678  2017-09-13 08:58:46  host                daily 1/2  ┌── /etc
abcdef01  2017-09-12 09:04:00  host                daily 2/2  ┌── /etc
```

## Actual behavior

```
23 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
12345678  2017-09-13 08:58:46  host                ┌── /etc
abcdef01  2017-09-12 09:04:00  host                ┌── /etc
```

### PR DESCRIPTION
**Pull request by fd0**
**UPDATE** this change is included in restic 0.9.3 and you don't need to do anything, restic prints the reason automatically.

What is the purpose of this change? What does it change?
--------------------------------------------------------

~~The `--explain` option instructs restic to print the reason for keeping each snapshot, sample:~~

```
$ ./restic forget --explain --dry-run --keep-daily 7 --keep-weekly 4 --keep-monthly 1

repository 559c5ffa opened successfully, password is correct
Applying Policy: keep the last 7 daily, 4 weekly, 1 monthly snapshots
snapshots for (host [mopped], paths [/home/fd0/work/restic]):
keep 9 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
b06c68f1  2018-06-17 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot
                    weekly snapshot
                    monthly snapshot

93636576  2018-06-24 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot
                    weekly snapshot

948e8801  2018-06-26 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot

058e4f60  2018-06-27 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot

13023ad3  2018-06-28 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot

b0870185  2018-06-29 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot

7c333b49  2018-06-30 19:00:00  mopped                  /home/fd0/work/restic
                    daily snapshot

6d965b57  2018-07-01 19:00:00  mopped                  /home/fd0/work/restic
                    weekly snapshot

f5dc9c02  2018-07-02 19:00:00  mopped                  /home/fd0/work/restic
                    weekly snapshot
----------------------------------------------------------------------
9 snapshots
remove 2 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
8f40d1f8  2018-06-10 19:00:00  mopped                  /home/fd0/work/restic
376c64d4  2018-06-25 19:00:00  mopped                  /home/fd0/work/restic
----------------------------------------------------------------------
2 snapshots
```

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

https://forum.restic.net/t/clarification-on-rotation-retention-of-backup/758/12

Closes #1235

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
I'm unhappy with the user interface. Thoughts?

**Comment by bjoe2k4** [comment]
Maybe one of the following:
```
$ ./restic forget --explain --dry-run --keep-daily 7 --keep-weekly 4 --keep-monthly 1

repository 559c5ffa opened successfully, password is correct
Applying Policy: keep the last 7 daily, 4 weekly, 1 monthly snapshots
snapshots for (host [mopped], paths [/home/fd0/work/restic]):
keep 9 snapshots:
ID        Date                 Host          Policy                      Tags         Directory
-----------------------------------------------------------------------------------------------------------
b06c68f1  2018-06-17 19:00:00  mopped       daily, weekly, monthly                    /home/fd0/work/restic
93636576  2018-06-24 19:00:00  mopped       daily, weekly                             /home/fd0/work/restic
948e8801  2018-06-26 19:00:00  mopped       daily                                     /home/fd0/work/restic
058e4f60  2018-06-27 19:00:00  mopped       daily                                     /home/fd0/work/restic
13023ad3  2018-06-28 19:00:00  mopped       daily                                     /home/fd0/work/restic
b0870185  2018-06-29 19:00:00  mopped       daily                                     /home/fd0/work/restic
7c333b49  2018-06-30 19:00:00  mopped       daily                                     /home/fd0/work/restic
6d965b57  2018-07-01 19:00:00  mopped       weekly                                    /home/fd0/work/restic
f5dc9c02  2018-07-02 19:00:00  mopped       weekly                                    /home/fd0/work/restic
-----------------------------------------------------------------------------------------------------------
9 snapshots
remove 2 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
8f40d1f8  2018-06-10 19:00:00  mopped                  /home/fd0/work/restic
376c64d4  2018-06-25 19:00:00  mopped                  /home/fd0/work/restic
----------------------------------------------------------------------
2 snapshots
```
or
```
$ ./restic forget --explain --dry-run --keep-daily 7 --keep-weekly 4 --keep-monthly 1

repository 559c5ffa opened successfully, password is correct
Applying Policy: keep the last 7 daily, 4 weekly, 1 monthly snapshots
snapshots for (host [mopped], paths [/home/fd0/work/restic]):
keep 9 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
b06c68f1  2018-06-17 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily, weekly, monthly
93636576  2018-06-24 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily, weekly
948e8801  2018-06-26 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily
058e4f60  2018-06-27 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily
13023ad3  2018-06-28 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily
b0870185  2018-06-29 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily
7c333b49  2018-06-30 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: daily
6d965b57  2018-07-01 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: weekly
f5dc9c02  2018-07-02 19:00:00  mopped                  /home/fd0/work/restic
└── Policy: weekly
----------------------------------------------------------------------
9 snapshots
remove 2 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
8f40d1f8  2018-06-10 19:00:00  mopped                  /home/fd0/work/restic
376c64d4  2018-06-25 19:00:00  mopped                  /home/fd0/work/restic
----------------------------------------------------------------------
2 snapshots
```

**Comment by fd0** [comment]
I went yak-shaving today and reimplemented the table generation we use. Now it supports (automatic) variable widths and optional columns, and it uses `text/template`! I'll push a few commits later.

I've followed @bjoe2k4's first idea, to add a column based on whether or not `--explain` has been specified.

**Comment by fd0** [comment]
This is how it looks now:
```
$ ./restic forget --explain --dry-run --keep-daily 7 --keep-weekly 4 --keep-monthly 1
repository 641c242b opened successfully, password is correct
Applying Policy: keep the last 7 daily, 4 weekly, 1 monthly snapshots
snapshots for (host [mopped], paths [/home/fd0/work/restic]):
keep 9 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
----------------------------------------------------------------------------------------------
61644c0d  2018-08-05 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
                                                       weekly snapshot
                                                       monthly snapshot
f9cbc85e  2018-08-12 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
7392a746  2018-08-13 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
384fb740  2018-08-14 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
6b83fc37  2018-08-15 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
877c49cf  2018-08-16 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
bb2c906b  2018-08-17 19:00:00  mopped                  daily snapshot    /home/fd0/work/restic
f74b46db  2018-08-18 19:00:00  mopped                  weekly snapshot   /home/fd0/work/restic
94800e3a  2018-08-19 19:00:00  mopped                  weekly snapshot   /home/fd0/work/restic
----------------------------------------------------------------------------------------------
9 snapshots
remove 10 snapshots:
ID        Time                 Host        Tags        Paths
----------------------------------------------------------------------------
54fe3c26  2018-08-01 19:00:00  mopped                  /home/fd0/work/restic
8129b031  2018-08-02 19:00:00  mopped                  /home/fd0/work/restic
19b1b995  2018-08-03 19:00:00  mopped                  /home/fd0/work/restic
8ee543e0  2018-08-04 19:00:00  mopped                  /home/fd0/work/restic
71cc800d  2018-08-06 19:00:00  mopped                  /home/fd0/work/restic
f4cad99f  2018-08-07 19:00:00  mopped                  /home/fd0/work/restic
3145ece4  2018-08-08 19:00:00  mopped                  /home/fd0/work/restic
ddc9f778  2018-08-09 19:00:00  mopped                  /home/fd0/work/restic
d9de2f5b  2018-08-10 19:00:00  mopped                  /home/fd0/work/restic
2f25e5a0  2018-08-11 19:00:00  mopped                  /home/fd0/work/restic
----------------------------------------------------------------------------
10 snapshots
```

**Comment by fd0** [comment]
@rawtaz convinced me that it's a good idea to always display the reason a snapshot was kept, and only hide it when `--compact` is passed as an option.

**Comment by chrestomanci** [comment]
The release notes for 0.9.3 say that this has been included in that release, but I can't get the feature to work:

    # restic version 
    restic 0.9.3 compiled with go1.11.1 on linux/arm
    # restic forget --explain  --dry-run --keep-daily 8 --keep-weekly 12 --keep-monthly 24
    unknown flag: --explain

**Comment by fd0** [comment]
Ah, yeah, sorry, the switch has been removed. I'll clarify at the top :)

**Pull request merged**
