### PR TITLE
Enable xattr support, on NetBSD 10+

### PR DESCRIPTION
**Pull request by vmlemon**
What does this PR change? What problem does it solve?
-----------------------------------------------------

This change enables support for extended attributes, on NetBSD.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

This implements the desire, in https://github.com/restic/restic/issues/5174, to use the existing FreeBSD-compatible xattr API, on NetBSD, and has been successfully tested, on NetBSD 10/ARM64, with Go 1.22.7.

Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by rawtaz** [comment]
@vmlemon Can you check the `internal/fs/node_xattr*_test.go` files as well, I'm suspecting those tests should run for netbsd as well.

**Comment by rawtaz** [comment]
Thanks! I'm curious, did you verify that both backing this file (having xattrs) up _and_ restoring it works fine with the changes in this PR?

**Comment by vmlemon** [comment]
> Thanks! I'm curious, did you verify that both backing this file (having xattrs) up _and_ restoring it works fine with the changes in this PR? I only saw that you tried backing it up in the issue.

It seemed to work fine, with later resting of restoration, and I could view the xattr, via FUSE, on MacOS/Linux, but I haven

**Comment by vmlemon** [comment]
Oops, I'm unsure of how I accidentally closed it, but reopening this, for now...

**Comment by rawtaz** [comment]
Sounds good then. We do need a changelog entry though, can you add a file based on https://github.com/restic/restic/blob/master/changelog/TEMPLATE that sums it up? It will eventually end up in the changelog for the release.

**Comment by vmlemon** [comment]
> Sounds good then. We do need a changelog entry though, can you add a file based on https://github.com/restic/restic/blob/master/changelog/TEMPLATE that sums it up? It will eventually end up in the changelog for the release.

Will do.

Apologies for it being a screenshot, since I don't have SSH access, to the VM configured, but it looks like roundtripping attributes through the ```restore``` option works, just fine:
image

**Comment by rawtaz** [comment]
Thank you very much for the elaborate information, very helpful! Merry Christmas!

**Review by rawtaz — APPROVED** [review]

**Comment by vmlemon** [comment]
> Thank you very much for the elaborate information, very helpful! Merry Christmas!

Thanks! Merry Christmas, to you, too!

**Comment by vmlemon** [comment]
> Thank you very much for the elaborate information, very helpful! Merry Christmas!

Thanks! Merry Christmas, to you, too!

**Pull request merged**
