### PR TITLE
Fix statistics in prune for duplicates

### LINKED ISSUE #3110: Prune stats calculation bug
Output of `restic version`
--------------------------
restic_v0.11.0-g5f3b802e

How did you run restic exactly?
-------------------------------
`restic_v0.11.0-g5f3b802e prune > prune.log`

Actual behavior
---------------
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```
Note the `16777215.894 TiB`.

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Fixes statistics calculation in `prune` if there are duplicates present in the repo.

Output of `restic prune -n -v` without this bug fix when using the repo in `cmd/restic/testdata/repo-duplicates.tar.gz`:
```
used:                 4 blobs / 1.718 KiB
duplicates:           2 blobs / 148 B
unused:               4 blobs / 1.726 KiB
total:               10 blobs / 3.588 KiB
unused size: 48.09% of total size

to repack:            2 blobs / 220 B
this removes          2 blobs / 148 B
to delete:            4 blobs / 1.726 KiB
total prune:          6 blobs / 1.870 KiB
remaining:            4 blobs / 1.718 KiB
unused size after prune: 16777216.000 TiB (100.00% of remaining size)
```

Output with this bug fix:
```
used:                 5 blobs / 1.790 KiB
duplicates:           1 blobs / 74 B
unused:               4 blobs / 1.726 KiB
total:               10 blobs / 3.588 KiB
unused size: 50.11% of total size

to repack:            2 blobs / 220 B
this removes          1 blobs / 74 B
to delete:            4 blobs / 1.726 KiB
total prune:          5 blobs / 1.798 KiB
remaining:            5 blobs / 1.790 KiB
unused size after prune: 0 B (0.00% of remaining size)
```

Note that this fix only solves the statistics problem, if all duplicates are marked for repacking.
If not all duplicates are marked for repacking, we lack the information what duplicates still exist after pruning.

The situation that not all duplicates are marked for repacking can occur when using the `max-repack-size` option.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

closes #3110 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- I have not added tests for all changes in this PR
- I have not added documentation for the changes (in the manual)
- There's no new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for the fast fix!

I think it'd be a great idea to extract all the calculation logic into a separate function/struct, so we can add proper tests for it (not necessarily in this PR). What do you think?

**Comment by aawsome** [comment]
> I think it'd be a great idea to extract all the calculation logic into a separate function/struct, so we can add proper tests for it (not necessarily in this PR). What do you think?

Fully agree! In fact there are two things we should test:

- Assure that prune basically does the job, i.e. removes data *and* does not damage the repository. This is mainly about assuring that the repacking, deletion and index rebuilding is done correctly. But also to ensure that the algorithm doesn't choose a pack for deletion which is actually still needed.

These tests are IMHO pretty well implemented.

- The main pruning algorithm which basically returns the list of packs to delete and to repack. As pointed out, here only the packs-to-delete part is mission critical, the decision which packs to repack is basically "only" performance-critical. 

Here tests are missing...

**Comment by aawsome** [comment]
@fd0: Forgot to mention: Yes I think we should postpone this testing issue to a follow-up PR.

**Review by fd0 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
