### PR TITLE
Progress UI for the new optimized restore implementation

### LINKED ISSUE #426: Progress bar for restore
Backup have nice progress bar, but restore is not.
In real life I expect to do restore not that often (now I play with restic and with restore a bit too often).
But it will be useful to have progress for restore too (for big repo I would like to see some estimation about how much time it will take).

### PR DESCRIPTION
**Pull request by ifedorenko**
What is the purpose of this change? What does it change?
--------------------------------------------------------

This PR implements periodic status report for the new optimized multithreaded `restore` command implementation. It also introduces new command-agnostic `ui.ProgressUI` interface, which is then used by `restore`, `backup` and `check` long-running commands.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

See #1719

Closes #426

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by mholt** [comment]
Ooo this looks really nice. Do you think the ProgressUI interface would help a lot with #1944?

And would you be open to having `--json` flag support for this, similar to #1944? I could potentially contribute it, just need some guidance as to how.

**Comment by ifedorenko** [comment]
My idea here is to decouple what progress is being reported from how the report is being rendered to the user. So yes, `--json` does look like a good usecase. There is some rudimentary support for different rendering in `TermstatusProgressUI.displayProgress` already (i.e. ansi-vs-dumb terminal stuff), but I think `--json` will require something more elaborate. I'll need to think about it before I can suggest anything more specific.

**Comment by fd0** [comment]
I've taken the liberty of rebasing this branch on master, thereby removing the commits that are already in master :)

**Comment by fd0** [comment]
I just gave this a try, the UI looks nice.

**Comment by ifedorenko** [comment]
To be clear, this is still work in progress and I don't like the way 
command progress 'phase' api is currently defined. I'll try to finalize the 
api and apply it to at least one other command in the next few days. Of 
course, let me know if you have any ideas or other feedback on what I have 
so far.

--
Regards,
Igor

**Comment by fd0** [comment]
Understood, I'll have a look!

**Comment by ifedorenko** [comment]
as for json, I'd like to suggest the following. 

each command will be modeled as sequence of phases ("load index", "list all files to restore", "restore file content", and so on). 

every few seconds during phase execution emit json message with the following attributes:
* `title` of the phase
* `percent` of the phase completion, if known
* `eta` of the phase completion, if known
* `message` description of the phase process, for example for restore file content download it will be something like "1 out of 1024 MiB in 1 out 123345 files"

at the end of each command phase emit summary json message with the following attributes
* `start`/`end` timestamps
* `message` that says how many files/bytes were "processed" during the phase and processing speed. to continue with restore file content download example, it will be something like "downloaded  1024 MiB in 123345 files at 1000Gbps".

@mholt what do you think?

**Comment by mholt** [comment]
@ifedorenko That sounds perfect -- and, preferably, if each message is encoded using a different struct type, it would be nice if there was a field to indicate the type of message or structure so we can expect certain decoded fields (`struct_type` is what I used in #1962 or `message_type` in #1944 -- hmm, maybe I should have standardized on one name). If that makes sense. Maybe there's a better way to do it, I dunno though.

Basically, if each kind of message could have a different structure, it'd be nice as a consumer of the JSON output to be able to decode all the messages into a structure that can fit all the possible values, or to know which kind of message it is so we can decode properly.

Also, the more details (like processing rate, number of files, etc) that you can put into separate fields as plain numbers, the better. (A message is fine, too, as long as it's not the only way the information is given.)

Anyway, sounds great overall :+1:

**Comment by ifedorenko** [comment]
I was hoping to avoid fine-grained metrics, like number of bytes downloaded or files written ;-). No big deal, will find a way to have those too.

@fd0 do you have a preferred text template library I can use here, like [mustache for Go](https://github.com/cbroglie/mustache) for example? Not sure I'll need this yet, but one of the ideas I consider is to have a map of fine-grained metrics, which are then used to render user-visible messages via a template. Probably an overkill here, but it feels like the right way to provide uniform way to support json and user-facing UI.

**Comment by fd0** [comment]
I'd prefer [`text/template`](https://godoc.org/text/template) from the standard library.

@mholt the json code is not released yet, we can change the name of the type field :)

**Comment by ifedorenko** [comment]
@mholt somebody ;-) will have to change `TermstatusProgressUI` to honour `--json`. `displayProgress` and `diplaySummary` are the two methods will need to change for sure, and maybe `Set` too.

**Comment by ifedorenko** [comment]
@fd0 do you mind I move all backup-specific progress reporting to `archiver` package, similarly to how I already did/prototyped for restore and check? And if you have time for some feedback on overall idea and implementation of ProgressUI API, I'll certainly appreciate that too.

**Comment by fd0** [comment]
@ifedorenko I need to find time to look a this, I didn't look at it yet. Sorry for the delay!

**Comment by mholt** [comment]
@ifedorenko Unfortunately (or fortunately?) I haven't made time to implement the json renderer yet -- I'm getting ready to launch (next week!) the version 1.0 of the application that will use it. After that, I can probably turn my attention to doing it. So if you want to make any (major?) changes, go ahead -- won't hurt anything I've worked on.

**Comment by ifedorenko** [comment]
@fd0 I implemented all changes I planned to do here, please have a look. I'd like to groom git history before (and _if_) this is merged, but otherwise I think this is "done". Let me know if you want me to make any changes or if you disagree with the proposed approach in general.

**Comment by fd0** [comment]
Will do, thanks!

**Comment by bbigras** [comment]
Any progress on this?

**Comment by ifedorenko** [comment]
I have no immediate plans to continue work on this PR. The approach I took here was too ambitious and the change is too big to be worth the trouble. I may provide smaller change to implement restorer progress after #2195 is merged, but can't promise at this point. Really depends how long it takes for #2195 to get reviewed and how much time I will be able to dedicate to restic after that.

**Pull request closed without merging**
