### PR TITLE
Remove regular status printing for non terminals

### PR DESCRIPTION
**Pull request by fd0**

### CODE REVIEW

**Comment by dirk777** [comment]
Is there any chance to activate the progress report for windows when running in background?

**Comment by fd0** [comment]
Nop, nothing built in. As far as I know, Windows doesn't have signals (in the Unix sense). Sorry.

**Comment by xcezzz** [comment]
I believe restic needs an actual logging facility that is not just a transient output to stdout or stderr and can be referenced without needing to just redirect these or turn on debug. 

Making this structured we can include information about the files, the progress and other information if necessary that can be read/parsed later without having to invoke restic (file, influxdb, etc).

**Comment by dirk777** [comment]
I highly appreciate this approach. This would improve restic' usability and makes it more developer friendly

**Pull request merged**
