### PR TITLE
Use path.Join to create the s3 object name within the bucket.

### PR DESCRIPTION
**Pull request by ckemper67**
path.Join already automatically skips empty path segments when
joining, so this simplifies the s3Path code.

### CODE REVIEW

**Comment by fd0** [comment]
Looks good, simplifications are always desirable! Why did you rename the variable from `path` to `objName` in the code?

**Comment by ckemper67** [comment]
I needed to do the rename because Join is imported from path and the
identifiers collided.

**Comment by fd0** [comment]
Oh, okay, that's a very good reason. Thanks for your contribution!

**Comment by fd0** [comment]
Ah, for the record: it would've also worked without the rename, but I think this way it's clearer. Thanks!

**Pull request merged**
