### PR TITLE
Extract chunker

### PR DESCRIPTION
**Pull request by fw42**
Extract chunker into it's own package. Mostly just moving things around and replacing "restic/restic/chunker" with "restic/chunker".

What's left to do:
- [x] Create a new GitHub repository (I don't have permission to do that)
- [x] Copy the contents of "Godeps/_workspace/src/github.com/restic/chunker/" to that new repo
- [x] Add the new package with SHA to the "Godeps.json" file
- [x] Add a README.md to the new repo, explaining what the chunker is and how to use it in applications other than restic

@fd0

### CODE REVIEW

**Comment by fw42** [comment]
(tests are gonna fail because the repo doesn't exist yet)

**Comment by fd0** [comment]
:+1:

I've just created the repository https://github.com/restic/chunker for the chunker. When you split out the chunker, please retain the history, e.g. by following http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475

Other things:
 * Add the license (BSD 2-clause)

**Comment by fw42** [comment]
Travis is happy. I think this can be merged now. @fd0? objections?

**Comment by fd0** [comment]
LGTM

**Comment by fd0** [comment]
I've added #224 to track adding documentation to the chunker.

**Pull request merged**
