### PR TITLE
pipe: propagate errors properly

### LINKED ISSUE #338: Handle "access denied" errors correctly
When I try to backup my Documents folder, I get the following output:

    C:\Git\restic>.\restic -r D:\Backups\restic backup "C:\Users\Jan Bader\Documents"
    enter password for repository:
    scan [C:\Users\Jan Bader\Documents]
    error for C:\Users\Jan Bader\Documents\Eigene Bilder: open C:\Users\Jan Bader\Documents\Eigene Bilder: Zugriff verweigert
    error for C:\Users\Jan Bader\Documents\Eigene Musik: open C:\Users\Jan Bader\Documents\Eigene Musik: Zugriff verweigert
    error for C:\Users\Jan Bader\Documents\Eigene Videos: open C:\Users\Jan Bader\Documents\Eigene Videos: Zugriff verweigert
    scanned 205 directories, 6787 files in 0:00 MiB
    [0:00] 2.36%  0B/s  5.929 MiB / 251.367 MiB  33 / 6992 items  0 errors  ETA 0:00
    duration: 0:00, 546.02MiB/s
    snapshot 92730b9b saved

Although a snapshot is created, no data is backed up:

    C:\Git\restic>.\restic -r D:\Backups\restic cat snapshot 92730b9b
    enter password for repository:
    {
      "time": "2015-11-03T19:02:30.594317+01:00",
      "tree": "ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8",
      "paths": [
        "C:\\Users\\Jan Bader\\Documents"
      ],
      "hostname": "...",
      "username": "..."
    }
    
    C:\Git\restic>.\restic -r D:\Backups\restic cat tree ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8
    enter password for repository:
    {
      "nodes": []
    }

### PR DESCRIPTION
**Pull request by fd0**
This PR reworks pipe error propagation.

Fixes #338

### CODE REVIEW

**Comment by fd0** [comment]
@JaCoB1123 It would be great if you could test the code in this PR :)

**Comment by JaCoB1123** [comment]
Thanks, Backup now works flawlessly.
On Restore I get the following errors though:

    error for C:\Backup\documents\Documents\Eigene Bilder: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\Eigene Dateien: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\Eigene Musik: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\Eigene Videos: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\My Games\Borderlands 2\WillowGame\SaveData: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\My Games\Fallout3\Saves: create node: filetype "" not implemented!

The last two folders are Symlinks as well and have default permissions.

**Comment by fd0** [comment]
> Also, out of curiosity: How did you find the actual problem?

Ah, I had a look at the code, did some tests and then it became obvious that two different things are wrong:
 * When a directory could not be read, the whole process was aborted and no other files and directories were handled any more (you experienced that)
 * In certain error conditions, the result of an operation was not reported back to the parent item (think files in a directory), so restic waits for it

The last thing you reported is that the data structure does not contain anything in the `type` field, that's another bug.

**Comment by fd0** [comment]
I've pushed another commit that ignores dirs with errors, so they aren't recorded in the backup. Could you please try again if restoring still outputs an error?

**Comment by JaCoB1123** [comment]
Thanks for the description :+1: 

I backed up everything again and tried to restore. Now the errors for the "Eigene ..." folders are gone. The errors for the savegame-folders are still shown though:

    restoring <Snapshot of [C:\Users\Jan Bader\Documents\] at 2015-11-08 15:14:46.9169251 +0100 CET> to C:/Backup/documents/
    error for C:\Backup\documents\Documents\My Games\Borderlands 2\WillowGame\SaveData: create node: filetype "" not implemented!
    error for C:\Backup\documents\Documents\My Games\Fallout3\Saves: create node: filetype "" not implemented!

**Comment by fd0** [comment]
Ok, let's declare that error a different issue and merge this one for now.

**Pull request merged**
