### PR TITLE
Improve limiting HTTP based backends

### LINKED ISSUE #1506: Potential issue or different implementation with --limit-upload
When uploading data (at least to B2) using --limit-upload 90 (in kB), data flows are bursting to sometimes 1MiB/s or higher, with long delays typically between each large burst.

I suspect the --limit-upload was done by averaging upload data over time.  That would result in 90kB/s over time, but there is no rate limiting of the actual upload itself in real time.  Is this a correct understanding of how it was implemented, or was it supposed to work another way and therefore a bug?

There are other mechanisms by which I could see a more smooth data flow, but it'd require modifications to the firewall rules or a tool to shape restic network traffic.

## Restic version details
restic 0.8.0 (b9441a1)
compiled with go1.9.2 on linux/amd64

## Output of `restic v0.80`
(incomplete -- lots of data to upload -- still in progress)
scan [/some/dir /some/dir]
[0:06] 17482 directories, 139992 files, 1.011 TiB
scanned 17482 directories, 139992 files in 0:06

## How did you run restic exactly?
(removed some specific directories -- not relevant)
/usr/bin/restic --cache-dir=/some/dir/restic-cache --limit-upload 90 backup --one-file-system /some/dir /some/dir --exclude /some/dir --exclude /some/dir

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior
Smooth, consistent data flows according to --limit-upload.  Expected doesn't imply it is what was intended by the developers.

## Actual behavior
Bursting, with long delays between bursts

## Steps to reproduce the behavior
Just run the command with a lot of files :)

## Do you have any idea what may have caused this?
I suspect the implementation of the upload limit was done over time and does not actually limit rate.

## Do you have an idea how to solve the issue?
Implement rate/throughput limit differently

## Did restic help you or made you happy in any way?
This is a great tool for cloud backup.

### PR DESCRIPTION
**Pull request by fd0**
Limit the bandwidth on the HTTP request via the RoundTripper

Closes #1506

### CODE REVIEW

**Comment by eliasp** [comment]
@fd0 Seems to have no effect here. Trying to minimize the impact on my crappy 1Mbit/s upstream connection by using `restic backup --limit-upload=500 […]`, but it still fully saturates the upstream at ~1Mbit/s.

**Comment by fd0** [comment]
did you rebuild the binary? What does `restic version` report?

**Comment by eliasp** [comment]
Yes, rebuilt it, version looks good:
```
restic 0.8.1 (v0.8.1-11-ga99637c6)
compiled with go1.9.2 on linux/amd64
```

**Comment by eliasp** [comment]
Can I provide any kind of useful debug information here?

**Comment by fd0** [comment]
Is the bandwidth limited at all? can you try with a small value, like 10?

**Comment by fd0** [comment]
I cannot reproduce what you're seeing, I see a slight overshoot at the beginning, but then it drops back to the limited bandwidth very quickly.

**Comment by fd0** [comment]
Ah! You said you have 1M**bit**, the value you need to pass restic is in K**byte** per second. So in order to not saturate your upstream bandwidth, you'll need to pass something less than "125"... Can you try that?

**Comment by eliasp** [comment]
Damn! I feel embarrassed for not paying attention to this - it works - thanks a ton for this!

**Comment by fd0** [comment]
Awesome, thanks for the feedback!

**Pull request merged**
