### PR TITLE
Add backend for Google Cloud Storage (GCS)

### LINKED ISSUE #211: Storage Backend: Google Cloud Storage
Google's [Cloud Storage Nearline](https://cloud.google.com/storage-nearline/) has a pricing similar to Amazon Glacier, but with ~3 sec response times and free ingress (upload) traffic.

### PR DESCRIPTION
**Pull request by fd0**
Main work by @diptadas, thank you very much! Successor of #1052.

TODO:
 * [x] Move files to new repo structure
 * [x] Vendor dependencies with `dep`
 * [x] Configure backend tests
 * [x] Test the backend thoroughly
 * [x] Add documentation to the manual (see https://github.com/restic/restic/pull/1052#issue-237117124)

Closes #211

### CODE REVIEW

**Comment by xor-gate** [comment]
Is the GCS the same as Gdrive or is it different?

**Comment by fd0** [comment]
It's entirely different. GCS is similar to S3.

**Comment by xor-gate** [comment]
I see, the tool rclone (golang) tool does support gdrive maybe we can find a way to create also a gdrive backend. But thanks for your answer, I will continue in a different thread.

**Comment by wjkohnen** [comment]
Uhm ok, I'll leave this here for now, feel free to close the review. Honestly I do not know what "a review" à la GitHub means.

**Comment by cafuego** [comment]
I flipped my storage URLs to the new gs backend recently and backup speed increased by a factor of 4! Thanks for doing this work @diptadas and merging it @fd0! 🧡

**Pull request merged**
