### PR TITLE
Switch to json-iterator for faster JSON encoding/decoding

### PR DESCRIPTION
**Pull request by greatroar**
What is the purpose of this change? What does it change?
--------------------------------------------------------

All JSON encoding/decoding outside the tests is now done by [json-iterator](http://jsoniter.com) instead of standard Go encoding/json to boost performance.

internal/index benchmarks:

```
name         old time/op  new time/op  delta
IndexNew-8    175µs ± 2%   178µs ± 2%   +1.58%  (p=0.000 n=20+20)
IndexSave-8   4.02s ± 2%   3.04s ± 3%  -24.24%  (p=0.000 n=20+20)
```

internal/repository:

```
name              old time/op    new time/op    delta
DecodeIndex-8       13.7µs ± 3%     6.8µs ± 5%  -50.72%  (p=0.000 n=20+20)
LoadTree-8           431µs ± 6%     275µs ± 3%  -36.08%  (p=0.000 n=20+20)
LoadAndDecrypt-8    13.1ms ± 4%    13.9ms ± 2%   +5.53%  (p=0.000 n=20+20)
LoadIndex-8         32.8ms ± 4%    22.6ms ± 4%  -31.04%  (p=0.000 n=20+20)
```

backend/rest shows no significant changes.

Although jsoniter promises [100% compatibility](http://jsoniter.com/migrate-from-go-std.html), it doesn't quite live up to that promise, as errors are reported differently (it has no UnmarshalTypeError). The old index format detection code had to be changed to handle this.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
In #838, @middelink demonstrated the performance issues with JSON and @fd0 suggested jsoniter (and some other libraries, which I didn't try). I'm not sure if it closes that issue.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by buschjost** [comment]
I am running with this merged for over a month now and it is working fine for me.

**Comment by aawsome** [comment]
Seems like we are getting merge conflicts after #2709 was merged.

@greatroar would you mind rebasing this?

Also, this deserves a changelog entry IMO.

**Comment by greatroar** [comment]
Rebased. Also upgraded to json-iterator 1.1.10 and cleaned up the go.{mod,sum} files (the trick is to use `go get` *without* `-u`, I just learned). I did not also update the benchmark figures, but if new ones are desired I can provide them.

**Comment by MichaelEischer** [comment]
I've rebased the PR to the current master. From some initial performance tests it looks like the performance benefit is much smaller than before.

**Comment by MichaelEischer** [comment]
Results for `go test -bench 'Save|Decode|Load' ./internal/repository`

```
name                 old time/op    new time/op    delta
DecodeIndex             4.98s ± 3%     2.94s ± 4%  -40.88%  (p=0.000 n=10+10)
DecodeIndexParallel     5.07s ± 6%     2.78s ± 6%  -45.08%  (p=0.000 n=10+10)
SaveAndEncrypt         51.9ms ± 4%    52.6ms ± 9%     ~     (p=0.780 n=9+10)
LoadTree                367µs ± 8%     226µs ± 8%  -38.38%  (p=0.000 n=10+10)
LoadBlob               11.7ms ± 2%    11.8ms ± 5%     ~     (p=0.842 n=9+10)
LoadAndDecrypt         12.4ms ± 5%    12.5ms ± 7%     ~     (p=0.481 n=10+10)
LoadIndex              32.3ms ± 5%    22.8ms ± 5%  -29.53%  (p=0.000 n=10+9)

name                 old speed      new speed      delta
SaveAndEncrypt       80.2MB/s ± 7%  79.9MB/s ± 8%     ~     (p=1.000 n=10+10)
LoadBlob             85.5MB/s ± 2%  84.9MB/s ± 5%     ~     (p=0.842 n=9+10)
LoadAndDecrypt       80.9MB/s ± 5%  80.1MB/s ± 7%     ~     (p=0.481 n=10+10)

name                 old alloc/op   new alloc/op   delta
SaveAndEncrypt         27.2MB ± 0%    27.2MB ± 0%   +0.00%  (p=0.000 n=10+10)

name                 old allocs/op  new allocs/op  delta
SaveAndEncrypt            136 ± 0%       139 ± 0%   +2.21%  (p=0.000 n=10+10)
```

As `LoadIndex` includes all steps like loading and decrypting the index, this is the speed-up that could be expected in practice.

**Comment by greatroar** [comment]
Rebased again and updated the benchmark figures in the commit message.

**Comment by MichaelEischer** [comment]
I've run a few tests with this PR. For a 550GB repo it reduces the user CPU time for `check` from 645 to 450 seconds and the system time from 156 to 135 seconds. That's essentially the 30-40% speed improvements also shown by the benchmarks. The maximum memory usage increased from 2GB to 2.5GB (it's that high because the repository contains several 300MB tree blobs).

Using `GOGC=10` the peak memory usage has shrunk to 1.25GB and 1.4GB, respectively, while the user time increased to 892 and 758 seconds. As restic already requires quite a bit of memory, I'm not sure whether the change is worth it. Especially as other commands will benefit far less.

**Comment by MichaelEischer** [comment]
As the memory usage of restic is already quite high, I think trading a higher memory usage for a limited speed increase is probably not worth it at the moment. So I'm closing this PR, but anyways thanks for trying to improve restic!

**Comment by greatroar** [comment]
That's fair. I never checked the memory use of this.

**Pull request closed without merging**
