### PR TITLE
Changelog 2390

### PR DESCRIPTION
**Pull request by ewhamilton**
What is the purpose of this change? What does it change?
--------------------------------------------------------

This is the changelog entry for PR #2391 / Bug #2390

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
Ah, you've integrated some merge commits into this PR... @rawtaz maybe just cherry-pick the commit (or remove the merge commits and force-push the branch)?

**Review by rawtaz — APPROVED** [review]
Thanks!

**Comment by rawtaz** [comment]
@ewhamilton I'm getting permission denied from the remote when trying to push to your branch. Can you check if the checkbox "Allow edits from maintainers" is checked in this PR (and if it isn't, check it)?

**Comment by ewhamilton** [comment]
@rawtaz The "allow edits from maintainers" is (and was) checked in the PR.   I don't know if it's something about my company's account settings, or what.  Can you cherry-pick?  We're talking about adding a 3 line file here.

**Comment by rawtaz** [comment]
@ewhamilton Weird. Sure, I'll fix it somehow. Thanks!

**Comment by rawtaz** [comment]
@ewhamilton Closing this, I made a new PR #2510 just like this one. Sorry for the trouble, and thanks!

**Pull request closed without merging**
