### PR TITLE
Bump go version to 1.21

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Increase the required Go version to 1.21 and update all direct dependencies. This will finally allow using the maps and slices packages. I've also removed usages of sha256-simd similar to https://github.com/minio/minio-go/pull/1958 .

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
No.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- ~~[ ] I have added tests for all code changes.~~
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Review by MichaelEischer — COMMENTED** [review]
LGTM

**Comment by sergeevabc** [comment]
Does crypto/sha256 work with processors without SSE4 and AVX?

**Comment by MichaelEischer** [comment]
> Does crypto/sha256 work with processors without SSE4 and AVX?

I'd expect so. As you seem to have access to such an old CPU, just run `go test -bench . crypto/sha256` to give it a try.

**Comment by sergeevabc** [comment]
``` console
$ ver && go version
Microsoft Windows [Version 6.1.7601]
go version go1.23.6 windows/amd64

$ go test -bench . crypto/sha256
goos: windows
goarch: amd64
pkg: crypto/sha256
cpu: Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz
BenchmarkHash8Bytes/New-2                1653452               728.7 ns/op        10.98 MB/s           0 B/op          0 allocs/op
BenchmarkHash8Bytes/Sum224-2             1688442               707.6 ns/op        11.31 MB/s           0 B/op          0 allocs/op
BenchmarkHash8Bytes/Sum256-2             1684946               704.1 ns/op        11.36 MB/s           0 B/op          0 allocs/op
BenchmarkHash1K/New-2                     121077              9845 ns/op         104.02 MB/s           0 B/op          0 allocs/op
BenchmarkHash1K/Sum224-2                  120547              9880 ns/op         103.64 MB/s           0 B/op          0 allocs/op
BenchmarkHash1K/Sum256-2                  121282              9890 ns/op         103.54 MB/s           0 B/op          0 allocs/op
BenchmarkHash8K/New-2                      16238             73778 ns/op         111.04 MB/s           0 B/op          0 allocs/op
BenchmarkHash8K/Sum224-2                   16306             73792 ns/op         111.01 MB/s           0 B/op          0 allocs/op
BenchmarkHash8K/Sum256-2                   16172             73933 ns/op         110.80 MB/s           0 B/op          0 allocs/op
PASS
ok      crypto/sha256   15.647s

**Pull request merged**
