### PR TITLE
Set go_import_path in Travis

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by fd0** [comment]
What's this about? :)

**Comment by gliptak** [comment]
Allows Travis builds to work for forks.

**Comment by fd0** [comment]
Ah, interesting! Thanks for the explanation, I did not see this use case before. It'll also be addressed in #2237 though, we'll then run all tests using Go Modules, so the `GOPATH` is not relevant any more.

**Comment by gliptak** [comment]
thanks for the pointers. i see that Azure runs Linux/Mac/Windows from a single config.

but it might have a similar issue, as forks' checkout locations isn't their "real" Github project name

**Pull request closed without merging**
