### PR TITLE
Regression test for #2979

### PR DESCRIPTION
**Pull request by greatroar**
This is a PR against #2984.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
@greatroar Could you recreate this PR against master? I've only noticed that this PR wanted to merge into #2984 after merging that one, sorry.

**Comment by rawtaz** [comment]
Yeah, please open it and rebase it so we can merge it, nice addition @greatroar!

**Comment by greatroar** [comment]
Could you reopen it so I can try to change the target branch? I'm not allowed to reopen, apparently.

**Comment by rawtaz** [comment]
Seems like this is because the restic:snapshots-json branch was deleted. Restic tells me that when I hover the "Reopen and comment" button.

**Pull request closed without merging**
