### PR TITLE
Fix backend List()

### LINKED ISSUE #1246: restic prune "removing -24839 blobs", then "id not found in any index"
## Output of `restic version`

```
restic 0.7.2 (v0.7.2-9-gc784a15a-dirty)
compiled with go1.8.3 on linux/amd64
```

(dirty just because I edited `build.go` to keep symbols)

## How did you run restic exactly?

```shell
$ export RESTIC_REPOSITORY=...
$ export RESTIC_PASSWORD=...
$ export GOOGLE_PROJECT_ID=...
$ export GOOGLE_APPLICATION_CREDENTIALS=...
$ ./restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 044a03a5858b00cce47487829ca63df6fdbd502233ed73644805de2d4f832be8: not referenced in any index
pack 068796f9e3d673b8bd5970e34de4c6f80b2d210350e40edc58907b7686c187e4: not referenced in any index
pack 07a78abe0a8c9eda6590ee4b834fa0d2eb2623f1c4dfcb259faf4149befb5ca6: not referenced in any index
pack 108caaaa58583c36b08e103986f55c6f8c16fa9a6d2f246775e05c68b3133b27: not referenced in any index
pack 196b608d0419f7ef01885e05d2e06650ee525d85b42ac9ccf33b12814039d734: not referenced in any index
pack 1b60df937c89427a6569631ef6d2d63523cbbf651cea9ea505000ecd9e946dc5: not referenced in any index
pack 1c1bfd623f4ebf6ebdd8936af2392f1190c7285b9fe37c746f7eb7bae92d668a: not referenced in any index
pack 1c2a50a28fa259464cd03f5e539789de70fdee9f061800f13f22bdb6ecf2c096: not referenced in any index
pack 1e03f4b44a9b0da2d57ae269c2081618d11596bc780e8c99383cd57ddf587f8b: not referenced in any index
pack 28140e3d6e1abf22d898fa9a6218400d6aadaf6bb589d9b927e7d185d3df5fd5: not referenced in any index
pack 28399f014c4b878b131cd49399f4925e10543e8200498163f88d7c2b23fb3224: not referenced in any index
pack 2f9e96eef2a310933b9eb360dfa1b9773cb4a4450c5bd65dba9b7d1b96976e82: not referenced in any index
pack 30407f338e6059be566d7314852b142725fbffc691424dd931a105e378143301: not referenced in any index
pack 34bec866ad982b469d1006399bedbc979e1b1ffd3e5a6756c864ca7ff3d0de42: not referenced in any index
pack 37ad137c5245469ebd2430d2496965828460ecdcbf8bf9aaf5fb10987330588d: not referenced in any index
pack 3e7179e414718607116a8e86159bad52dab67557d3b5298eb643575fe64daab3: not referenced in any index
pack 4008ba04667b9f363d77a99909398c0c3c9d9363c336c7142c08684fa7c3e6fe: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors


$ ./restic prune
counting files in repo
building new index for repo
[0:53] 100.00%  1000 / 1000 packs
repository contains 1000 packs (9418 blobs) with 4.766 GiB bytes
processed 9418 blobs: 44 duplicate blobs, 34.114 MiB duplicate
load all snapshots
find data that is still in use for 16 snapshots
[13:19] 100.00%  16 / 16 snapshots
found 34257 of 9418 data blobs still in use, removing -24839 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 25 packs, this frees 34.114 MiB
[1:46] 100.00%  25 / 25 packs rewritten
counting files in repo
[0:48] 100.00%  975 / 975 packs
finding old index files
saved new index as 5adfd1ed
remove 29 old index files
[0:05] 100.00%  25 / 25 packs deleted
done


$ ./restic prune
counting files in repo
building new index for repo
[0:54] 100.00%  1000 / 1000 packs
repository contains 1000 packs (9370 blobs) with 4.770 GiB bytes
processed 9370 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 16 snapshots
id 6b07085896d4bcd42011c8d79ef21e117ca189a463d38923e75ea880edbae9c1 not found in any index
github.com/restic/restic/internal/repository.(*MasterIndex).LookupSize
	src/github.com/restic/restic/internal/repository/master_index.go:54
github.com/restic/restic/internal/repository.(*Repository).LoadTree
	src/github.com/restic/restic/internal/repository/repository.go:536
github.com/restic/restic/internal/restic.FindUsedBlobs
	src/github.com/restic/restic/internal/restic/find.go:11
main.pruneRepository
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:168
main.runPrune
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func16
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
main.main
	src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
	/usr/lib/go-1.8/src/runtime/proc.go:185
runtime.goexit
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197
```

## What backend/server/service did you use?

Google Cloud Storage

## Expected behavior

This line should presumably show a non-negative number of blobs to be removed:

```
found 34257 of 9418 data blobs still in use, removing -24839 blobs
```

Then of course prune shouldn't fail again.

## Actual behavior

`usedBlobs` is greater than `stats.blobs`, causing the removal count to be negative. From the rest of the log this didn't sound problematic, but the crash afterwards seems to indicate otherwise.

## Steps to reproduce the behavior

I'm not sure, since the prune modified my repo.

## Do you have any idea what may have caused this?

Nope.

## Do you have an idea how to solve the issue?

Nope. I still need to figure out if this has broken any of the snapshots.

### PR DESCRIPTION
**Pull request by fd0**
* [x] Fix 1246
 * [x] Add proper backend tests for `List()` pagination
 * [x] Add plausibility check to `prune`

Closes #1246

### CODE REVIEW

**Comment by tamalsaha** [comment]
Thanks @fd0 for fixing this. 

Azure version has the same problem. https://docs.microsoft.com/en-us/rest/api/storageservices/List-Blobs?redirectedfrom=MSDN "Returning Result Sets Using a Marker Value" .

I wonder if a max results should be set for List calls and that be used with the test?

cc: @diptadas

**Comment by fd0** [comment]
I've already discovered that ;)

**Comment by fd0** [comment]
Hm, I wonder how we should handle the tests, creating more than a thousand files to test for this issue takes time (and needs to be done for each backend). Make the pagination value configurable (at least for the tests) and set it to something low, like 20 or so?

**Comment by tamalsaha** [comment]
Yeah. I was thinking that. Set the pagination to a lower value for tests.

**Comment by prattmic** [comment]
This PR fixes my issue from #1246. After a `restic rebuild-index`, `restic check` is happy again and subsequent `restic prune`s work fine.

**Comment by tamalsaha** [comment]
Any plans to do a 0.7.3 release?

**Comment by fd0** [comment]
Probably, but I'm not sure yet. What do you think?

**Comment by tamalsaha** [comment]
I would very much appreciate a release. We need a working restic binary for GCS .

**Comment by fd0** [comment]
I've released 0.7.3.

**Pull request merged**
