### PR TITLE
Attempt to make issue template a bit clearer

### PR DESCRIPTION
**Pull request by rawtaz**
### What is the purpose of this change? What does it change?

Make the issue template a bit more explicit or "clear" in the initial part of it's comment, to encourage more people to fill it out or use the forum.

### Was the change discussed in an issue or in the forum before?

No.

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in a subdir of `changelog/x.y.z` that describe the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/changelog-entry.tmpl))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Review by fd0 — CHANGES_REQUESTED** [review]
Very nice, I like the new text. just one minor thing: Would you mind putting the forum URL back in?

**Comment by rawtaz** [comment]
I'm terribly sorry, I removed it by mistake. IT's added back now, in a way such that the list items are still kept short, and the top part of the initial comment is still "light". Do you feel it works like this?

**Comment by rawtaz** [comment]
Feel free to speak your mind on the command and dot issue (third commit). I'm all for changing it if requested.

**Comment by ifedorenko** [comment]
The template works well for bug reports but I find it less useful for feature requests and enhancement proposals. Just my 2c.

**Comment by rawtaz** [comment]
That's a really good point @ifedorenko, I agree. I'll see what I can do to change it a bit in a new PR once this one is merged (unless @fd0 wants me to do it in this one - I just feel it's two separate things to clarify the template and to make it more adjusted to feature requests).

**Review by fd0 — APPROVED** [review]

**Comment by fd0** [comment]
This issue template is for bug reports, feature requests aren't handled at all. We can create a second template for feature requests and add a link in the README or so which loads the alternative template, see https://github.com/blog/2495-multiple-issue-and-pull-request-templates

But this is a different issue :)

**Comment by rawtaz** [comment]
Hmm, but the issue template has "This issue tracker is mainly for tracking *bugs and feature requests* ..." in it, and also there's an actual feature request every now and then for which there is an issue created to track it (often by you @fd0 :).

I don't think having a link to different "modes" of opening an issue works, as the absolute majority of people creating issues does so through the "New Issue" button. A link would only be used very rarely.

So, do you want to remove the "feature" stuff from the template? Or should it still be there, and we allow and use issues for feature requests too?

IMO feature requests are fine to have in issues as long as they are to the point - it's a neat place to track them in, and they are directly related to the development of the software (as opposed to questions etc).

**Comment by fd0** [comment]
> So, do you want to remove the "feature" stuff from the template? Or should it still be there, and we allow and use issues for feature requests too?

Let's leave it in and see how people use it in the next couple of weeks. Overall, I think reporting feature requests as issues is fine, and in this case it's not strictly necessary to fill out the template. Most people get that :)

The main purpose of the issue template is to aid in debugging be requiring people to submit all possibly relevant data beforehand, and (since we have the forum now) reduce the number of issues which are really just questions.

Thanks again!

**Pull request merged**
