### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by klauspost**
WIP for #26 - DO NOT MERGE!

Compiles, but all tests fail. 

Requires "RESTIC_TEST_CLEANUP=0" to avoid panics, since files are not closed before the test directory is deleted.

### CODE REVIEW

**Comment by fd0** [comment]
For the ansi output we can maybe use https://github.com/Bitbored/go-ansicon, there was a talk about that at FOSDEM: https://youtu.be/oM-MfeflUZ8?t=46m41s

**Comment by klauspost** [comment]
@fd0 - good idea. Is there ANSI other places? (Otherwise it might  be a bit overkill to add a dependency for just nice-looking tests)

Right now I get many failures like:
```
archiver_test.go:108: unexpected error: strconv.ParseInt: parsing "S-1-5-21-1075215122-993071141-2159816414-1000": invalid syntax
```

Any idea where should I start looking?

**Comment by klauspost** [comment]
Ah - a lot of places are just converting the os/user/User.Uid/Gid to an integer value. :/

**Comment by fd0** [comment]
> @fd0 - good idea. Is there ANSI other places? (Otherwise it might be a bit overkill to add a dependency for just nice-looking tests)

The tests are the most boring thing, much more interesting is the progress information that is updated via ANSI escape codes, e.g. https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L112

I'd suggest disabling color output for tests on windows, and test if `cmd.exe` is able to work with the other escape sequences. We might have a look at how git does status updates...

> Ah - a lot of places are just converting the os/user/User.Uid/Gid to an integer value. :/

Since restic was started with Unix/Linux in mind, `uid` and `gid` fields in the json data structures are integers. What do they look like in Windows? Strings?

What do you think about having additional fields `user` and `group` for that? This way, restic can easily distinguish these.

**Comment by klauspost** [comment]
I have just set them to 0 for now.

The biggest issue right now is files that aren't closed before they are deleted. If you have a file open, it cannot be deleted on Windows. I modified the local file storage, but there are still a lot of tests that are failing because of that. Do you know additional places I should look for that?

**Comment by fd0** [comment]
Hm, that's interesting. I don't have any idea where that is coming from, I thought all the code always takes care to close before removing. What files are removed in the tests? What tests fail exactly?

**Comment by fd0** [comment]
btw, I don't know if you're aware of that, but there's also #restic on irc.freenode.net for realtime debuggung ;)

**Comment by fd0** [comment]
I've just added some words about git commits to the contibuting guidelines, it'd be awesome if you could finde the time to read and apply them https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits

I'm aware that this looks like nitpicking, but please believe me it makes viewing the history so much nicer. :)

**Comment by klauspost** [comment]
@fd0 - I have read it, believe me ;) 

I made some one-line commits, to trigger the travis CI build to test I haven't broken other platforms.

As I wrote in the top, this is WIP. I will make a separate PR once this is running.

**Comment by fd0** [comment]
Great, I'm looking forward to it!

**Comment by klauspost** [comment]
All tests pass now. I will proceed test actual functionality now.

**Comment by klauspost** [comment]
The ansi library is broken (doesn't compile).

https://github.com/Bitbored/go-ansicon/issues/1

I made a small adjustment, and it works mostly ok. The automatic wrapping detection in [cmd_backup.go](https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L155) has to be adjusted by one, but with that, it looks good.

**Comment by klauspost** [comment]
It seems we are in a "good enough" state.  ANSI still needs fixing, but godep is not being helpful.

I will resubmit a "reduced" PR, with fewer commits tomorrow, and make sure stuff is documented. Finally it should also be possible to add windows/amd64 to the CI tests.

**Comment by fd0** [comment]
Cool, thanks a lot for your contribution! You don't need to open a new PR though, just force-push the commits into your branch, and this PR will reflect your changes. Force-push in a PR is okay :)

**Comment by klauspost** [comment]
Replaced by #259

**Pull request closed without merging**
