### PR TITLE
Optimize for dirs containing many entries (Introduce Node.Subtrees)

### LINKED ISSUE #2446: memory usage when backing up directories containing many empty files
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.9 on linux/amd64

How did you run restic exactly?
-------------------------------
See the attached test script, which I ran like this:

```
$ ./test 1000000
```
The script creates a directory containing a million empty files and then backs it up using restic. On an ext4 filesystem the directory is 22MB in size.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem

Expected behaviour
-----------------
Lower memory usage.

Actual behaviour
---------------
Higher memory usage, see the attached heap profiles with GOGC unset and GOGC=1 taken towards the end of the restic backup process. The peak RAM usage with GOGC unset is 2.8 GB.

With real-world workloads (such as large Maildirs containing more files), the RAM usage can exceed the amount of RAM on the system, leading to swap death.

Steps to reproduce the behaviour
-------------------------------
See the attached test script.

Do you have any idea what may have caused this?
-----------------------------------------------
I am guessing that restic prepares directory indexes in RAM instead of preparing them on-disk. The issue could also be inefficiently stored directory indexes.

Do you have an idea how to solve the issue?
-------------------------------------------
I don't know enough about restic's internals nor Golang memory profiling.

Did restic help you or made you happy in any way?
-------------------------------------------------
I was happy to find a good replacement for rdiff-backup.

### PR DESCRIPTION
**Pull request by aawsome**
What is the purpose of this change? What does it change?
--------------------------------------------------------

restic uses the `Tree` object to specify which files or subdirs are within a dir. A directory node specifies its contents by referring to a `Tree` object in `Node.Subtree`.
 A `Tree` is simply a list of `Nodes` and is stored in a single blob. 

This raises some problems if a directory contains many files:

- Trees need to be stored completely in memory leading to huge memory requirements
- Memory consumption is double or even 3x during operations like backup (actual tree, previous tree, json mashalling, etc) which makes the memory situation even more severe.
- Trees are usually processed sequentially disallowing efficient parallel processing
- Big blobs can be seen in the repository as they result in big packs. This can give attackers information about the repository without being able to decrypt the files

This PR introduces a new the object `Node.Subtrees` which is a list of `Tree` elements and consequently changes restics behaviour to use the new data structure. `Node.Subtree` is still be read and written if only one subtree exists. This allows this code to work with existing repositories.

As a consequence when having directories with many entries restic is faster and much less memory consuming while no difference can be seen with directories containing only few entries.

The PR is still WIP. Open points are implementation/change of tests and documentation. I would like to discuss the change before investing more time in exhaustive testing.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
closes #2446 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by rawtaz** [comment]
Please do not create PRs without first creating an issue if there isn't an issue for whatever the PR is supposed to address.

There needs to be a place for discussing the proposed feature/problem, and this is the issue.

Once there has been a conclusion in that issue, a PR can be filed. By doing it in this order, unnecessary work is avoided both for the core maintainer(s) and the one producing the PR.

**Comment by by-cx** [comment]
I am gonna test this code on our servers where we have tens of millions of files and we had to stop using Restic because of that.

**Comment by pabs3** [comment]
@by-cx: see also the GOGC=1 workaround from #2446 and the memory reduction strategies in #2523.

**Comment by pabs3** [comment]
Has any more progress been made on this PR? It would be great to have lower memory requirements in restic.

**Comment by aawsome** [comment]
> Has any more progress been made on this PR? It would be great to have lower memory requirements in restic.

No, it is still in the state of the start of 2020 and already suffering from being outdated w.r.t. master.
However, as it is a big change which includes changing the repo format I'm still waiting for comments on the direction of implemention.

Frankly said, I do not want to spend more time without the perspective of getting this PR merged soon after finishing my work. (and moreover in these Corona-times I actually do not have much spare time)

Please note that this PR also only applies to a very specific problem causing large memory usage (i.e. a huge number of *direct directory entries*; it does not generally apply to a huge number of entries within a *tree of directory*) - I would judge working on #2523 more fruitful as it applies to *all* settings with memory problems.

That said there are still open points (e.g. finish work on tests and docu). 
Moreover the whole direction of the solution can and should be discussed. Actually it generates the `Subtrees` data structure which collects a specific fixed number of directory entries. Having thought about this solution a bit in the last couple of weeks I actually favor more to change the `Tree` data structure into a JSON stream of `Node`s. That would allow to use the chunker to cut this down in many blobs. Many parts of this PR could still be used for that kind of format change but others would need a change.

**Comment by pabs3** [comment]
Ok, thanks for the info and your work on this and restic in general.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by pabs3** [comment]
Some folks working on bup are doing content based tree splitting, so that adding one file to a large maildir only adds a small amount of metadata rather than another copy of the directory.

https://lwn.net/Articles/824632/
https://github.com/jmberg/bup/commit/44006daca4786abe31e32a969a08778133496663

**Comment by rawtaz** [comment]
> It would be great to have lower memory requirements in restic.

There's other memory usage related PRs that have been merged and that you can benefit from by running the latest master build of restic that you can get from [here](https://beta.restic.net/?sort=time&order=desc) :)

**Comment by pabs3** [comment]
I noticed that the other memory usage related PRs that got merged did not have much effect on the memory usage for large directories.

**Comment by aawsome** [comment]
Closing this PR as I won't work anymore on this.

IMO the way to go would be to chunk tree packs using the standard chunking algorithm and then save the blob IDs which are needed to get a tree in JSON format in the `Contents` field of the node.

**Comment by MichaelEischer** [comment]
> IMO the way to go would be to chunk tree packs using the standard chunking algorithm and then save the blob IDs which are needed to get a tree in JSON format in the `Contents` field of the node.

That sounds like a reasonable way to adapt the repository format. I've started some experiments in that direction, including being able to incrementally generate, chunk and save trees, but it will take some time until that code is in any way presentable. The only downside I've noticed is that `recover` will no longer work in all cases. A chunked tree just won't be valid.

**Pull request closed without merging**
