### PR TITLE
Disable gox cross compile on darwin

### PR DESCRIPTION
**Pull request by fd0**

### CODE REVIEW

**Comment by fw42** [comment]
Hm this is getting super ugly... I would prefer if all this logic would live in two scripts (`ci/install` and `ci/run` or something like that) and Travis only calls those two scripts.

**Comment by fw42** [comment]
That would also make it easier to run the same steps locally or on another CI system or in a docker container or whatever.

**Comment by fw42** [comment]
I guess the Travis test output wouldn't look as nice though :/

**Comment by fd0** [comment]
Yeah, the Travis config file is ugly. I've reworked the commit, maybe that's better.

**Comment by fd0** [comment]
A problem with the script approach is, that we currently let Travis set up the development environment, that must be replicated with something else.

**Pull request merged**
