### PR TITLE
#2508: Adds support for `diff --json`

### PR DESCRIPTION
**Pull request by dp-github**
What is the purpose of this change? What does it change?
--------------------------------------------------------
Resolves Issue #2508, adding support for `diff --json`
Note:  As discussed in #2508 this only includes summary diff statistics in the json output

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
* #2508

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by rawtaz** [comment]
Can you please provide a complete and detailed example of output from this new feature?

**Comment by dp-github** [comment]
You bet.  Here is a sample command-line and it's output:
````
# restic -r . diff --json 1b5d25bb 0541d4d4
{"source_snapshot":"1b5d25bb","target_snapshot":"0541d4d4","changed_files":0,"added":{"files":3,"dirs":0,"others":0,"data_blobs":0,"tree_blobs":5,"bytes":14851},"removed":{"files":0,"dirs":0,"others":0,"data_blobs":0,"tree_blobs":5,"bytes":13426}}
````
Here is the same output, json-prettified:
````
{
  "source_snapshot": "1b5d25bb",
  "target_snapshot": "0541d4d4",
  "changed_files": 0,
  "added": {
    "files": 3,
    "dirs": 0,
    "others": 0,
    "data_blobs": 0,
    "tree_blobs": 5,
    "bytes": 14851
  },
  "removed": {
    "files": 0,
    "dirs": 0,
    "others": 0,
    "data_blobs": 0,
    "tree_blobs": 5,
    "bytes": 13426
  }
}
````

**Comment by darkdragon-001** [comment]
Any progress here?

**Comment by MichaelEischer** [comment]
I've thought a bit about this PR and I don't think it's a good idea to omit a substantial portion of the diff command output when passing the `--json` flag. After all it is just expected to change the output formatting but not the content. So I think we rather should opt for a output format similar to that of the backup command, which prints one line per changed/unchanged file and a summary object at the end.

For the individual changes, we could output something like the verboseUpdate from the backup command. Although we'd probably want to limit the struct to for example `MessageType`, `Action` and `Item` or so.
```Go
type verboseUpdate struct {
	MessageType  string  `json:"message_type"` // "verbose_status"
	Action       string  `json:"action"`
	Item         string  `json:"item"`
	Duration     float64 `json:"duration"` // in seconds
	DataSize     uint64  `json:"data_size"`
	MetadataSize uint64  `json:"metadata_size"`
	TotalFiles   uint    `json:"total_files"`
}
```
The summary output should then also include a `MessageType` to allow discerning the different output lines.

Another option would be to behave like the `find` command which incrementally assemble a single large JSON object.

**Comment by dp-github** [comment]
I will support whichever decision you make, but here's an argument for the
alternative:

Dont let the perfect be the enemy of the good.  This PR implements json
output where it's not currently available at all, and even if its
imperfect, that improvement. A future PR can fix the issues you raise.

**Comment by darkdragon-001** [comment]
I would still vote for an implementation in combination with the `--quiet` flag (https://github.com/restic/restic/issues/2508#issuecomment-642825328). A single incrementally build json file would make parsing and error handling a lot easier for my use case (I wait for the command to be finished anyway).

**Comment by MichaelEischer** [comment]
@dp-github The json output is considered part of the API of restic and thus we try to avoid breaking compatibility if possible. As the PR currently outputs a single JSON document and does not prepare for a streaming JSON output, currently the PR essentially makes the decision that the list of changed files should be part of the summary JSON message.

Regarding a single JSON document, I'm worried that this might become very large. Just consider a snapshot which contains a few million files. Then the diff output can reach a size of a few hundred MBs. In that case I'd prefer a output format that is easier to parse incrementally. Btw, to avoid that restic has to store the whole output in memory, a single JSON document would essentially  be an array with entries describing the change for each file. And that format is basically what you get when replacing the new lines in the streaming format and add square brackets around the result.

**Comment by MichaelEischer** [comment]
Replaced by #3592

**Pull request closed without merging**
