### PR TITLE
Add rclone to the Docker container

### PR DESCRIPTION
**Pull request by alexander-bauer**
What does this PR change? What problem does it solve?
-----------------------------------------------------

This change adds the `rclone` Alpine package to the Docker container. 

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

This is discussed in #4640.

There are some concerns there about the Rclone release cycle, and what it will take to keep the Restic Docker container up to date. I would argue that keeping Rclone up to date falls into the same problem category as the other packages included by our container: we probably need a general solution for publishing updated containers in-between Restic releases, but that should be a separate issue.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by alexander-bauer** [comment]
Unfortunately, making this change increases the size of the container pretty dramatically.

```
 ⇒  podman image ls localhost/restic/restic
REPOSITORY               TAG         IMAGE ID      CREATED        SIZE
localhost/restic/restic  latest      3680a2d3faad  7 minutes ago  41.6 MB  # from main
localhost/restic/restic  rclone      423c2eaf74a8  19 hours ago   127 MB   # from this branch
```

These are both container images built on my laptop with `podman`. I was hoping there's a flaw in my methodology here, like squashed layers being reused for the main branch, or something, but it looks like the `rclone` binary really is about that size.

```
 ⇒  unzip -l rclone-v1.66.0-linux-amd64.zip | tail -1 | xargs | cut -d' ' -f1 | numfmt --to=iec-i --suffix=B
66MiB
```

I realize I'm being a bit fast and loose with the units here, but ultimately I think whether `rclone` belongs in the standard image is down to the judgement call of whether that extra bulk is worthwhile.

The alternate approach would be to build and release a new flavor of the image which does come with the `rclone` binary. I think that wouldn't be too big a lift, but I'm a little hazy on how GHCR is managed. I'd be inclined to say that a "restic+rclone" variant would belong in its own image repository, as opposed to just being tagged differently, but I'm not sure how easy that is here.

Anyway, I'm eager to hear y'all's thoughts.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
> we probably need a general solution for publishing updated containers in-between Restic releases, but that should be a separate issue.

Probably, however, that issue **MUST** be resolved first before we can consider this PR.

> I'd be inclined to say that a "restic+rclone" variant would belong in its own image repository, as opposed to just being tagged differently, but I'm not sure how easy that is here.

It's not uncommon to have images with different base images or slim and regular variants of an image in the same repository.

**Comment by alexander-bauer** [comment]
@MichaelEischer Solving the release / update cycle first seems reasonable to me. Should I open another issue for discussing that, or is there a more appropriate place?

**Comment by MichaelEischer** [comment]
@alexander-bauer Let's discuss that in #4640. My idea would be to setup a github ci job that regularly rebuilds the container and pushes it to ghcr.io (the Github container registry). Then we don't have to mess around with registry access permissions.

**Comment by MichaelEischer** [comment]
I'll close this PR for now. It should be easy enough to recreate once the automatic rebuilds are in place.

**Pull request closed without merging**
