### PR TITLE
AIX port

### PR DESCRIPTION
**Pull request by greatroar**
What is the purpose of this change? What does it change?
--------------------------------------------------------

Make restic run on AIX.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

At #2727,  @Mikesch-mp requested AIX binaries and verified this port works, as far as basic functionality goes.

Release binary building is not in this PR, but at least it enables the build so people can build their own. Adding release binaries is a one-liner, but I don't have access to an AIX box, so I can't debug them if anything is wrong, and I'm not sure if restic binaries should be made available if even the developer can't test them.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by greatroar** [comment]
Looks like this won't build properly with Go 1.11, which doesn't know about AIX. There might be a workaround, but since Go 1.11 is end of life (and 1.12 will soon be too), I'm not going to try any further until the minimum compiler version is bumped.

**Comment by greatroar** [comment]
Back to reviewable state as 1.12 is now the minimum supported Go version.

**Comment by Mikesch-mp** [comment]
Will this be merged in the near future?

**Comment by rawtaz** [comment]
It would probably be a good idea to rebase this on current master, and then it needs some testing again to make sure it's up to snuff. It's currently unlikely that it will be merged any day now. @Mikesch-mp Have you tried it? Can you rebase it on master and see how it works out?

**Comment by MichaelEischer** [comment]
I've rebased the PR to the current master branch. This required a few small changes: The docs change has already been merged, node_aix.go now uses the concrete type `statT` and I've changed the `integration_fuse_test.go` to list supported instead of unsupported build targets.

**Comment by fd0** [comment]
I've pushed two commits which remove the old `run_integration_test.go` and synchronizes for which architectures we cross-compile with the list of architectures we build release binaries for.

**Review by fd0 — APPROVED** [review]

**Comment by Mikesch-mp** [comment]
i tested the latest master branch and it build flawless (also rest-server), now i will test it on some lpars that uses restic

**Comment by Mikesch-mp** [comment]
Works as expected without any errors.

**Comment by MichaelEischer** [comment]
Thanks a lot for testing!

**Pull request merged**
