### PR TITLE
Add Dockerfile to run travis tests locally

### PR DESCRIPTION
**Pull request by fd0**
This PR tracks the progress on getting the travis tests to run in a docker container.

### CODE REVIEW

**Comment by fd0** [comment]
@fw42 promised to take a look. :)

**Comment by fd0** [comment]
@fw42 *nudge*

**Comment by fw42** [comment]
yeah sorry didn't have time yet :) soon.

**Comment by fd0** [comment]
Hey @silvio, thanks a lot for taking the time to look at the `Dockerfile`!

Most of your comments are straightforward and will be integrated. I've based this image on Ubuntu so that it's as similar to the environment Travis runs in as possible, and that is based on Ubuntu.

Can you maybe assist in getting the Travis test scripts running?

**Comment by silvio** [comment]
Hi, sorry no.
I don't have knowledge of travis at all.
I would use images which are available at now. The set up of a travis-service is a complex as only to use the `travis-cli` (At least according to this document <http://vzmind.tumblr.com/post/9412611799/why-travis>). It exists some docker images for the travis-cli (like: <https://registry.hub.docker.com/u/tomdesinto/docker-travis-run> and some other).

What you are trying to accomplished? You can register a travis service in the settings of this project and all pushes create a job at <http://travis-ci.org>.

Or you can some replacement services like <https://github.com/grosser/wwtd> or <https://github.com/jolicode/JoliCi>. This services could be done in a container.

**Comment by fd0** [comment]
My goal is to give developers an easy way to run all the tests that Travis runs, in exactly the same environment. This would mean only running the client part of Travis and execute the steps from the `.travis.yml` file.

Travis hosts a free service  for open source projects, so as soon as someone opens a Pull Request or pushes to some branch, a Travis job is kicked of to test the new code. They schedule these jobs among all the others, including the jobs from their commercial clients, which have a higher priority. So unfortunately during my mostly active development time (after 18:00 o'clock Germany), it's the middle of the day for North America, this means that Travis is really busy and it takes up to half an hour to get a feedback from Travis.

I usually run my tests locally of course, but this is not exactly the same, and doesn't run on all supported Go versions. Most of the time when opening a new Pull Request for a new feature I'm working on, I break something really small for e.g. Go 1.3, that isn't a problem for Go 1.4. The major drawback here is that I only realize this half an hour later, when Travis has executed the job.

I'd like to have a much faster feedback loop.

**Comment by fd0** [comment]
In #235 a `Vagrantfile` has been added so tests can be run on Linux, FreeBSD and OpenBSD. That's enough for now, I'm closing this PR.

**Pull request closed without merging**
