### PR TITLE
resume interrupted backups

### LINKED ISSUE #59: Resume interrupted backups
When a backup is interrupted and restarted later, restic writes all data again, newly encrypted, because the index is written at the end so restic doesn't know about what blobs have already been stored.

This can be fixed for example by regularly (e.g. every X minutes or every Y files or so) uploading a preliminary index that is removed after the next preliminary index (which is a superset of the first one) has been uploaded. Once the final index was successfully uploaded, all preliminary indexes from this session are removed.

Connects #243

### PR DESCRIPTION
**Pull request by fd0**
This breaks out some commits from #252 (which was clearly too large to be done in one PR). The code in this PR adds resuming of interrupted backups by regularly writing an index (utilizing the new supersedes field) and reading these when a backup should be resumed.

Closes #59

### CODE REVIEW

**Comment by fd0** [comment]
@episource I've handled the bug you discovered, thanks again.

**Comment by episource** [comment]
Is a RWMutex reantrant? The documentation does not say anything about this...

Context: 
`AddInFlight` acquires a RW-Lock (`mi.inFlight.Lock()`) and then calls `Has`, which tries to acquire a Read-Lock (`mi.idxMutex.RLock()`). Without RWMutex being reantrant this should fail/dead-lock.

Assuming go locks to be reantrant I tried the same while implementing my draft of `StoreInProgress`. Due to that I learned the hard way, that my assumption was wrong and Mutex (not RWMutex) is not reantrant.

**Comment by fd0** [comment]
Uhoh. I'll have a look, thanks again!

**Comment by episource** [comment]
No, just forget my comment. It's plain wrong.

**Comment by fd0** [comment]
Hm, I'd expect that acquiring the r lock while an r/w lock is already held leads to a deadlock...

**Comment by fd0** [comment]
Ah, indeed, now I see it.

**Comment by fd0** [comment]
Any other comments? Otherwise I'll merge this branch now :)

**Comment by episource** [comment]
Not from my side...

**Comment by fd0** [comment]
cool

**Pull request merged**
