### PR TITLE
Switch documentation to Sphinx

### PR DESCRIPTION
**Pull request by Thor77**
* Converts existing documentation to ReStructuredText
* Started bundling and reorganizing various parts of the manual

~~**Please don't merge, yet** as some more testing (with readthedocs.org) and some minor tweaks are missing~~

### CODE REVIEW

**Comment by fd0** [comment]
Looks good, a few things I noticed:
 * The `Manual.md` and `Design.md` documents are linked in the README, the links need to be corrected
 * REST_backend.md is still markdown
 * The SVG version of the logo is used
 * Add `doc/_build` directory to the gitignore file
 * Maybe make the logo in the top-left corner smaller? it's too present :)

**Comment by Thor77** [comment]
What do you think about this logo size (60%) and navbar-color?
screenshot

**Comment by fd0** [comment]
Looks good (apart from the logo on the right side with the wrong font ;)

**Comment by Thor77** [comment]
The documentation is working perfectly fine on readthedocs now: https://thor77-restic.readthedocs.io/en/switch-to-sphinx/

**Comment by Thor77** [comment]
Fixed your concerns from yesterday, let me know if there's anything else (except squashing my commits) I should do.

**Comment by fd0** [comment]
So, then squash the commits and get this merged!

**Comment by Thor77** [comment]
Done :)

**Pull request merged**
