### PR TITLE
Fix #3062

### LINKED ISSUE #3062: Prune results in context canceled with b2 Backend
Output of `restic version`
--------------------------
restic 0.11.0 (v0.11.0-24-g636b2f2e9) compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
Just `restic prune` without any arguments.
Environment Variables set:
```
B2_ACCOUNT_ID
B2_ACCOUNT_KEY
RESTIC_REPOSITORY
RESTIC_PASSWORD
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze (B2) Backend

Expected behavior
-----------------
`restic prune` prunes the repository and exits with a zero status code.

Actual behavior
---------------
Restic exits with a non-zero status code and the following backtrace:
```
<ommittted previous lines>
[0:10] 100.00%  45 / 45 files deleted
repacking packs
[5:15] 100.00%  612 / 612 packs repacked
context canceled
Close
github.com/restic/restic/internal/backend/b2.(*b2Backend).Save
	github.com/restic/restic/internal/backend/b2/b2.go:211
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
	github.com/restic/restic/internal/backend/backend_retry.go:56
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
	github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52
github.com/cenkalti/backoff/v4.RetryNotify
	github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Save
	github.com/restic/restic/internal/backend/backend_retry.go:50
github.com/restic/restic/internal/cache.(*Backend).Save
	github.com/restic/restic/internal/cache/backend.go:54
github.com/restic/restic/internal/repository.(*Repository).savePacker
	github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).FlushPacks
	github.com/restic/restic/internal/repository/repository.go:344
github.com/restic/restic/internal/repository.(*Repository).Flush
	github.com/restic/restic/internal/repository/repository.go:321
github.com/restic/restic/internal/repository.Repack
	github.com/restic/restic/internal/repository/repack.go:190
main.prune
	github.com/restic/restic/cmd/restic/cmd_prune.go:477
main.runPruneWithRepo
	github.com/restic/restic/cmd/restic/cmd_prune.go:176
main.runPrune
	github.com/restic/restic/cmd/restic/cmd_prune.go:152
main.glob..func19
	github.com/restic/restic/cmd/restic/cmd_prune.go:36
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	github.com/restic/restic/cmd/restic/main.go:98
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_amd64.s:1374
```

Steps to reproduce the behavior
-------------------------------
Run `restic prune` on a repository stored in backblaze.

Do you have any idea what may have caused this?
-----------------------------------------------
It most likely is connected to the recent merge of the prune rewrite, since it worked before. I am not familiar with the code enough but my guess is that something is closing the context in a different go routine, which results in a failure during the `Write`-call.

Do you have an idea how to solve the issue?
-------------------------------------------
Not really, but I could take a closer look and try to debug it later. I am not the most versatile Go programmer though.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is an amazing backup tool and I use it every day. Fortunately I did not have a disaster where I needed to restore everything but having a great scriptable backup solution at my disposale really helps me sleep better at night :)
Thank you so much for this amazing tool!

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Fixes invalid context in parallel repacking code.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Hopefully closes #3062 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Review by greatroar — APPROVED** [review]

**Comment by fd0** [comment]
Thanks for the really quick response and diagnosis!

Is this ready for review?

**Comment by aawsome** [comment]
> Is this ready for review?

It is.
Just write if this needs a changelog entry.

I'm wondering why this wasn't covered by tests so far - if I find some time, I can have a closer look and add a testcase (but this may take a couple of days..)

**Comment by fd0** [comment]
Ah, since it's a fix for a not-yet-released feature I think it's not relevant to add a changelog entry. I can confirm the PR fixes the issue.

It feels to me that the big part in the middle of the function could be extracted to its own function, thereby making the scope of the context object more obvious, but that'll do for now.

It'd be great if you could look into how we can test that. I think we don't have integration tests which run a real prune on a real cloud backend yet...

**Review by fd0 — APPROVED** [review]
LGTM!

**Comment by aawsome** [comment]
> It'd be great if you could look into how we can test that. I think we don't have integration tests which run a real prune on a real cloud backend yet...

@fd0: I was still a bit irritated about why this error didn't show up in the tests. I thought - despite you telling me - that it wouldn't matter if this is called with a local or a cloud backend as in both cases we will call some backend methods with a cancelled context. 
So I took some more time to analyze this. Turns out you are right about the cloud backends :wink:  - in the local backend the context is simply unused in almost all methods... Same applies to the mem backend.
So the backends we use in the tests simply do not detect the cancelled context. 

I suggest to check for the context in the mem backend which is anyway only used in tests and I am about to prepare a PR. This would have detected this cancelled context (and also reveals some other context issues in the archiver code, which I'm about to fix within that PR).

A second possibility would be to add these context checks to the local backend - either directly in the backend or using the hook @MichaelEischer proposed. But here I'm not perfectly sure about the way to go...

**Comment by aawsome** [comment]
I feared a bit that the archiver code had some context issues. Turned out this is all just in the archiver test code - same problem as here, but with `tomb` instead of `errgroup`. I fixed these in #3068.

**Comment by fd0** [comment]
Great, thanks for taking the time to debug this further.

**Pull request merged**
