### PR TITLE
adds advice to run restic check regularly

### PR DESCRIPTION
**Pull request by jniggemann**
First shot at partly fixing #1137...
Ideas / comments?

### CODE REVIEW

**Review by zcalusic — CHANGES_REQUESTED** [review]
3 typos in the last paragraph. Other than that, I like it. 👍

**Comment by jniggemann** [comment]
Argh, will fix the typos ...

**Review by fd0 — CHANGES_REQUESTED** [review]
Looks very good, thanks a lot for your contribution!

I know this sounds a bit petty, but may I ask you to reformat your commits so that they conform to the general style we used for restic? It's documented here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits and here https://chris.beams.io/posts/git-commit/

Especially:
 * Start the terse subject line with an upper case letter (except when there's a module prefix like `backend: ` or so)
 * Use imperative for the verb: Describe what the commit does when applied
 * Suash the two commits into one, there's no value in keeping the typos ;)
 
 So I'd suggest using the following subject for the commit: `Add advice to run check regularly`
 
 Thanks!

**Comment by jniggemann** [comment]
Petty? Just a tad ;-) So - no problem, it's your project so you set the guidelines.
My PRs will be about documentation, should I prefix them with `doc:`?

**Comment by fd0** [comment]
Good idea, for commits that only change documentation. Thanks!

**Review by fd0 — APPROVED** [review]
Thanks!

**Pull request merged**
