### PR TITLE
Doc Addition: Wasabi repo setup instructions

### PR DESCRIPTION
**Pull request by HugoReeves**
What is the purpose of this change? What does it change?
--------------------------------------------------------

This is an addition to the 'preparing a new repo' documentation that adds specific instructions for the AWS S3 conformant object storage provider [Wasabi](https://wasabi.com). **NOTE**: I am not affiliated with Wasabi and wrote this as a service to restic not to Wasabi. This PR does not necessarily change anything, it simply adds more repo specific information to the documentation. Most of the content for this documentation addition was taken from the [Wasabi support topic on restic backups](https://wasabi-support.zendesk.com/hc/en-us/articles/115002240372-How-do-I-use-Restic-with-Wasabi-).

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Not to my knowledge. I have seen some discussion of Wasabi across the restic forum and I believe Wasabi is being used by many restic users, hence why I thought specific documentation would be useful.

Checklist
---------
**PR Author Note**: These have been checked for clarity however this PR only changes one documentation file.

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Review by moritzdietz — APPROVED** [review]
LGTM.

**Comment by rawtaz** [comment]
I started looking over this and had a few small adjustments to correct, but then I realized that I'm not sure we should add this provider-specific info to the docs. This service seems to be S3 compatible, and looking through the instructions they're essentially the same as for Amazon S3, just different URLs.

So, if we add this, is it actually useful, and won't we have to add a lot of other specific docs as well? It can become a never ending spiral. Perhaps instead we should keep the focus of this part of the doc on how to init a repo for the individual backends, which I think has been the purpose of the article in the first place. That is, whether an S3 server is served by company A, B or C shouldn't really matter, as long as the docs show how to configure *such a service* or *that backend/protocol*.

Thoughts? As far as *I* am concerned, it's up to @fd0. If he thinks it should be merged, I'll go ahead with a couple of small change requests before we merge.

**Comment by HugoReeves** [comment]
@rawtaz This was also something I considered before authoring. I am perfectly happy if this PR is rejected and a decision is made to avoid including provider specific backend details.

I noted, before authoring these changes, that minio information is included in the docs; this make sense to me because it is a self hosted alternative to S3 whereas Wasabi is a commercial alternative. Another option would be creating an entirely new section of documentation, maybe a different subdomain, that offers very specific guides and tutorials for setting up different backends. This would present a lot more work and may be out of scope of what is desired for the restic project.
Thanks

**Comment by moritzdietz** [comment]
I think adding this would not really overcrowd the docs. It would probably make it "easier" for new users to see if their platform of choice is supported right away. Like rclone does it.

**Comment by fd0** [comment]
I like the proposal to split the docs into a section for each backend (local, sftp, s3, b2), and a section describing the setup for various cloud providers (AWS, Wasabi etc).

**Review by rawtaz — APPROVED** [review]
Looks good, we'll merge this now and probably move it to a separate section later.

**Comment by fd0** [comment]
Ok, thanks!

**Comment by HugoReeves** [comment]
Thanks for merging this. As a sidenote, I have been using restic frequently for 4 months now and have been impressed with the experience.

@fd0 If I have time, would a draft PR implementing this split documentation approach be appreciated?
I'm just thinking a separate sidebar section in the readthedocs - among "talks", "faq", "manual" - called "Provider specific backend instructions".

**Comment by rawtaz** [comment]
@HugoReeves Please continue the discussion in the active issue #2490 - this PR is closed 🌶

**Pull request merged**
