### PR TITLE
Set O_NOATIME flag on Linux

### PR DESCRIPTION
**Pull request by greatroar**
What is the purpose of this change? What does it change?
--------------------------------------------------------

The O_NOATIME flag is set when opening a file on Linux, which prevents the access time from being updated on every read.

Citing Kerrisk, The Linux Programming Interface:

> The O_NOATIME flag is intended for use by indexing and backup programs. Its use can significantly reduce the amount of disk activity, because repeated disk seeks back and forth across the disk are not required to read the contents of a file and to update the last access time in the file’s i-node[.]

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

restic used to do this, but the functionality was removed along with the fadvise call in #670. That solved #666, which is unrelated to O_NOATIME.

The implementation here is different: it uses fcntl, so we don't need to open the file twice when an error occurs (leading to duplicate path traversals). Errors are expected to be common, as O_NOATIME is only available to the owner of a file or root. Also, fcntl can set O_DIRECT on FreeBSD and is needed to set F_NOCACHE on MacOS, in case we ever want to do that.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Review by MichaelEischer — APPROVED** [review]
LGTM. I've rebased the PR, moved the setFlags call to fs_local.go (see commit message) and updated to test.

@greatroar Can you have a look at my modifications to the `setFlags` usages?

**Comment by MichaelEischer** [comment]
@greatroar Can you have a look at my modifications to your PR?

**Comment by greatroar** [comment]
Merged the t.Log message into t.Skip setflags_linux_test.go. Your changes LGTM.

**Comment by MichaelEischer** [comment]
Thanks for checking.

**Pull request merged**
