### PR TITLE
Add support for reading password from external command

### PR DESCRIPTION
**Pull request by juergenhoetzel**
This allows reading the password from an password manager (like [pass](https://www.passwordstore.org/))

Signed-off-by: Juergen Hoetzel <juergen@archlinux.org>

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
No

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

This is inspired by a feature of [mbsync](https://wiki.archlinux.org/index.php/isync): `mbsync` supports reading the password from an external command.

Using `pinentry-gnome3` I get a nice prompt when the GnuPG agent cache expired. 

This is my systemd/timer setup I use for doing daily backups without storing the password in a plaintext file:

* Oneshot-Service
```ini
juergen@samson:~ → systemctl --user cat restic
# /home/juergen/.config/systemd/user/restic.service
[Unit]
Description=Restic Backup

[Service]
Type=oneshot
Environment=RESTIC_PASSWORD_COMMAND='pass Backup/restic@samson'
Environment=RESTIC_REPOSITORY=sftp:restic@shaun:/ext/restic
ExecStart=/home/juergen/bin/restic backup ${HOME}/
```
* Timer
```ini
juergen@samson:~ → systemctl --user cat restic.timer
# /home/juergen/.config/systemd/user/restic.timer
[Unit]
Description=Run restic backup daily

[Timer]
OnCalendar=*-*-* 14:06:00
Persistent=true

[Install]
WantedBy=timers.target
```

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
If you are in interested in this commit I can also add the documentation.

**Comment by fd0** [comment]
Hey, thank you very much for contributing to restic! Why do you think this feature is needed? You can just supply the password for restic on stdin, like `pass backup/restic | restic backup /home`...

**Comment by juergenhoetzel** [comment]
> Hey, thank you very much for contributing to restic! Why do you think this feature is needed? There 
are several ways to supply the password to restic with a program:

Thanks for your feedback and especially creating `restic`! 👍 
> 
> * pipe the password into restic via stdin: `pass backup/restic | restic backup /home`...

I wasn't aware `restic` can read the password from a non-terminal device. But input redirection will lead to other issues when restic tries to read from `stdin` in subcommands like:

```bash
pass Backup/restic@samson |restic key add
```
```
main.readPassword
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/global.go:281
main.ReadPassword
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/global.go:317
main.ReadPasswordTwice
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/global.go:335
main.getNewPassword
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/cmd_key.go:107
main.addKey
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/cmd_key.go:113
main.runKey
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/cmd_key.go:194
main.glob..func12
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/cmd_key.go:26
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /home/juergen/go/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /home/juergen/go/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /home/juergen/go/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /home/juergen/go/src/github.com/restic/restic/cmd/restic/main.go:86
runtime.main
        /usr/lib/go/src/runtime/proc.go:201
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1333
unable to read password
```


> * use the shell and `--password-file`: `restic backup --password-file <(pass backup/restic) /home`

Has the same issue as the above solution: `stdin` redirection. Also the shell will generate a temporary file containing  the password: Which might be readable by an attacker (`extundelete`or other filesystem tools).

> * use the environment: `RESTIC_PASSWORD=$(pass backup/restic) restic backup /home`

This seems like a good solution! The only disadvantage i see: The plaintext password stays in the  environment while `restic` is executing:

```bash
ps e $(pidof restic)
```

**Comment by fd0** [comment]
The code is good, still missing is an entry for the changelog and an update to the documentation. Unfortunately, we don't have tests in place for user-interface stuff like this, so let's leave it for now.

**Comment by juergenhoetzel** [comment]
> Ah, that's not the case: The shell starts the other process (e.g. `pass`) and connects a pipe to its stdout, which is then passed as a path to the file descriptor to restic:

Yep I was wrong here. I confused it with here-docs (`<<EOF`).

> Yep, but reading the environment is restricted to the current user (who could also just debug the process and dump its memory) or `root`, who could do anything.

Yep this is correct. You have to trust `root` anyway. But compared to environment variables you can prevent swapping out sensitive data (`mlock(2)`) in C: I don't know if `restic` is using this mechanism.

> Don't get me wrong, I'm not completely against adding this feature, I'm just worrying about feature creep and I'm trying to find out what benefits the additional complexity brings. :)

I fully agree. Less code, less bugs 😀

**Comment by fd0** [comment]
So, what do we do? Is your use case covered by the options we discussed or do you still think it's valuable to merge this feature?

**Review by fd0 — APPROVED** [review]
Ok, fine with me

**Comment by fd0** [comment]
I've added documentation and a changelog file.

**Pull request merged**
