### PR TITLE
New archiver code

### LINKED ISSUE #549: Unable to backup/restore files/dirs with same name
## Output of `restic version`

restic 0.1.0
compiled at 2016-07-20 12:42:43 with go1.6.3
## Expected behavior

After restore all directories should be restored.
## Actual behavior

Only one directory is restored.
## Steps to reproduce the behavior
1. Create files

/tmp/restic/FILESNEW01/Dir01/Test01.txt
/tmp/restic/FILESNEW01/Dir01/Test02.txt
/tmp/restic/FILESNEW01/Dir01/Test03.txt

/tmp/restic/FILESNEW02/Dir01/Test01.txt
/tmp/restic/FILESNEW02/Dir01/Test02.txt
/tmp/restic/FILESNEW02/Dir01/Test03.txt

content of files:
**`cat /tmp/restic/FILESNEW01/Dir01/Test0*`**
`Content file. /tmp/restic/FILESNEW01/Dir01/Test01.txt`
`Content file. /tmp/restic/FILESNEW01/Dir01/Test02.txt`
`Content file. /tmp/restic/FILESNEW01/Dir01/Test03.txt` 

**`cat /tmp/restic/FILESNEW02/Dir01/Test0*`**
`Content file. /tmp/restic/FILESNEW02/Dir01/Test01.txt`
`Content file. /tmp/restic/FILESNEW02/Dir01/Test01.txt`
`Content file. /tmp/restic/FILESNEW02/Dir01/Test03.txt`

I want backup
- /tmp/restic/FILESNEW01/Dir01/
- /tmp/restic/FILESNEW02/Dir01/

Commands:
Initiate repository in /tmp/restic/BACKUP directory
- **restic -r /tmp/restic/BACKUP/ init**

Make backup 
-  **restic backup /tmp/restic/FILESNEW01/Dir01 /tmp/restic/FILESNEW02/Dir01 -r /tmp/restic/BACKUP/**
  
  `scan [/tmp/restic/FILESNEW01/Dir01 /tmp/restic/FILESNEW02/Dir01]`
  `scanned 2 directories, 6 files in 0:00`
  `[0:00] 16.67%  0B/s  51B / 306B  0 / 8 items  0 errors  ETA 0:00
  duration: 0:00, 0.01MiB/s`
  `snapshot 4d197b90 saved`

Checking if backup exists in repository
- **restic -r /tmp/restic/BACKUP/ snapshots**

`ID        Date                 Host        Directory`

`4d197b90  2016-07-26 14:14:43  nebss       /tmp/restic/FILESNEW01/Dir01
                                           /tmp/restic/FILESNEW02/Dir01`

Restore backup
- **restic -r /tmp/restic/BACKUP/ restore 4d197b90  -t /tmp/restic/RESTORE/**

`restoring <Snapshot 4d197b90 of [/tmp/restic/FILESNEW01/Dir01 /tmp/restic/FILESNEW02/Dir01] at 2016-07-26 14:14:43.208840145 +0300 EEST> to /tmp/restic/RESTORE/`

Checking if directories/files exists
- **ls /tmp/restic/RESTORE/**
  `Dir01`
- **cat /tmp/restic/RESTORE/Dir01/Test0***
  `Content file. /tmp/restic/FILES01/Dir01/Test01.txt`
  `Content file. /tmp/restic/FILES01/Dir01/Test02.txt`
  `Content file. /tmp/restic/FILES01/Dir01/Test03.txt`

### PR DESCRIPTION
**Pull request by fd0**
### What is the purpose of this change? What does it change?

The commits in this PR replace the current archiver code with a rewritten, newly implemented archiver. The archiver is the part of restic which traverses the files and dirs, saves them to the repo and create snapshots. This is my WIP code, do not use it.

### Was the change discussed in an issue or in the forum before?

Closes #549, #1286, #446, #1344, #1416, #1456, #1145, #1160

### TODO

- [x] Add new archiver code
  - [x] Excludes
  - [x] Concurrency
  - [x] Progress reporting
  - [x] Abstract file system, allow reading from stdin with the same archiver code
  - [x] Don't save `atime` by default
  - [x] Upload intermediate indexes
  - [x] UI polishing
  - [x] Duration estimate
  - [x] Display summary at the end of the backup run
- [x] Remove old archiver code
- [x] Remove other unused code
      * `internal/pipe`
      * `internal/walk`

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's an entry in the `CHANGELOG.md` file that describe the changes for our users
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
To everyone subscribed to this PR: Work is ongoing and I think I'm almost finished.

**Comment by mholt** [comment]
Wow, this looks cool. Forgive my naivety -- is this change backwards-compatible with existing repositories?

**Comment by fd0** [comment]
> Forgive my naivety -- is this change backwards-compatible with existing repositories?

Yes, the repo format that the new archiver code is completely backwards compatible. The only thing that may change (due to #549 being resolved) is the directory structure within newly created snapshots. In addition, the first backup with the new archiver code will probably re-read all data, depending on how the directory structure is.

For example, running `restic backup work` may create a snapshot with a file `/work/todo.txt`. The new archiver will create the same structure in this case.

But for `restic backup /home/user/work`, the old code creates `/work/todo.txt`, and the new code will create `/home/user/work/todo.txt`.

I hope this is understandable ;)

That should be the only thing which changes.

**Comment by mholt** [comment]
Thanks for the explanation!

**Comment by mlissner** [comment]
> but also faster

Any idea how much faster and whether this might address the high memory usage problems?

**Comment by fd0** [comment]
> Any idea how much faster

Nope, time will tell. We need to test the code in real-world scenarios.

> and whether this might address the high memory usage problems?

Probably a bit, but I don't have any numbers yet :)

**Comment by lwis** [comment]
Did some brief real world testing as I was interested.

Fresh backups;

Scanning appears to be significantly faster for me on macOS

0.8.3 - scanned 34666 directories, 253479 files in 0:16
new-archiver - scan done in 8.12136426s, final result: 253479 files, 34666 dirs, 20.460 GiB bytes

Uploading

0.8.3 - 2:35
new-archiver - 2:40

Total times for fresh backup

0.8.3 - 2:53
new-archiver - 2:48

Incremental

0.8.3 - 0:29
new-archiver - 0:43

Scan times were the same (0:11) but for some reason the new-archiver took longer to check the diff.

Some things you may already be aware of;

- When uploading a large file the progress does not change on the display.
- GiB bytes?
- new-archiver appears to be slightly larger (11,907,099,737 bytes (11.91 GB on disk) for 2,596 items vs 11,898,720,698 bytes (11.9 GB on disk) for 2,586 items)

Obviously this is all anecdotal as there are a ton of variables at play and it's one test.

Great work on this @fd0, opens restic up to a much better future.

**Comment by stevesbrain** [comment]
I tested on a small repo, backing up to a local SSD:

**Current version** (excuse the working directory):
```bash
:: [stephen@waddleduck] ~/projects/restic [git:new-archiver]
$ ./restic -r ~/tmp/new-archive init
enter password for new repository:
enter password again:
created restic repository 6d01cd3dd5 at /home/stephen/tmp/new-archive

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

# Initial backup
:: [stephen@waddleduck] ~/projects/restic [git:new-archiver]
$ time ./restic -r ~/tmp/new-archive backup ~/Videos
enter password for repository:
password is correct
scan done in 2.454596ms, final result: 22 files, 1 dirs, 4.448 GiB bytes
snapshot 6829893d saved
added 4.448 GiB data and 305.438 KiB metadata in 22 files and 3 dirs
./restic -r ~/tmp/new-archive backup ~/Videos  94.62s user 11.16s system 287% cpu 36.852 total

# Incremental
:: [stephen@waddleduck] ~/projects/restic [git:new-archiver]
$ time ./restic -r ~/tmp/new-archive backup ~/Videos
enter password for repository:
password is correct
using parent snapshot 6829893d
scan done in 226.943µs, final result: 22 files, 1 dirs, 4.448 GiB bytes
snapshot 646b2065 saved
added 0B data and 0B metadata in 22 files and 3 dirs
./restic -r ~/tmp/new-archive backup ~/Videos  0.59s user 0.02s system 19% cpu 3.122 total
```

**Comment by rolfn** [comment]
Hello Alexander,
I tested today the new archiver code with an existing repository created with restic from the master branch. The snapshot was created with
```
restic backup /opt/gitlab /etc/gitlab
```
with the warning
```
/etc: name collision for "gitlab", renaming to "gitlab-1"
```
The destination is a server accessible via webdav (gmx mediacenter) with rclone. After installing an updated version of restic (branch "new-archiver", commit "9276a7590f07359da518fcf4d9f022643f6a7e3d") I tried to create a new snapshot without success. The program only shows
```
password is correct
```
and nothing else happens (waiting more than 30 minutes). If helpful I can do some more tests.

...Rolf

**Comment by fd0** [comment]
The master branch does not contain this PR (and therefore the new archiver code) yet, so switching to the branch `new-archiver` was indeed correct. I'm not sure the code was in a testable state yet, I'm still working on it.

Please have a bit more patience :)

**Comment by fd0** [comment]
I'm done, I'll merge this when the CI tests pass :)

**Comment by fd0** [comment]
And it's in! Wohoo! Four months of work :)

**Comment by whereisaaron** [comment]
Now... about that #21 compression @fd0 :smile:

**Comment by onionjake** [comment]
Not sure if this is outside the scope of the work going on here, but go 1.16 has a new Filesystem interface abstraction.

It might be useful for restic to use the `fs.FS` interface in the archiver code because it would be easy for someone to provide another implementation that would make it easier to restic to backup files from other sources... Say http apis, etc.

As part of that then you could also leverage the`testing/fstest` package which might simplify testing.

**Pull request merged**
