### PR TITLE
Ls ncdu

### PR DESCRIPTION
**Pull request by ndecker**
What does this PR change? What problem does it solve?
-----------------------------------------------------
NCDU (NCurses Disk Usage) is a tool to analyse disk usage of directories.
It has an option to save a directory tree and analyse it later.
This patch adds an output option to the ls command for the NCDU format.

Use `restic ls latest --ncdu | ncdu -f -`

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
no

Created issue: #4549

Checklist
---------

- [X] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [X] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [X] I have run `gofmt` on the code in all commits.
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [X] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by jvandenbroek** [comment]
I am intrigued by this patch, so had to try it out ;-) But when a snapshot contains multiple paths it doesn't work correctly and specifying a specific path results in the following error:

```
panic: cannot find suitable parent directory

goroutine 1 [running]:
main.lsNodeNcdu({0x137a120, 0xc00007c030}, 0xc0000f57d0, 0xc0000f5840, {0xc00636cc30, 0xb}, 0xc00636f7c0)
        github.com/restic/restic/cmd/restic/cmd_ls.go:175 +0x505
main.runLs.func6({0xc00636cc30?, 0xb?}, 0xc0005e8720?)
        github.com/restic/restic/cmd/restic/cmd_ls.go:293 +0x45
main.runLs.func9({0x34, 0xc5, 0xfb, 0x92, 0x0, 0x0, 0x15, 0x62, 0x14, 0x5, ...}, ...)
        github.com/restic/restic/cmd/restic/cmd_ls.go:331 +0x90
github.com/restic/restic/internal/walker.walk({0x1387d28, 0xc0000ad5e0}, {0x137a200, 0xc0004b8410}, {0xc00636caa0, 0x4}, {0x34, 0xc5, 0xfb, 0x92, ...}, ...)
        github.com/restic/restic/internal/walker/walker.go:103 +0x2e7
github.com/restic/restic/internal/walker.walk({0x1387d28, 0xc0000ad5e0}, {0x137a200, 0xc0004b8410}, {0x1372ab0, 0x1}, {0x3b, 0xd6, 0x76, 0xc2, ...}, ...)
        github.com/restic/restic/internal/walker/walker.go:122 +0x467
github.com/restic/restic/internal/walker.Walk({0x1387d28, 0xc0000ad5e0}, {0x137a200, 0xc0004b8410}, {0x3b, 0xd6, 0x76, 0xc2, 0x41, 0x28, ...}, ...)
        github.com/restic/restic/internal/walker/walker.go:51 +0x1ef
main.runLs({_, _}, {0x0, {{}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
        github.com/restic/restic/cmd/restic/cmd_ls.go:321 +0x78d
main.glob..func15(0xc00019b500?, {0xc0003e9340?, 0x4?, 0x11afcb5?})
        github.com/restic/restic/cmd/restic/cmd_ls.go:47 +0x87
github.com/spf13/cobra.(*Command).execute(0x1b49f00, {0xc0003e92d0, 0x7, 0x7})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0x1b4e6e0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/restic/restic/cmd/restic/main.go:109 +0x1a5
Error importing file on line 2:2: expected ','.
```

**Comment by MichaelEischer** [comment]
I've extended the `walker` to also inform about leaving a directory. This allows significantly simplifying the JSON printing code. The different output formats are now also abstracted using a common interface such that no more workarounds are necessary to print the NCDU json.

@jvandenbroek The code should now also work when specifying a path.

remaining TODOs:
- [ ] add tests for walker.LeaveDir
- [ ] add documentation

**Review by MichaelEischer — APPROVED** [review]
LGTM.

**Comment by skywinder** [comment]
so cool feature, thanks! will it be released in next version?

**Comment by MichaelEischer** [comment]
Yes it will be part of restic 0.17, but that will still take a few months until it will be released. Until then you can use a beta release from https://beta.restic.net/?sort=time&order=desc .

**Comment by akrabu** [comment]
@MichaelEischer When testing this with snapshots of multiple paths, it seems to only pass the first folder to `NCDU` - unless I'm doing something wrong?  I see @jvandenbroek mentioned this already.  Is the answer that only the first path is supported, and if you want another path you must specify it - or will it be possible to have it consider all paths by default eventually?

**Comment by MichaelEischer** [comment]
@akrabu In theory multiple paths should work just fine. I've fixed the crash and had hoped that multiple paths work. But apparently there's something broken, see #4910.

**Pull request merged**
