### PR TITLE
Added security note for passing pw via env variable

### PR DESCRIPTION
**Pull request by JsBergbau**
What does this PR change? What problem does it solve?
-----------------------------------------------------
It adds a security note that environment variables can be seen by other processes running as the same user as restic does.

It is only a small documentation update. Feel free to change the wording. 
I was aware that passwords via commandline are unsafe because they can be read by other processes easily and thats why I used environment variables. But these aren't so secure as thought. So I've created this pull request.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
No.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
> I was aware that passwords via commandline are unsafe because they can be read by other processes easily and thats why I used environment variables.

The problem with passing the password via the command line is that _any_ user on the system can read the command line and thus the password is leaked. When passing the password via environment variables, then only the current user can extract it. As the standard security boundaries in unix only separate users from each other but not processes of the same user, that is not really unexpected. The most obvious problem with environment variables is that these are passed on to subprocesses if any are launched by restic.

When stating that something is supposed to be insecure, it is a good idea to suggest a better solution. `restic -p password_file` won't help here, as some other process executing as the current user could just read the password file as well. `restic --password-command "get-pass restic"` could help when running it interactively, but for an automated backup there's nothing preventing something else to call `get-pass restic`.

That is, I currently don't understand where precisely the security benefit would be.

**Comment by rawtaz** [comment]
There's also the aspect that the restic documentation cannot be expected to document every security aspect people should know about - it's outside of its concerns. Some things we can add as an extra precaution, but how a Linux or similar system works is simply out of scope.

In this case as Michael said the security separation is the user, which already has access to the information needed to start restic anyway. So it's rather moot in its entirety. I'm inclined that we close this without merging. Good point with the "suggesting a better solution".

**Comment by JsBergbau** [comment]
You're right, the user that is running restic backup can also access the password when supplied via `RESTIC_PASSWORD_FILE`. 

Suppose debug logs of other processes that contain all processes including their environment variables. I don't know how much other software is around that includes environment variables of all processes but still for me it feels more safe to supply password from a password file than via environment variable.

**Comment by rawtaz** [comment]
I'll close this then :)

**Comment by JsBergbau** [comment]
Just for the record. With ProcessHacker https://processhacker.sourceforge.io/ it is possible to view environment variables of the processes like `cat /proc/`pidof restic`/environ`` does in linux.

**Pull request closed without merging**
