### PR TITLE
Fix links to manual

### PR DESCRIPTION
**Pull request by tyll**

### CODE REVIEW

**Review by fd0 — APPROVED** [review]
Need another PR for hacktoberfest? ;)

Thanks!

**Comment by tyll** [comment]
You can never have enough PRs :-)

**Comment by tyll** [comment]
I do not understand why this commit changes anything in the coder coverage...

**Comment by fd0** [comment]
Don't worry about that: We're running tests for the various backends against live systems, and the required credentials aren't exposed to third-party PRs (not from the restic repo), so the tests don't run for those PRs.

**Pull request merged**
