### PR TITLE
Improve stats

### LINKED ISSUE #3779: Total Size in stats is not correct when backup is compressed
Output of `restic version`
--------------------------
```
./restic2 version
restic 0.13.1-dev (compiled manually) compiled with go1.18 on linux/amd64
```

I have built current master with compression support.

How did you run restic exactly?
-------------------------------

`./restic2 --verbose -r /mnt/restic/repo2/ stats --mode raw-data`

```
enter password for repository:
repository 193651e2 opened (repo version 2) successfully, password is correct
scanning...
Stats in raw-data mode:
Snapshots processed:   1
   Total Blob Count:   97646
         Total Size:   174.626 GiB
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

local dir

Expected behavior
-----------------

After backup with compression, i can see actual size which is smaller then in 'stats' output:

```
du -sh /mnt/restic/repo2
99G	/mnt/restic/repo2
```

Steps to reproduce the behavior
-------------------------------

Backup something with compression and check 'stats' in 'raw-data' mode.

### PR DESCRIPTION
**Pull request by fd0**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Print the number of bytes added to the repo (including optional compression and the crypto overhead).

Checklist
---------

- [x] Add real size to the `stats` command
- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
The code looks fine. But currently "SizeInRepo" feels a bit misleading. It will systematically underreport how much data was added to the repository, as the pack header overhead is missing. My suggestion would be to either immediately report the pack entry header size along with the blob length or to report that overhead together with the blob that triggers a pack file upload. The downside of the second variant is that it would either require modifications to `repo.Flush()` or not account for the last few pack headers.

**Comment by fd0** [comment]
Ah, right. I'm in favor of the second option, even if that's not exact and will not report the last few header sizes. Since the header size will depend on the repo version I think it's less complex this way.

**Comment by MichaelEischer** [comment]
I've implemented a mix of both variants. We already have a method to calculate the size of the pack header entry for a given blob, which make accounting for the per blob overhead a one-line change. When finalizing a pack file, now the pack header crypto overhead is reported and added for the last blob. 

Adding the pack header entry overhead for each blob individually also has the benefit that the "stored size" for each file won't have large random spikes due to charging the full pack overhead to a single blob.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Let's merge this now and wait for feedback whether the stats need further improvements.

**Pull request merged**
