### PR TITLE
Add backend support for Google Cloud Storage.

### PR DESCRIPTION
**Pull request by kurin**

### CODE REVIEW

**Comment by fd0** [comment]
This is expected to fail, the dependencies are not included in the PR (see #302)

**Comment by fw42** [comment]
That's why I asked this to be PRed against the other branch, not against master :-/ Then it wouldn't fail...

**Comment by fd0** [comment]
Yeah, but then we'd still see the commit adding the dependecies and GitHub won't show the diff.

**Comment by fw42** [comment]
nope you wouldn't

**Comment by fw42** [comment]
The GitHub PR UI shows the diff between your branch and the branch the PR is made against... So if you PR against a branch that already has the dependencies (and this branch has it as well), then you only see what you see here right now (but the tests will work).

**Comment by fd0** [comment]
Interesting, I'll talk to @kurin.

**Comment by fd0** [comment]
Done, let's see.

**Comment by fd0** [comment]
For me, it still shows `370 changed files`...

**Comment by fd0** [comment]
@kurin Just a quick reminder: Thank you for your contribution, I haven't forgotten about it. I'll have a look as soon as I have time, probably over the holidays :)

**Comment by kurin** [comment]
FYI, the Google storage library has changed significantly since this CL was opened.  If you want to keep in sync, more work will have to be done.

**Comment by fd0** [comment]
Ok, good to know.

**Comment by abourget** [comment]
Keep up the good work folks :) Anything I could help with ?

**Comment by fd0** [comment]
Maybe you could have a look at the API changes and forward-port the code in this PR.

Is there a way to get easy access for me to Nearline storage to test this code?

**Comment by kardianos** [comment]
@fd0 google cloud offers a free trial you could use as a test for initial merging: https://cloud.google.com/free-trial/

**Comment by broady** [comment]
https://github.com/GoogleCloudPlatform/gcloud-golang/wiki/Storage-Package-Update

**Comment by fd0** [comment]
@broady thanks, I'll have a look.

**Comment by kurin** [comment]
Just FYI I actually have a CL open with the cloud storage package to provide a LimitedReader, which means you can read from part of an object without downloading the rest of it, which would be nice.

Once I get that in I can revisit this, if you want, or if you have a better way to approach this (without adding all of GCS to the dependencies) I could look at that.  My personal backup strategies have moved from restic to zfs, so I no longer really need to push this though, but I'm happy to see it in if anyone else has a need.

**Comment by mappu** [comment]
> The Google Cloud Storage XML API is interoperable with some cloud storage tools and libraries that work with services such as Amazon Simple Storage Service (Amazon S3) 

So `restic` can already back up to Google Cloud Storage using existing minio backend. Am I wrong? or what does this patch add?

**Comment by fd0** [comment]
@mappu This PR was opened way before we switched to minio, I'll close it for now.

**Pull request closed without merging**
