### PR TITLE
Fix ls command

### PR DESCRIPTION
**Pull request by howeyc**
Added missing loadindex call. Also fixed the recursive call to
use the subtree to stop infinte recursion.

### CODE REVIEW

**Comment by fw42** [comment]
hu interesting. good catch. @fd0 we should have a regression test for this.

**Comment by fd0** [comment]
Agreed, I'll ad one this evening.

**Comment by fd0** [comment]
Merged, thanks for your contribution!

**Comment by fd0** [comment]
Test was added in c86474663c16cd2fd6b2b88db700682c64e89e53

**Pull request merged**
