### PR TITLE
Added long paths fix for samba network shares

### PR DESCRIPTION
**Pull request by hmsdao**
Also check if long paths expression is already included in paths.

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for your contribution! I just have one (minor) request, then this can be merged!

**Review by fd0 — CHANGES_REQUESTED** [review]
Please use backticks instead of double quotes to delimit the strings with backslashes, this way the code remains readable. Backticks are used to delimit raw strrings and the backslash character is a normal character thath doesn't need escaping. Example here: https://play.golang.org/p/iXD-ow_xqa

**Comment by hmsdao** [comment]
Am I suppose to do any more work on this PR?

**Review by fd0 — APPROVED** [review]

**Comment by fd0** [comment]
Nop, looks fine, thanks!

**Pull request merged**
