### PR TITLE
doc: reading from CIFS can be a problem on linux

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
See https://github.com/restic/restic/issues/2659#issuecomment-1349661280 .

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- ~~[ ] I have added tests for all code changes.~~
- [x] I have added documentation for relevant changes (in the manual).
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).~~
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by greatroar** [comment]
Is this still a problem with the most recent builds of restic? I thought the newer Go versions had EINTR loops around all the relevant syscalls.

**Comment by MichaelEischer** [comment]
> Is this still a problem with the most recent builds of restic? I thought the newer Go versions had EINTR loops around all the relevant syscalls.

That part should definitely be fixed by now.

What worries me are cases like https://github.com/restic/restic/issues/2659#issuecomment-792313543 where some files nevertheless turned out to be broken. The latter cases rather appear to be bugs in the CIFS implementation in Linux and thus are highly dependent on the used kernel version. But we have no way to assess whether that is still a problem or not.

**Comment by greatroar** [comment]
LGTM, then.

**Comment by MichaelEischer** [comment]
LGTM. After talking to @rawtaz I've added a remark that this affects older Linux kernels (whatever the exact version range might be).

**Pull request merged**
