### PR TITLE
changelog: Add .gitkeep to persist unreleased/ folder

### LINKED ISSUE #2485: Folder changelog/unreleased/ doesn't exist when empty
When here are no pending changeling entries in the unreleased/ folder, the folder isn't tracked by git anymore. Add a .gitkeep file to the changelog/unreleased/ folder in order to make the folder always exist. This makes it less confusing for new contributors when the contributing instructions reference this folder.

### PR DESCRIPTION
**Pull request by rawtaz**
What is the purpose of this change? What does it change?
--------------------------------------------------------

It adds a .gitkeep file (conventional name, everyone and their two cats does it) to the changeling/unreleased/ folder so that it is still tracked and kept around when it's empty.

Previously when there were no pending changeling files in this folder, it wasn't tracked by Git, which could be confusing to new contributors considering the folder is referenced by the contributing instructions.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes #2485.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
Two things:
 * We need to make sure the empty file is created again
 * We need to teach `calens` to ignore files starting with a dot

**Comment by rawtaz** [comment]
Can you teach calens to ignore files starting with dot and to only move the *files* in the `unreleased` folder, instead of the folder itself?

**Comment by fd0** [comment]
Ah, that's done manually, like `mv changelog/unreleased changelog/v1.0.0`, but maybe it's a good idea to let `calens` do that. But first, I'll build ignoring dot-prefix files.

**Review by fd0 — APPROVED** [review]
LGTM, calens is fixed

**Pull request merged**
