### PR TITLE
PR dead: issue 4278: Enhancement: include filters in command rewrite - see newer PR #5191 

### PR DESCRIPTION
**Pull request by wplapper**
Enhancement: include filters in command rewrite

What does this PR change? What problem does it solve?
-----------------------------------------------------
https://github.com/restic/restic/issues/4278 

The enhancement allows the standard include filter options. 

In order to make the include filter work efficiently, an additional read pass through the directory tree is needed to identify the sub-directories and their parents for the inclusion of files. Otherwise the full directory tree needs to be included which as a consequence may contain quite a lot of empty sub-directories. The additional read pass avoids this issue, but it might take a bit more time, depending on the network speed of the back-end storage and the size of the snapshot.

File internal/filter/include.go gained an "Empty() function, and file internal/walker/rewriter.go gained two additional fields 
TreeBlobs and DataBlobs. 

File cmd/restic/cmd_rewrite.go gained the additional logic of handling the include filters and the very first pass through
the snapshot to detect the necessary directory structure to support the inclusion of files. 

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
https://github.com/restic/restic/issues/4278

Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [X] I'm done! This pull request is ready for review.

### CODE REVIEW

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Thanks for working on include filters! I've only partially reviewed the code so far as I ran into a major conceptual problem with the implementation of the `--exclude-empty` option. `directoriesNeeded` is a rather complex and slow workaround for missing functionality in `TreeRewriter.RewriteTree`.

The problem that `directoriesNeeded` tries to work around is that directories that are not included still remain in the snapshot but are empty. The clean solution would be to extend the `TreeRewriter` options with a new `KeepEmtpyDirectory func(path string) bool` field. If it is unset, then the rewriter behaves like before. If the field is set and the filtered tree is empty then `KeepEmtpyDirectory` decides whether to keep the tree or not. If the tree should not be kept, then `RewriteTree` returns an empty restic.ID which also means that the corresponding node should be dropped.

That way the filtering of empty directories happens directly within the `TreeRewriter` without _any_ additional overhead. This also obsoletes the `--exclude-empty` option.

[Edit]Some of the comments below are obsolete when replacing `directoriesNeeded`. I've nevertheless kept them as they are still relevant from a code style perspective[/Edit]

**Comment by wplapper** [comment]
Will work on https://github.com/restic/restic/pull/5185 first. Once this PR is on its way, I will tackle this PR. Thanks for reviewing.

**Comment by wplapper** [comment]
@MichaelEischer: Thank you for commenting on the issue of empty directories. You wrote 
"The problem that directoriesNeeded tries to work around is that directories that are not included still remain in the snapshot but are empty. The clean solution would be to extend the TreeRewriter options with a new KeepEmtpyDirectory func(path string) bool field. If it is unset, then the rewriter behaves like before. If the field is set and the filtered tree is empty then KeepEmtpyDirectory decides whether to keep the tree or not. If the tree should not be kept, then RewriteTree returns an empty restic.ID which also means that the corresponding node should be dropped.
". I have a problem understanding your comment. Since RewriteTree is a strictly top down process and one needs to know the parent line of a particular sub directory structure (parent, grandparent, ... up to the top of the tree), one has to decide quite early in the tree walk whether or not to keep/drop this subtree. 

I will give an example: My snapshot I want to rewrite contain some Python files (*.py) which I am interested in. I am looking for all *.py files inside a certain subdirectory "peterNorvig", and below. So the chosen filter is '-i "peterNorvig/**/*.py"'.
The partial snapshot listing of the filtered output is:
/home
/home/wplapper
/home/wplapper/sudoku
/home/wplapper/sudoku/peterNorvig
/home/wplapper/sudoku/peterNorvig/PN-solve_LSA_puzzle.py
...
/home/wplapper/sudoku/peterNorvig/PN_cython
/home/wplapper/sudoku/peterNorvig/PN_cython/PN_sudoku_setup.py'
...

TreeRewriter, has to include tree nodes /, /home, /home/wlapper, /home/wlapper/sudoku and /home/wlapper/sudoku/PN_cython/ before it can include the wanted *.py files. My question is: how does TreeRewriter knows this in advance, unless this has been found out before? Please correct me if my thoughts are wrong.
PS.: Only the wanted sub directories need to be stored in 'directoriesNeeded', not all of them. This can be amended easily.

**Comment by wplapper** [comment]
I have cracked the issue of including empty sub directories when using include filters: when a sub directory is empty, the resulting byte string from calling tb.Finalize() is `{"nodes":[]}` + "\n". Comparing with this constant 

> suppresses the creation of empty subtrees
> removes them in the parent directory of being listed

**Comment by rawtaz** [comment]
@wplapper I think you accidentally closed the PR =D

**Comment by wplapper** [comment]
Yes I know, but I have created a new one with the "old" contents.

**Comment by rawtaz** [comment]
There is no need to close one PR and open a second PR about the same thing and even with the same title :) Let's have a chat about that at some point, if you want help with the Git/GitHub stuff here!

**Comment by wplapper** [comment]
Yes, I am pretty blind when it comes to Git / Github. I have made too many
mistakes with git and I do not know how to revert them, particularly when
the commits have been pushed to github.

Merry Christmas and thanks for the generous offer,

Winfried

**Comment by wplapper** [comment]
@rawtaz: how can I get in contact with you? I am working on #4585 and I want to cleanly shutdown the backup process. Thanks Winfried

**Pull request closed without merging**
