### PR TITLE
Prune speedup

### LINKED ISSUE #2162: handle large prune much more efficent
Output of `restic version`
--------------------------

restic 0.9.3 compiled with go1.10.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

In general, I like restic very much, and creating/recovery snapshots works perfectly fine.
But run restic with large repository’s is almost impossible. I have a repository with 5 TB / 30 snapshots.
Intention was to do this like a circular buffer (remove oldest, add newest). 

Adding a snapshot and removing them works perfect, but as you necessarily come to prune your repository it can take WEEKS to just free 1 TB (because of rewrite).
This makes it almost impossible to use restic anymore as you can't create new snapshots during that time.

As you mentioned already [here](https://github.com/restic/restic/issues/725#issuecomment-277277794)
you may do something to improve this.

Example: 
found 5967884 of 7336415 data blobs still in use, removing 1368531 blobs
will delete 144850 packs and rewrite 142751 packs, this frees 1.082 TiB (took 2 weeks!)

Especially on remote repository’s where you just bought storage (with ssh access) and CPU resources are limited its much faster upload the whole repository again.

### LINKED ISSUE #2227: Prune should either disregard repository indexes, or not rebuild indexes twice
Output of `restic version`
--------------------------
```
restic 0.9.4 compiled with go1.11.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
restic -r . prune
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local, though this does not appear to matter.

Expected behavior
-----------------
Prune completes successfully.

Actual behavior
---------------
Prune rebuilds the repository indexes in-memory but then appears to ignore these indexes, and tries to load the (missing) files from disk.  When it gets to the garbage-collection phase, it therefore can't find any objects in the repository and fails.  For example:

```
$ restic -r . prune
enter password for repository:
repository 26b51fe2 opened successfully, password is correct
counting files in repo
building new index for repo
[0:00] 100.00%  67 / 67 packs
repository contains 67 packs (4773 blobs) with 316.143 MiB
processed 4773 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 1 snapshots
tree 30649e56256d8418cd8b4f0c85f6ed048f6c4d04aa31e1fd28602df9956f125a not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadTree
        /restic/internal/repository/repository.go:653
github.com/restic/restic/internal/restic.FindUsedBlobs
        /restic/internal/restic/find.go:11
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:191
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func18
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
```

Running `restic rebuild-index` first makes prune succeed:

```
$ restic -r . rebuild-index
enter password for repository:
repository 26b51fe2 opened successfully, password is correct
counting files in repo
[0:00] 100.00%  67 / 67 packs
finding old index files
saved new indexes as [a13538cc]
remove 0 old index files

$ restic -r . prune
enter password for repository:
repository 26b51fe2 opened successfully, password is correct
counting files in repo
building new index for repo
[0:00] 100.00%  67 / 67 packs
repository contains 67 packs (4773 blobs) with 316.143 MiB
processed 4773 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 1 snapshots
[0:00] 100.00%  1 / 1 snapshots
found 4773 of 4773 data blobs still in use, removing 0 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 0 packs, this frees 0 B
counting files in repo
[0:00] 100.00%  67 / 67 packs
finding old index files
saved new indexes as [e13b3d29]
remove 1 old index files
done
```

I would suggest that restic should either use the indexes it generated instead of the repository indexes, or not generate the indexes that it does not appear to use.

Steps to reproduce the behavior
-------------------------------
1. Create a repository.
2. Run a backup to create a snapshot.
3. Delete all of the files in the repository `index` directory.
4. Run `restic prune`.

### PR DESCRIPTION
**Pull request by cbane**
What is the purpose of this change? What does it change?
--------------------------------------------------------

This makes pruning large repositories (especially when stored on a remote backend) much faster. It will use the existing index if it can (instead of building a new one from scratch), and it keeps track of changes to the repository to save a new index at the end. It also parallelizes slow operations, including scanning snapshots for used blobs, rewriting partially used packs, and deleting unused packs. As a side effect of the index related changes, it also handles missing index files.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

closes #2162 
closes #2227 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by thiell** [comment]
Hello, 


With the master branch or restic, the prune operation on a local test repo takes about 4 days to complete, so I was looking for ways to improve the speed.

I tried your branch on a local repo but unfortunately I get the following error:
```
$ restic forget --keep-daily 3
repository 99ac5daf opened successfully, password is correct
Applying Policy: keep the last 3 daily snapshots
keep 3 snapshots:
ID        Time                 Host        Tags        Reasons         Paths
---------------------------------------------------------------------------------------------------
59dbdd61  2019-08-01 16:29:46  oak-io4-s1              daily snapshot  /oak/stanford/groups/abc
be784ca8  2019-08-02 14:39:10  oak-io4-s1              daily snapshot  /oak/stanford/groups/abc
a75116a2  2019-08-08 18:38:20  oak-io4-s1              daily snapshot  /oak/stanford/groups/abc
---------------------------------------------------------------------------------------------------
3 snapshots

remove 1 snapshots:
ID        Time                 Host        Tags        Paths
-----------------------------------------------------------------------------------
81f197d5  2019-07-29 11:35:39  oak-io4-s1              /oak/stanford/groups/abc
-----------------------------------------------------------------------------------
1 snapshots

$ restic snapshots
repository 99ac5daf opened successfully, password is correct
ID        Time                 Host        Tags        Paths
-----------------------------------------------------------------------------------
59dbdd61  2019-08-01 16:29:46  oak-io4-s1              /oak/stanford/groups/abc
be784ca8  2019-08-02 14:39:10  oak-io4-s1              /oak/stanford/groups/abc
a75116a2  2019-08-08 18:38:20  oak-io4-s1              /oak/stanford/groups/abc
-----------------------------------------------------------------------------------
3 snapshots
$ ./prune-speedup/restic/restic prune
repository 99ac5daf opened successfully, password is correct
listing files in repo
loading index for repo
[2:36] 100.00%  5071 / 5071 index files
checking for packs not in index
repository contains 15760889 packs (58210748 blobs) with 79.157 TiB
processed 58210748 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 3 snapshots
[2:51] 100.00%  3 / 3 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

real    123m48.016s
user    18m4.746s
sys     6m28.770s
```

**Comment by moritzdietz** [comment]
Hi @thiell I think this is unrelated to this change. See https://forum.restic.net/t/fatal-number-of-used-blobs-is-larger-than-number-available-blobs/1143 for this. Or in general a [search](https://forum.restic.net/search?q=Fatal%3A%20number%20of%20used%20blobs%20is%20larger%20than%20number%20of%20available%20blobs!) in the forum.

**Comment by thiell** [comment]
Ah, thanks @moritzdietz! I'll have a look.

**Comment by aawsome** [comment]
Thank you very much for proposing this PR! I think an improvement of prune is very important and we need to take into account as many ideas as possible!
I'd tried do a code review, but honestly this change is too big for me to inspect the changes.

Maybe your good ideas should be separated in different PRs?
I could imagine that a separate PR to use the existing index in combination with the open PR #1994 should be able to already relax the prune speed issue a lot.

Adding parallel operations is of course a good thing but IMO really hard to review/debug and I don't know if the core developers have enough time for this issue ATM :smirk:

**Comment by fd0** [comment]
Closing, superseded by #2718 and #2941. Please feel free to add further comments!

**Pull request closed without merging**
