### PR TITLE
Add note about pre-compiled binaries

### LINKED ISSUE #755: golang is a dev requirement not a user one
README.md and Manual.md explains that golang is required to use restic, it may look a bit scary to add this dependency if you just want to try out restic.

A simpler way to install restic is just to download it...

```sh
curl --location https://github.com/restic/restic/releases/download/v0.3.3/restic_linux_amd64.bz2 | bunzip2 > /usr/local/bin/restic
chmod +x /usr/local/bin/restic
```

I think this download explanation should be part of README.md to have more people using it.

### PR DESCRIPTION
**Pull request by brikou**
Fixes #755

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for giving this a try! Could you please add the paragraph about building restic from source back into the README file, maybe below the new section about the pre-compiled binaries? That'd be great :)

**Review by fd0 — CHANGES_REQUESTED** [review]
Thanks for giving this a try! Could you please add the paragraph about building restic from source back into the README file, maybe below the new section about the pre-compiled binaries? That'd be great :)

**Comment by brikou** [comment]
@fd0 done

**Review by fd0 — APPROVED** [review]

**Comment by fd0** [comment]
Great, thanks!

**Comment by fd0** [comment]
(I cancelled the Travis build, this is just a change of documentation)

**Pull request merged**
