### PR TITLE
[#issue 3127] Add xattr support for Solaris

### LINKED ISSUE #3127: Add xattr support for Solaris/SmartOS
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic currently does not support xattrs for solaris.

See #1645 for the patch that added initial solaris support.

The xattr API for solaris is documented here: https://illumos.org/man/5/fsattr. See the `Using the API` section.

### PR DESCRIPTION
**Pull request by gautammenghani**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Fixes #3127 

Added build tag for solaris and removed redundant functions in node_solaris.go. Also added example command in documentation.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
The change itself looks fine. Please add a short changelog entry.

Are you using Solaris and can test the PR? Or can someone else help with that?

**Comment by gum3ng** [comment]
I've added the changelog. I do not have Solaris to test this. It would be great if somebody having solaris can test this.

**Comment by gco** [comment]
Same results as last time I tried this, the xattr internals does something nasty with file descriptors.   This is on Solaris(tm).

A short excerpt from a very long log filled with similar errors:
```
build: running tests
build: environment (GO*):
build:   GOARCH=amd64
build:   GOARM=
build:   GO111MODULE=on
build:   GOOS=solaris
build: chdir "/pool/projects/restic"
build: go ["test" "-count" "1" "./..."]
?       github.com/restic/restic        [no test files]
could not read signature from exclusion tagfile "/tmp/restic-test-1687343194/CACHEDIR.TAG": unexpected EOF
integration_test.go:88: Error while backing up

helpers.go:192: unexpected error: unlinkat /tmp/restic-test-2481435712: bad file number

--- FAIL: TestBackup (0.31s)
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    lock.go:82: setting lock timeout to 0s
    integration_test.go:56: repository initialized at /tmp/restic-test-2481435712/repo
    integration_test.go:68: backing up [testdata] in /tmp/restic-test-2481435712
    integration_test.go:70: chdir to /tmp/restic-test-2481435712
    integration_test.go:83: chdir back to /pool/projects/restic/cmd/restic
integration_test.go:88: Error while backing up

--- FAIL: TestDryRunBackup (0.04s)
...
...
    integration_test.go:68: backing up [/tmp/restic-test-187746066/testdata/0/0/9] in
integration_test.go:88: Error while backing up

helpers.go:192: unexpected error: unlinkat /tmp/restic-test-1747024417: bad file number

--- FAIL: TestCopyIncremental (0.06s)
...
...
```

**Comment by MichaelEischer** [comment]
Thanks for testing. However, this means that this PR is stuck indefinitely until someone using Solaris can investigate what's going on.

**Comment by gco** [comment]
I'm new to go, but I suspect that the xattr implementation for Solaris is causing file descriptors to be closed twice.  Any fd passed to NewFile should be closed when NewFile is gc'd:

> Otherwise, during garbage collection the finalizer may close an unrelated file descriptor with the same (reused) number.

With these changes and some cleanup of the restic tests for Solaris quirks, all tests pass and I didn't see any signs of fd leaks examining the truss output.

```
--- xattr_solaris.go.orig       2022-01-24 22:28:35.689187773 -0800
+++ xattr_solaris.go    2022-01-24 23:16:40.587417004 -0800
@@ -27,9 +27,6 @@
        if err != nil {
                return 0, err
        }
-       defer func() {
-               _ = unix.Close(fd)
-       }()
        return fgetxattr(os.NewFile(uintptr(fd), path), name, data)
 }

@@ -53,11 +50,7 @@
        if err != nil {
                return err
        }
-       if err = fsetxattr(os.NewFile(uintptr(fd), path), name, data, flags); err != nil {
-               _ = unix.Close(fd)
-               return err
-       }
-       return unix.Close(fd)
+       return fsetxattr(os.NewFile(uintptr(fd), path), name, data, flags)
 }

 func lsetxattr(path string, name string, data []byte, flags int) error {
@@ -89,9 +82,6 @@
        if err != nil {
                return err
        }
-       defer func() {
-               _ = unix.Close(fd)
-       }()
        return fremovexattr(os.NewFile(uintptr(fd), path), name)
 }

@@ -115,9 +105,6 @@
        if err != nil {
                return 0, err
        }
-       defer func() {
-               _ = unix.Close(fd)
-       }()
        return flistxattr(os.NewFile(uintptr(fd), path), data)
 }

@@ -130,9 +117,6 @@
        if err != nil {
                return 0, err
        }
-       defer func() {
-               _ = unix.Close(fd)
-       }()
        names, err := os.NewFile(uintptr(fd), f.Name()).Readdirnames(-1)
        if err != nil {
                return 0, err
```


restic changes:

```
diff --git a/cmd/restic/integration_helpers_test.go b/cmd/restic/integration_helpers_test.go
index 1bbd41cb..df989335 100644
--- a/cmd/restic/integration_helpers_test.go
+++ b/cmd/restic/integration_helpers_test.go
@@ -67,7 +67,7 @@ func isSymlink(fi os.FileInfo) bool {

 func sameModTime(fi1, fi2 os.FileInfo) bool {
        switch runtime.GOOS {
-       case "darwin", "freebsd", "openbsd", "netbsd":
+       case "darwin", "freebsd", "openbsd", "netbsd", "solaris":
                if isSymlink(fi1) && isSymlink(fi2) {
                        return true
                }
diff --git a/internal/restic/node.go b/internal/restic/node.go
index cd237ac4..08a102ba 100644
--- a/internal/restic/node.go
+++ b/internal/restic/node.go
@@ -617,6 +617,9 @@ func (node *Node) fillExtendedAttributes(path string) error {
        if node.Type == "symlink" {
                return nil
        }
+       if runtime.GOOS == "solaris" && (node.Type == "dev" || node.Type == "chardev") {
+               return nil
+       }

        xattrs, err := Listxattr(path)
        debug.Log("fillExtendedAttributes(%v) %v %v", path, xattrs, err)
diff --git a/internal/restic/node_test.go b/internal/restic/node_test.go
index 5390a90a..65f71fa7 100644
--- a/internal/restic/node_test.go
+++ b/internal/restic/node_test.go
@@ -210,9 +210,9 @@ func TestNodeRestoreAt(t *testing.T) {
                                "%v: GID doesn't match (%v != %v)", test.Type, test.GID, n2.GID)
                        if test.Type != "symlink" {
                                // On OpenBSD only root can set sticky bit (see sticky(8)).
-                               if runtime.GOOS != "openbsd" && runtime.GOOS != "netbsd" && test.Name == "testSticky" {
+                               if runtime.GOOS != "openbsd" && runtime.GOOS != "netbsd" && runtime.GOOS != "solaris" && test.Name == "testSticky" {
                                        rtest.Assert(t, test.Mode == n2.Mode,
-                                               "%v: mode doesn't match (0%o != 0%o)", test.Type, test.Mode, n2.Mode)
+                                               "%v/%v: mode doesn't match (0%o != 0%o)", test.Name, test.Type, test.Mode, n2.Mode)
                                }
                        }
                }
@@ -228,7 +228,7 @@ func AssertFsTimeEqual(t *testing.T, label string, nodeType string, t1 time.Time
        // Go currently doesn't support setting timestamps of symbolic links on darwin and bsd
        if nodeType == "symlink" {
                switch runtime.GOOS {
-               case "darwin", "freebsd", "openbsd", "netbsd":
+               case "darwin", "freebsd", "openbsd", "netbsd", "solaris":
                        return
                }
        }
diff --git a/internal/restic/node_unix_test.go b/internal/restic/node_unix_test.go
index 0908d378..e5fbd034 100644
--- a/internal/restic/node_unix_test.go
+++ b/internal/restic/node_unix_test.go
@@ -93,9 +93,13 @@ func TestNodeFromFileInfo(t *testing.T) {

        // on darwin, users are not permitted to list the extended attributes of
        // /dev/null, therefore skip it.
-       if runtime.GOOS != "darwin" {
+       // on solaris, /dev entries are all symlinks
+       if runtime.GOOS != "darwin" && runtime.GOOS != "solaris" {
                tests = append(tests, Test{"/dev/null", true})
        }
+       if runtime.GOOS == "solaris" {
+               tests = append(tests, Test{"/devices/pseudo/mm@0:null", true})
+       }

        for _, test := range tests {
                t.Run("", func(t *testing.T) {

```

**Comment by gco** [comment]
PR pkg/xattr#62 was accepted and is fixed.

**Comment by gum3ng** [comment]
Thanks! I've rebased the code

**Comment by MichaelEischer** [comment]
@gum3ng Please update the xattr library to include the xattr fix: `go get github.com/pkg/xattr`

**Comment by gum3ng** [comment]
I've updated the xattr version. Please let me know if anymore changes are required.

**Comment by MichaelEischer** [comment]
@gco Can you test whether xattr support works  on Solaris when applying this PR?

**Comment by gco** [comment]
> @gco Can you test whether xattr support works on Solaris when applying this PR?

@MichaelEischer `go run build.go  --test --verbose` passes on Solaris 11.4.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks for changes. @gco thank you for testing!

**Pull request merged**
