### PR TITLE
Don't run TestMetadataChanged test on Windows

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Correct Windows build error https://ci.appveyor.com/project/fd0/restic
```
# github.com/restic/restic/internal/archiver [github.com/restic/restic/internal/archiver.test]
internal\archiver\archiver_test.go:2065:25: undefined: syscall.Stat_t
```

### CODE REVIEW

**Review by fd0 — APPROVED** [review]
LGTM, thanks for taking the time! It's a good workaround for now, later on we should figure out how to port this test to Windows. I got distracted and then forgot about this error, apparently AppVeyor did not run for the PR #2252 so I did not catch this early enough...

**Comment by gliptak** [comment]
@fd0 latest run still shows failures at https://ci.appveyor.com/project/fd0/restic/branch/master

```
--- FAIL: TestFileChanged (0.31s)
    --- FAIL: TestFileChanged/same-content-new-file (0.00s)
        archiver_test.go:645: unchanged file detected as changed
    --- FAIL: TestFileChanged/new-content-same-timestamp (0.06s)
        archiver_test.go:655: modified file detected as unchanged
--- FAIL: TestArchiverParent (0.06s)
    --- FAIL: TestArchiverParent/#00 (0.05s)
        testing.go:30: using low-security KDF parameters for test
        config.go:65: disabling check of the chunker polynomial
        archiver_test.go:1598: chdir to C:\Users\appveyor\AppData\Local\Temp\1\restic-test-763840237
        archiver_test.go:1606: first backup saved as b4985c9d
        archiver_test.go:1607: testfs: &{{{}} {0 0} map[targetfile:2102152]}
        archiver_test.go:1649: file targetfile: read 4204304 bytes, wanted 2102152 bytes
        panic.go:406: chdir back to C:\restic\internal\archiver
FAIL
```

**Comment by fd0** [comment]
I'll have a look.

**Comment by fd0** [comment]
Narf, this was much harder than I thought, but it's now finally corrected in #2266. I've verified the fix locally.

**Pull request merged**
