### PR TITLE
Refactor backup progress

### LINKED ISSUE #2738: restic backup --json --quiet is not quiet at all
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/arm

How did you run restic exactly?
-------------------------------
`restic backup --json --quiet`
called from a python3 script.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone/local

Expected behavior
-----------------
output only one line with `"message_type":"summary"`

Actual behavior
---------------
MANY lines with `"message_type":"status"`

According to `restic help` these should not be there:
```
-q, --quiet                     do not output comprehensive progress report
```

Steps to reproduce the behavior
-------------------------------

see above

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
probably add an `if` somewhere?

Did restic help you today?
------------------------------------------------------------
Every day!

### PR DESCRIPTION
**Pull request by amozoss**
What does this PR change? What problem does it solve?
-----------------------------------------------------
`ui/backup.go` and `ui/json/backup.go` are almost identical to one another (copy paste). 

This change refactors the shared logic into `progress.go`. 

`ui/backup.go` and `ui/json/backup.go` have already begun to diverge, for example
```
// for the last item "/", current is nil
if current != nil { 
   p.summary.ProcessedBytes += current.Size
}
```
`p.summary.ProcessedBytes += current.Size` was done outside of the lock in json/backup.go , but ui/backup.go had the above

This will continue to be a "hope we don't forget to update the other place" problem..

This change also allows the progress reporting/printing to be shared with restore status (forth coming after this is merged).

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
No it wasn't

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by greatroar** [comment]
I don't agree with omitting "archive" or "backup" from the names of the moved types, which are all specific to the backup command. The generic names ui.Counter and ui.Progress mentally conflict with ui/progress.Counter. If this must be moved out of cmd/restic, I suggest it be moved to a new package, maybe archiver/ui, ui/archiver or ui/backup.

**Comment by amozoss** [comment]
I'm not sure I follow what you're saying. I renamed the interface so that I could re-use the logic of the progress reporting with restores (I haven't submitted that change yet, it depends on this refactor).

**Review by MichaelEischer — COMMENTED** [review]
@amozoss
I've rebased the commit onto the current master. The main change during the rebase is that there's now a `SetDryRun()` method.

Besides that I've made a few other noteworthy changes:
- The JSON statistics part of the summary output is restored, which was lost during the refactoring.
- I've removed the unused `TotalErrors` field from the `Summary` struct.
- `backup --json | cat -` no longer printed status updates. I've fixed that regression. Now only `backup --json --quiet` disabled the status updates. The latter actually is a change compared to the current behavior where `backup --json --quiet` and `backup --json` behave similarly.

The `Counter` struct had also diverged between the text and JSON output.

Regarding the name of the `Counter` and the `Summary` struct I agree with greatroar that these are pretty generic and could be confusing. The cleanest way would probably to move everything, that is the backup.go files and progress.go, into a package `internal/ui/backup`. However, as you've mentioned that you want to reuse some part of the logic for `restore`, I'm wondering whether some other structure would be preferable.

**Comment by MichaelEischer** [comment]
I've added a changelog that his PR also fixes #2738.

@greatroar The backup ui code is for now consolidated in `ui/backup`.

**Review by MichaelEischer — APPROVED** [review]
LGTM.

**Pull request merged**
