### PR TITLE
prune/rebuild-index: Add warmup possibilities

### PR DESCRIPTION
**Pull request by aawsome**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Adds the possibility to access all packs which need a repack during `prune` and `rebuild.index`
This allows some cold storages to warm up these packs such that they are all accessable. This warm-up can also be done within a dry run such that the needed packs are available for the next `prune` run.
Also the `--json` option is now implemented for prune dry-run. This allows to build custom warm-up processes if the pure access to files doesn't do the warmup.

This can be easily extended to `restore`, see #2796.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

The idea comes from #2796.
For cold storage discussions see  also #2504

I didn't see a discussion about pruning cold storage, but this PR proved to be very useful for pruning my OVH Cloud Archive repositories.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by aawsome** [comment]
I rebased to master and added to `--warm-up` option to `rebuild-index`.

**Comment by rawtaz** [comment]
The more options there are, the more confusing it is for users. We want to keep the number of options as small as possible. Please try to not introduce new options unless really necessary. Is it really necessary in this case, and if so why can't it be the default behavior instead?

**Comment by aawsome** [comment]
> Is it really necessary in this case, and if so why can't it be the default behavior instead?

See #3202. This is only relevant if "data pack files" cannot be accessed immediately. If this is the case, we need to distinguish the "warm-up" run and the real run, where the needed files are accessible (which can be hours later that the warm-up run).

Of course, we could decide not to add the `--warm-up` option at all and instead only give a verbose JSON output for `--dry-run --json`. This would mean that we only support the workaround where the users create scripts to do the warmup themselves and the option for warmup would be effectively the `--dry-run` option.

**Comment by aawsome** [comment]
see also https://github.com/rustic-rs/rustic/pull/121

**Pull request closed without merging**
