### PR TITLE
compile on windows

### PR DESCRIPTION
**Pull request by thesyncim**
not really useful but i would like to help on supporting windows.
can you guide me?
will start with restic.Node

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for trying this. Please have a look at `isNewer()` and `fill_extra()` in `node_linux.go`, this needs to be implemented in order to fully support windows. Are you aware of any extra attributes files and directories have? I'm thinking about things like ACL, owner, group, etc.

**Comment by thesyncim** [comment]
thanks for the feedback 

node.ChangeTime and node.AccessTime 
```
stat, ok := fi.Sys().(*syscall.Win32FileAttributeData)
	if !ok {
		return
	}

node.ChangeTime = time.Unix(0, stat.LastWriteTime.Nanoseconds())
node.AccessTime = time.Unix(0, stat.LastAccessTime.Nanoseconds())
```

i´m not a windows expert but i think we can use GetSecurityInfo to get owner and group. 
https://msdn.microsoft.com/en-us/library/windows/desktop/aa446654(v=vs.85).aspx 

I´m a bit worried about you do we manage to copy open files maybe we can use VSS

**Comment by fd0** [comment]
VSS would be the right thing to do. I'm not a windows expert either, so someone has to find out how VSS works ;)

**Comment by thesyncim** [comment]
we can use vshadow.exe
`VShadow is a command-line tool that you can use to create and manage volume shadow copies.`
https://msdn.microsoft.com/en-us/library/windows/desktop/bb530725(v=vs.85).aspx





 but we need different binaries for different windows arch/versions 
also vshadow.exe needs administrative privileges 
binaries for major windows arch/versions (https://github.com/thesyncim/insync/tree/master/util/vshadow)

example:
vshadow.exe  -exec=(program to execute after snapshot created) -script=(File To save Snapshot information)  C:

Here is a example wrapper service for vss to choose right vshadow.exe based on windows arch/version
https://github.com/thesyncim/insync/blob/master/util/vss/vss.go (needs admin privileges)

and here is the example script to execute once snapshot is ready (https://github.com/thesyncim/insync/blob/master/util/copy/copy.go)

**Comment by thesyncim** [comment]
we may need some API changes so we can support windows.

node.fill_extra(string,os.FileInfo) must be node.fill_extra(string, *os.File) in order to get access to *os.File.Fd() (file Handle).

any thoughts on this?

**Comment by fd0** [comment]
Oh, why is that? This needs some more changes, as the file isn't opened yet at the time the node is created. Can't we just open it in `fill_extra()`?

btw: The latest commit is not properly formatted with `gofmt`, maybe you can install the pre-commit hook for git as suggested in the `README.md`.

**Comment by thesyncim** [comment]
sry about that will fix in the next commit

currently the file in open in archive.SaveFile (https://github.com/restic/restic/blob/1c0e76ccd6db5925e2a1c6db10abe6e3366842e2/archiver.go#L167) and closed only after the call to callNodeFromFileInfo.
we can close it before enter NodeFromFileInfo but we will have an extra syscall.

what do you suggest ?
thanks

**Comment by fd0** [comment]
That's the easy part. What about the call in `fileWorker()`? 
https://github.com/restic/restic/blob/1c0e76ccd6db5925e2a1c6db10abe6e3366842e2/archiver.go#L405

**Comment by fd0** [comment]
Maybe we should postpone windows support until afte the alpha release, so that the internal structures are more stable. What do you think?

**Comment by thesyncim** [comment]
ok sounds good to me

**Comment by thesyncim** [comment]
Meanwhile I will work on a go interface for vss snapshot

**Comment by fd0** [comment]
That's a great idea! Thanks for your support and braveness to attempt working on the windows support for restic! ;)

**Comment by fd0** [comment]
I'll close this PR for now.

**Pull request closed without merging**
