### PR TITLE
Use the platform-independent function for joining

### LINKED ISSUE #568: sftp backend fails in path, if used from Windows
## Output of `restic version`
current master

## Expected behavior
restic backup -r sftp://remote//path/to/go
(back up normally)

## Actual behavior
\path\to\go\data does not exist

The same command, if run from linux, works fine.

### PR DESCRIPTION
**Pull request by fd0**
Closes #568

### CODE REVIEW

**Comment by fd0** [comment]
@viric could you please have a look and test the code in this PR?

**Comment by fd0** [comment]
@viric ping?

**Comment by viric** [comment]
Works for me.

**Comment by fd0** [comment]
thanks!

**Pull request merged**
