### PR TITLE
archiver: only store deviceID for hardlinks

### LINKED ISSUE #3041: Restic 0.10.0 always reports all directories "changed", adds duplicate metadata, when run on ZFS snapshots
I run my backups from a ZFS snapshot in order to ensure the entire file-system is in a consistent state.  After I upgraded to restic 0.10.0 from the previous official release, the backup started adding a duplicate copy of all the directory meta-data while claiming that all the directories have been changed.  For example (pardon my bash):

    # restic version
    restic 0.10.0 compiled with go1.15.2 on freebsd/amd64
    
    # commands executed for bug (repeatedly on unchanging 
    # /usr/local/bin/restic backup -H $HOSTNAME --verbose=1 --cache-dir=$RESTIC_CACHE --exclude-file                 "${path}/${EXCLUDE_NAME}" "$path"
    scan finished in 2.928s: 1604 files, 341.787 GiB
    
    Files:           0 new,     0 changed,  1604 unmodified
    Dirs:            0 new,   231 changed,     0 unmodified
    Data Blobs:      0 new
    Tree Blobs:    219 new
    Added to the repo: 17.876 MiB

The result occurs repeatedly after re-running the backup on a new ZFS snapshot of an otherwise static file-system.  I expect it to work like the previous version in which directories were not seen to be "changed".

I tested this on the same file-system except without using a ZFS snapshot, and it does not report directories as "changed" or upload duplicate metadata.  Therefore, this problem seems to be particular to using ZFS snapshots.  My method for backing up from ZFS snapshots is as follows:

 * create ZFS snapshot of file-system labeled "restic"
 * run backup of "$basedir/.zfs/snapshot/restic", where the snapshot is mounted
 * destroy the ZFS snapshot labeled "restic"

I find it interesting that restic is uploading new/unique directory meta-data with every run, suggesting that something about the directory meta-data is actually changing between runs.  However, earlier versions of restic did not "see" these changes.  I'm at a loss as to what's causing this.

In terms of severity, this is merely a nuisance to me---about 30ish MiBs added to the repo each day.  However, I could see this being a bigger problem on systems with a lot more small files.  Is there any way I can find out what aspect of the directory is being identified as "changed" from the command-line?  Adding verbosity did not appear to do the trick.

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
he deviceID can change e.g. when backing up from a filesystem snapshot. However, it is only used for hardlink detection. Thus, it is not necessary to store it for non-hardlinks. This should handle most use cases without adding much complexity.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Solves part of #3041
Replaces #3599

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- ~~[ ] I have added documentation for relevant changes (in the manual).~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by greatroar** [comment]
This does make it impossible to determine where the mount points were from inspecting the snapshot...

**Comment by MichaelEischer** [comment]
> This does make it impossible to determine where the mount points were from inspecting the snapshot...

Is that information that useful? I figure that without knowing what filesystem was used where, that information is not particularly useful.

I did some tests to see where hardlinks are used, so far I've seen usages in `/usr/share/{terminfo,zoneinfo}`, in Docker/podman images, the steam runtime, flatpaks and a few random other usages. For me these amount to about 3% of all files, such that this PR is less effective than I'd hoped for.

**Comment by greatroar** [comment]
> Is that information that useful? I figure that without knowing what filesystem was used where, that information is not particularly useful.

No, probably not.

**Comment by JoeKun** [comment]
If I understand correctly, this small change could substantially improve the usability of `restic` for users who want to backup from a file-system snapshot, such as a ZFS snapshot.

This sounds like a very desirable improvement.

@MichaelEischer Could you please clarify what is missing before we could potentially see this change merged?

**Comment by MichaelEischer** [comment]
The problem with this change is that it will cause the next backup to create different tree blobs. This can double the size of the metadata stored for a backup.

My plan is to add support for large directories in restic 0.18 (see https://forum.restic.net/t/roadmap-for-restic-0-17-to-0-19/7197) which will also require changes to the tree format. That provides a good opportunity to also include this PR.

**Comment by MichaelEischer** [comment]
Slight change of plans. Now that we have feature flags, we can immediately merge this PR, but hide it behind a feature flag for now (`RESTIC_FEATURES=device-id-for-hardlinks`). The deviceID handling will either become the default in repository version 3 (restic 0.18) or be completely replaced. Either way, the feature flag will be removed some time afterwards.

**Review by MichaelEischer — COMMENTED** [review]
LGTM

**Comment by hettiger** [comment]
Thank you @MichaelEischer 

this also fixed backing up from APFS-snapshots for me.

**Comment by ilyagr** [comment]
I also just wanted to say thank you, this helped me a lot on my Mac. ❤️

**Pull request merged**
