### PR TITLE
Reveal archiver's concurrency options to backend command

### LINKED ISSUE #2204: rclone parallel uploads
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-37-g7b8d1dc0) compiled with go1.11.4 on linux/arm64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
uploading more files in parallel through rclone.

What are you trying to do?
--------------------------

restic uploads 4 files in parallel through rclone. Due to some weird limitations on the remote storage, they only allow 500kb speed or so per file uploaded, however, if we increase the number of parallels connections we can use more bandwidth and reduce backup time (tested and confirmed with rclone sync).

Example of current rclone uploads to Jotta Cloud (just as an example, it can be with oneDrive, hubic, opendrive, b2, etc...) command used:

`restic  backup /srv/dev-disk-by-label-DATAdroid  --exclude-file=/root/filter.restic -v -v  --repo rclone:oDroid-Jotta:/restic/dataDroid -o rclone.connections="10"   -o rclone.args="serve restic --stdio --rc --rc-addr localhost:5582 --rc-no-auth --config /root/.config/rclone/rclone.conf --log-file /mnt/cache/log/restic.jotta -v --transfers 10 --stats=20s"`

achieving the following output...

```
Transferred:        1.307G / 1.316 GBytes, 99%, 1.616 MBytes/s, ETA 5s
Errors:                 0
Checks:                 0 / 0, -
Transferred:          275 / 279, 99%
Elapsed time:    13m48.1s
Transferring:
 *     data/45/45a7f45c3de3…0be968fb3887a4f3316f:  7% /4.005M, 163.955k/s, 23s
 *     data/4a/4a9a4b16f1a9…668a9089f9602d2c731e: 27% /4.593M, 451.721k/s, 6s
 *     data/97/97965e0121dc…c76f0b070a9b9876f7d4: 97% /4.146M, 565.974k/s, 0s
 *     data/e4/e4562dd9205e…1dfd2c0b293fa66dfc4b: 54% /4.599M, 520.954k/s, 4s
```

how it should be...

as many files as the parameter rclone.connections (10 in this command), or a new parameter, is set up, so then we could be uploading 10 files (instead of our current 4, the default by rclone with no modifiers) reducing the time of the backups.

I have seen in the code (restic/internal/backend/rclone/config.go), we can configure the number of connections, however, that does not change the number of uploads through rclone.

`Connections uint option:"connections" help:"set a limit for the number of concurrent connections (default: 5)"`

and in 

```
func NewConfig() Config {
        return Config{
                Connections: 5,
        }
}
```
Nevertheless, I guess above configurations are more about the number of connections to rclone rather than the amount of files to be uploaded in parallel. am I right?

Did restic help you or made you happy in any way?
-------------------------------------------------
I am starting to use this great piece of software and I guess that can help me to keep my data safe, I would really like the idea of having a software fully customizable. Please, allow setting up a new parameter that will be the amount of parallels files to be uploaded. We can then extensively use more bandwidth uploading more files.

I have a lot of experience uploading backup to cloud storage providers, and is very annoying having enough bandwidth to upload 1Tb in less than 12hours and spend 3 days or more in doing so....
 
(1Tb of data to be uploaded to jotta through restic/rclone is taking 170hours).

Keep doing such a good stuff!!, you rock!

### PR DESCRIPTION
**Pull request by aspcartman**
This PR adds an ability to set the `archiver.Options` values in `backup` command. There are three options:

```go
// Options is used to configure the archiver.
type Options struct {
	// FileReadConcurrency sets how many files are read in concurrently. If
	// it's set to zero, at most two files are read in concurrently (which
	// turned out to be a good default for most situations).
	FileReadConcurrency uint

	// SaveBlobConcurrency sets how many blobs are hashed and saved
	// concurrently. If it's set to zero, the default is the number of CPUs
	// available in the system.
	SaveBlobConcurrency uint

	// SaveTreeConcurrency sets how many trees are marshalled and saved to the
	// repo concurrently.
	SaveTreeConcurrency uint
}
```

And there were no ability to alter them any how. They were always set to defaults. I added those three fields to the `backupOptions` struct. Now you can set them as `--file-read-concurrency=20`, `--save-blob-concurrency=20` and `--save-tree-concurrency=20` in `backup` command.

The purpose of those changes is to allow parallel uploads of more than 2 files when using rclone (#2204). Increasing the parallelism dramatically increases the speeds of the upload for unstable and rate limited connections and rclone backends that tend to hang.

For example YandexDisk backend hangs after the upload completes to calculate the hash sum of the file, and only then responds to the POST request. The larger the file - the longer it hangs. Uploading 5mb photos in 10 threads leads to 8 threads stuck on 100%, waiting for the response, and only 2 threads actually working most of the time.

Restic provides us with the `rclone.connections` option, yet increasing it doesn't change the fact that the archiver works with 2 file uploads at a time by default. 

The following command works ten times faster now:
```
restic -r rclone:yd:Restic -o rclone.connections=20 -o rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --transfers=20" backup --file-read-concurrency=20 --save-blob-concurrency=20 ~/Music
```

Closes #2204 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by MichaelEischer** [comment]
I think this PR solves the wrong problem in the wrong way: There's no point in manually setting SaveTreeConcurrency, once #2696 is fixed, it will be fixed at `GOMAXPROCS`. #2696 will also allow choosing the number of concurrent uploads independent of the file read and blob save concurrency. See #2750 for further discussions on that topic.

In addition restic should automatically adjust the number of uploads to the backend concurrency limit set via `-o rclone.connections=20`, there's no need to specify that manually.

**Comment by aspcartman** [comment]
@MichaelEischer I don't seem to understand your point : ) Mentioned #2696 is an issue, not a PR. I don't see any fixes anywhere.

My point is dramatically simple: 
FileReadConcurrency=2 - backup takes 1.5 hour. 
FileReadConcurrency=20 - 8 minutes. 
A user needs a command line option to change this value.

> restic should automatically adjust the number of uploads to the backend concurrency limit set via -o rclone.connections=20, there's no need to specify that manually.

I don't see such code in the repo, restic doesn't do that. And the number of concurrent connections != number of concurrent uploads.

**Comment by MichaelEischer** [comment]
@aspcartman I was mostly speaking how the backup should work and not how it does right now. We can't just add cli options which aren't useful for much longer than a few month (hopefully). There is no PR to fix #2696 right now; currently I'm busy with reviewing the prune optimizations.

I don't doubt that manually increasing the number of file reader and blob savers improves performance in your case, but that is merely a hack not a proper solution. `-o rclone.connections=20` should be the only option that has to be set, the rest should automatically do the right thing. Please take a look at #2750 for a discussion of some of the concurrency options and also at #322.

**Comment by MichaelEischer** [comment]
Closing as sort of duplicate of #2750.

**Pull request closed without merging**
