### PR TITLE
supports mount on windows

### PR DESCRIPTION
**Pull request by comicfans**
these patches support mount on windows through winfsp

#361 have some discuss on dokan , but I prefer [winfsp](http://www.secfs.net/winfsp/) instead, reasons:

* its official go bind [cgofuse](https://godoc.org/github.com/billziss-gh/cgofuse/fuse) have similar interface to bazil fuse,  and it also targets linux/osx,  makes port easily
* it's used by [rclone](https://rclone.org/commands/rclone_mount/) mount on windows
* winfsp's author takes [test](http://www.secfs.net/winfsp/develop/tests/) heavily
* winfsp suggests better [performance](http://www.secfs.net/winfsp/develop/perf-tests/) 
* in my test environment (with antivirus and data leak prevention software), dokan based encfs4win cause BSOD , but winfsp works without problem (with it's memfs example). and winfsp never crash during my restic development (even with my incorrect code)

this implementation is not a "native" port , it's an adapter layer which reuses current implementation .for that  I've moved minimal set codes to separate file in bazil fuse to make it built on windows.   it should not change behavior for other OS , and we can evaluate this on windows. 

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's an entry in the `CHANGELOG.md` file that describe the changes for our users
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for giving this a try. I must say I'm very skeptical, I had several bad experiences with cgo and (as already mentioned in https://github.com/restic/restic/issues/361#issuecomment-192171157 I'd like to keep restic Go-only.

**Comment by comicfans** [comment]
I haven't tried webdav mount on windows so I'm not sure it works as well as local filesystem (file number/size limit for example),  benifits of local filesystem is that it can be shared through samba with windows authorization (which is useful for us), I don't know if webdav can provide similar functional. and  what's the plan of #60 ? it have similar functional to webdav,  maybe we should consider most user scenario and decide which one to implement  ?

**Comment by fd0** [comment]
So, what do we do with this issue? Is there a way to realize fuse on Windows using Go-only code, without `cgo`?

Do you have some more background information for me on the limitations of the Windows webdav client? As far as I understood the issue you linked, it's only an issue on Windows 7? Since Windows 7 isn't supported any more since the beginning of January 2015, I don't think that's a huge issue. Which Windows version are you running?

**Comment by fd0** [comment]
Ah, the webdav limitations are not an issue, there's an webdav client implementation for winfsp that you could use (instead of the internal Windows webdav client): https://github.com/FrKaram/KS2.Drive

**Comment by rawtaz** [comment]
I realize it means third party software, but Cyberduck is a free and open source file transfer client with great support for many backens, including WebDAV: https://github.com/iterate-ch/cyberduck and https://cyberduck.io

They also have Mountain Duck which I am not sure if it's open source however. But my point is that there *is* third party software that will let the user use WebDAV if that is provided by restic.

**Comment by comicfans** [comment]
winfsp's cgofuse needs cgo to build , that means restic also needs cgo to build (on windows only). currently we're running windows 7 (even its not supported any more ).  I've found some webdav limitation but didn't confirm that by myself. [here](https://github.com/cryptomator/cryptomator/issues/357) and [here from microsoft, file cannot larger than 4GB](https://social.technet.microsoft.com/Forums/en-US/7cc8aaf5-3b68-47dc-8dc8-0f51d955f189/i-need-to-remove-the-filesizelimitsinbytes-registry-key?forum=w8itpronetworking).

and I agreed with @rawtaz 's point.  If third party software still needed to access restic, it didn't help too much for windows users. I think most linux/osx user will still prefer fuse instead of webdav .

**Comment by fd0** [comment]
> winfsp's cgofuse needs cgo to build , that means restic also needs cgo to build (on windows only)

Yeah, that's not an option. It'd mean reworking our build process completely, adding new dependencies (even a cross-compilation environment), that's not something we (as a spare-time Free Software project) can do.

To clarify this: I proposed adding a webdav server **in addition** to the fuse mount, so on non-Windows you have fuse+webdav, on Windows you only have webdav. Users can then either use the default Windows webdav client (for small files), or the Duck software thing @rawtaz mention, or the webdav client implementation based on winfsp. I think having users on Windows install an additional software package to use this is not an issue, it would be the same if we were to merge the winfsp-based fuse mount, since that requires having winfsp installed.

So, all an all, thank you very much for giving this a try, but I won't merge this PR. The way forward here in my opinion is to implement a webdav server which works on all platforms. Please let us know if you'd maybe like to try it. Thanks!

**Comment by comicfans** [comment]
That's OK, but I think a web interface is more useful than webdav, for example btsync/syncthing/transmission

**Comment by fd0** [comment]
@comicfans that's a somewhat related, but different issue.

**Comment by rawtaz** [comment]
I think @comicfans has a good point - instead of WebDAV, perhaps that coding time is better spend on a web server in restic. But then again, it will not yield the same features in terms of how you can interact with it, so on second thought I think neither of these two features are more important than the other one. Never mind :)

**Pull request closed without merging**
