### PR TITLE
Allow --files-from to take a dash (-) for stdin #769

### PR DESCRIPTION
**Pull request by barthr**
See code, added errors when both --stdin and --files from - are used together.

### CODE REVIEW

**Comment by barthr** [comment]
I'm not entirely sure what you mean. Could you elaborate more on that?

**Comment by barthr** [comment]
Do you mean for example that if you have the command:
```
$ find -name '*.go' | restic backup --files-from -
open -: no such file or directory
``` 
That the `-` automatically gets converted to os.Stdin?

**Comment by opennota** [comment]
I thought it would be something like this: https://github.com/restic/restic/pull/773/files

**Comment by barthr** [comment]
I interpreted it the wrong way, excuses. I will close my PR.

**Comment by fd0** [comment]
Thanks for trying :)

**Pull request closed without merging**
