### PR TITLE
Take last snapshot as parent by default and allow force re-reading

### PR DESCRIPTION
**Pull request by rakoo**
This solves #105

### CODE REVIEW

**Comment by fd0** [comment]
Hey, thanks for your contribution! This looks like a good start, here are my comments:
 * I think it would be good to change `--asnew` to `--force`, this makes it clearer
 * Why did you move the search for a parent snapshot after the scan phase? restic should abort as soon as possible without doing any work if there are wrong command line parameters.
 * At the moment the code only looks at cached snapshots, this should be changed to use the list of snapshots from the repository, the local cache should only be queried before reading the snapshot from the repo.
 * If `--force` is given, do not search for a snapshot, just create a new one

You can re-submit the commit after reworking it byy pushing it to your master branch with `git push -f`, it will appear here in this pull request and overwrite the old commit.

Thanks!

**Comment by rakoo** [comment]
Hey fd0,

I thought it would be best to get content from the cache after it was refreshed, since at that moment we have all the trees locally and we wouldn't have to fetch them from the repository a 2nd time (if I understand restic correctly), possibly on a remote location.

I thought the lookup for a parent also needed that, but it actually doesn't query the cache.

**Comment by fd0** [comment]
Another thought: The snapshots should also be checked whether the same directories/files have been specified as to be backed up. If I create backups of `~/foo` and `~/bar` separately, it should find the matching latest parent commit.

**Comment by rakoo** [comment]
I created a proper branch and re-submitted a PR in #121

**Pull request closed without merging**
