### PR TITLE
mount: support fuse-t on macOS

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
See https://github.com/restic/restic/issues/4048 for context.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
See https://github.com/restic/restic/issues/4048

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by MichaelEischer** [comment]
Compilation on FreeBSD is currently broken in the upstream library: https://github.com/anacrolix/fuse/pull/7

**Comment by akrabu** [comment]
When running the mount command, I get "List(key) failed: context canceled" first, then it loads the repository and behaves normally.  When I open the mount, at first it's swift and responsive - much moreso than usual.  Then as I browse a folder full of images using Finder, it will eventually freeze, "beachball", then I have to relaunch the Finder.

Finder will not relaunch until I SIGQUIT restic.  Here's the output:

```
./restic -vv mount ~/mnt/1
List(key) failed: context canceled
repository 24344e18 opened (version 2, compression level max)
[0:10] 100.00%  72 / 72 index files loaded
Now serving the repository at /Users/akrabu/mnt/1
Use another terminal or tool to browse the contents of this folder.
When finished, quit with Ctrl-c here or umount the mountpoint.
^\SIGQUIT: quit
PC=0x7ff80c33ff7c m=0 sigcode=0

goroutine 0 gp=0xadeb7a0 m=0 mp=0xadecbe0 [idle]:
syscall.syscall(0x95db7e9?, 0xc01529de0c?, 0xa47a2a0?, 0x0?)
	runtime/sys_darwin.go:23 +0x70 fp=0xc000e412f0 sp=0xc000e41260 pc=0x95cb5d0
syscall.read(0xafc11d8?, {0xc05573e000?, 0x95dad3d?, 0xc014594cc0?})
	syscall/zsyscall_darwin_amd64.go:1245 +0x45 fp=0xc000e41330 sp=0xc000e412f0 pc=0x95e3b45
syscall.Read(...)
	syscall/syscall_unix.go:181
github.com/anacrolix/fuse.readAll(0xa, {0xc05573e000, 0x4, 0x1001000})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:593 +0x7a fp=0xc000e41368 sp=0xc000e41330 pc=0x9bbe1da
github.com/anacrolix/fuse.(*Conn).ReadSingle(0xc000526a80, {0xc05573e000, 0x1001000, 0x1001000})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:608 +0x4c fp=0xc000e413a0 sp=0xc000e41368 pc=0x9bbe2ac
github.com/anacrolix/fuse.(*Conn).ReadRequest(0xc000526a80)
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:641 +0xe5 fp=0xc000e41e80 sp=0xc000e413a0 pc=0x9bbe4c5
github.com/anacrolix/fuse/fs.(*Server).Serve(0xc00020cd20, {0xa5b2a08, 0xc00053c240})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fs/serve.go:503 +0x3d5 fp=0xc000e41f60 sp=0xc000e41e80 pc=0x9bd1e75
github.com/anacrolix/fuse/fs.Serve(0xc000526a80, {0xa5b2a08, 0xc00053c240})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fs/serve.go:524 +0x135 fp=0xc000e41f90 sp=0xc000e41f60 pc=0x9bd22d5
main.runMount.func2()
	github.com/restic/restic/cmd/restic/cmd_mount.go:182 +0x65 fp=0xc000e41fe0 sp=0xc000e41f90 pc=0xa078fa5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000e41fe8 sp=0xc000e41fe0 pc=0x95cefa1
created by main.runMount in goroutine 1
	github.com/restic/restic/cmd/restic/cmd_mount.go:180 +0x7ad

goroutine 146 gp=0xc000105a40 m=0 mp=0xadecbe0 [syscall]:
syscall.syscall(0x95db7e9?, 0xc01529de0c?, 0xa47a2a0?, 0x0?)
	runtime/sys_darwin.go:23 +0x70 fp=0xc000e412f0 sp=0xc000e41260 pc=0x95cb5d0
syscall.read(0xafc11d8?, {0xc05573e000?, 0x95dad3d?, 0xc014594cc0?})
	syscall/zsyscall_darwin_amd64.go:1245 +0x45 fp=0xc000e41330 sp=0xc000e412f0 pc=0x95e3b45
syscall.Read(...)
	syscall/syscall_unix.go:181
github.com/anacrolix/fuse.readAll(0xa, {0xc05573e000, 0x4, 0x1001000})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:593 +0x7a fp=0xc000e41368 sp=0xc000e41330 pc=0x9bbe1da
github.com/anacrolix/fuse.(*Conn).ReadSingle(0xc000526a80, {0xc05573e000, 0x1001000, 0x1001000})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:608 +0x4c fp=0xc000e413a0 sp=0xc000e41368 pc=0x9bbe2ac
github.com/anacrolix/fuse.(*Conn).ReadRequest(0xc000526a80)
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fuse.go:641 +0xe5 fp=0xc000e41e80 sp=0xc000e413a0 pc=0x9bbe4c5
github.com/anacrolix/fuse/fs.(*Server).Serve(0xc00020cd20, {0xa5b2a08, 0xc00053c240})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fs/serve.go:503 +0x3d5 fp=0xc000e41f60 sp=0xc000e41e80 pc=0x9bd1e75
github.com/anacrolix/fuse/fs.Serve(0xc000526a80, {0xa5b2a08, 0xc00053c240})
	github.com/anacrolix/fuse@v0.3.1-0.20240526114152-8ed3dc023cd9/fs/serve.go:524 +0x135 fp=0xc000e41f90 sp=0xc000e41f60 pc=0x9bd22d5
main.runMount.func2()
	github.com/restic/restic/cmd/restic/cmd_mount.go:182 +0x65 fp=0xc000e41fe0 sp=0xc000e41f90 pc=0xa078fa5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000e41fe8 sp=0xc000e41fe0 pc=0x95cefa1
created by main.runMount in goroutine 1
	github.com/restic/restic/cmd/restic/cmd_mount.go:180 +0x7ad

goroutine 1 gp=0xc0000061c0 m=nil [select, 3 minutes]:
runtime.gopark(0xc000e47910?, 0x2?, 0x98?, 0x7d?, 0xc000e477c4?)
	runtime/proc.go:402 +0xce fp=0xc000e47530 sp=0xc000e47510 pc=0x959b88e
runtime.selectgo(0xc000e47910, 0xc000e477c0, 0xc000e47958?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc000e47650 sp=0xc000e47530 pc=0x95acb65
main.runMount({_, _}, {0x0, 0x0, 0x0, {{}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	github.com/restic/restic/cmd/restic/cmd_mount.go:185 +0x811 fp=0xc000e47990 sp=0xc000e47650 pc=0xa078c11
main.init.func33(0xadda7a0?, {0xc000522100?, 0x4?, 0xa09ba06?})
	github.com/restic/restic/cmd/restic/cmd_mount.go:71 +0xa7 fp=0xc000e47bb0 sp=0xc000e47990 pc=0xa057f27
github.com/spf13/cobra.(*Command).execute(0xadda7a0, {0xc0005220e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca fp=0xc000e47d38 sp=0xc000e47bb0 pc=0x98ff56a
github.com/spf13/cobra.(*Command).ExecuteC(0xaddaa80)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff fp=0xc000e47e10 sp=0xc000e47d38 pc=0x98ffe3f
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
main.main()
	github.com/restic/restic/cmd/restic/main.go:125 +0x245 fp=0xc000e47f50 sp=0xc000e47e10 pc=0xa092a65
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc000e47fe0 sp=0xc000e47f50 pc=0x959b45d
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000e47fe8 sp=0xc000e47fe0 pc=0x95cefa1

goroutine 2 gp=0xc000006700 m=nil [force gc (idle), 3 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000078fa8 sp=0xc000078f88 pc=0x959b88e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb3 fp=0xc000078fe0 sp=0xc000078fa8 pc=0x959b713
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x95cefa1
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000006c40 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000079780 sp=0xc000079760 pc=0x959b88e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc00007e000)
	runtime/mgcsweep.go:318 +0xdf fp=0xc0000797c8 sp=0xc000079780 pc=0x958777f
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc0000797e0 sp=0xc0000797c8 pc=0x957bfe5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000797e8 sp=0xc0000797e0 pc=0x95cefa1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000006e00 m=nil [GC scavenge wait]:
runtime.gopark(0xd43aa5?, 0x1264cd9?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000079f78 sp=0xc000079f58 pc=0x959b88e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.(*scavengerState).park(0xadea820)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc000079fa8 sp=0xc000079f78 pc=0x9585129
runtime.bgscavenge(0xc00007e000)
	runtime/mgcscavenge.go:658 +0x59 fp=0xc000079fc8 sp=0xc000079fa8 pc=0x95856d9
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x25 fp=0xc000079fe0 sp=0xc000079fc8 pc=0x957bf85
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x95cefa1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xa5

goroutine 17 gp=0xc0001a2000 m=nil [finalizer wait]:
runtime.gopark(0x0?, 0xc000e2a9c0?, 0x0?, 0xc0?, 0x1000000010?)
	runtime/proc.go:402 +0xce fp=0xc0000cfe20 sp=0xc0000cfe00 pc=0x959b88e
runtime.runfinq()
	runtime/mfinal.go:194 +0x107 fp=0xc0000cffe0 sp=0xc0000cfe20 pc=0x957b027
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000cffe8 sp=0xc0000cffe0 pc=0x95cefa1
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:164 +0x3d

goroutine 18 gp=0xc000281c00 m=nil [select]:
runtime.gopark(0xc000074778?, 0x3?, 0x8?, 0xf1?, 0xc000074772?)
	runtime/proc.go:402 +0xce fp=0xc000074618 sp=0xc0000745f8 pc=0x959b88e
runtime.selectgo(0xc000074778, 0xc00007476c, 0xc000203580?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc000074738 sp=0xc000074618 pc=0x95acb65
go.opencensus.io/stats/view.(*worker).start(0xc000203580)
	go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f fp=0xc0000747c8 sp=0xc000074738 pc=0x9f52ddf
go.opencensus.io/stats/view.init.0.gowrap1()
	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x25 fp=0xc0000747e0 sp=0xc0000747c8 pc=0x9f52145
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x95cefa1
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 19 gp=0xc000281dc0 m=nil [chan receive, 3 minutes]:
runtime.gopark(0x9624e85?, 0x1?, 0x1?, 0x20?, 0xc000074f60?)
	runtime/proc.go:402 +0xce fp=0xc000074ed0 sp=0xc000074eb0 pc=0x959b88e
runtime.chanrecv(0xc000096180, 0xc000074fa0, 0x1)
	runtime/chan.go:583 +0x3bf fp=0xc000074f48 sp=0xc000074ed0 pc=0x956825f
runtime.chanrecv2(0xc000096180?, 0xc000074fc0?)
	runtime/chan.go:447 +0x12 fp=0xc000074f70 sp=0xc000074f48 pc=0x9567e92
github.com/restic/restic/internal/restic.init.0.func1.1()
	github.com/restic/restic/internal/restic/lock.go:404 +0x99 fp=0xc000074fe0 sp=0xc000074f70 pc=0x9991e79
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x95cefa1
created by github.com/restic/restic/internal/restic.init.0.func1 in goroutine 1
	github.com/restic/restic/internal/restic/lock.go:401 +0x1a

goroutine 5 gp=0xc000007340 m=nil [select, 3 minutes, locked to thread]:
runtime.gopark(0xc00007a7a8?, 0x2?, 0x68?, 0xa6?, 0xc00007a798?)
	runtime/proc.go:402 +0xce fp=0xc00007a640 sp=0xc00007a620 pc=0x959b88e
runtime.selectgo(0xc00007a7a8, 0xc00007a794, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00007a760 sp=0xc00007a640 pc=0x95acb65
runtime.ensureSigM.func1()
	runtime/signal_unix.go:1034 +0x16f fp=0xc00007a7e0 sp=0xc00007a760 pc=0x95c5daf
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00007a7e8 sp=0xc00007a7e0 pc=0x95cefa1
created by runtime.ensureSigM in goroutine 19
	runtime/signal_unix.go:1017 +0xc8

goroutine 33 gp=0xc000104700 m=4 mp=0xc000081208 [syscall, 3 minutes]:
runtime.sigNoteSleep(0x0?)
	runtime/os_darwin.go:132 +0x18 fp=0xc00011a7a0 sp=0xc00011a768 pc=0x9596058
os/signal.signal_recv()
	runtime/sigqueue.go:149 +0x25 fp=0xc00011a7c0 sp=0xc00011a7a0 pc=0x95cb025
os/signal.loop()
	os/signal/signal_unix.go:23 +0x13 fp=0xc00011a7e0 sp=0xc00011a7c0 pc=0x9625253
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00011a7e8 sp=0xc00011a7e0 pc=0x95cefa1
created by os/signal.Notify.func1.1 in goroutine 19
	os/signal/signal.go:151 +0x1f

goroutine 20 gp=0xc0004b76c0 m=nil [chan receive, 3 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000075698 sp=0xc000075678 pc=0x959b88e
runtime.chanrecv(0xc000492fc0, 0xc0000757a0, 0x1)
	runtime/chan.go:583 +0x3bf fp=0xc000075710 sp=0xc000075698 pc=0x956825f
runtime.chanrecv1(0x0?, 0x0?)
	runtime/chan.go:442 +0x12 fp=0xc000075738 sp=0xc000075710 pc=0x9567e72
main.cleanupHandler(0x0?, 0xc0004de750)
	github.com/restic/restic/cmd/restic/cleanup.go:24 +0x2a fp=0xc0000757c0 sp=0xc000075738 pc=0xa05850a
main.createGlobalContext.gowrap1()
	github.com/restic/restic/cmd/restic/cleanup.go:16 +0x25 fp=0xc0000757e0 sp=0xc0000757c0 pc=0xa0584a5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x95cefa1
created by main.createGlobalContext in goroutine 1
	github.com/restic/restic/cmd/restic/cleanup.go:16 +0x98

goroutine 49 gp=0xc000504380 m=nil [GC worker (idle), 3 minutes]:
runtime.gopark(0x6dc6ff6ea594?, 0x3?, 0x1a?, 0xa7?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000116750 sp=0xc000116730 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0001167e0 sp=0xc000116750 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0001167e8 sp=0xc0001167e0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 50 gp=0xc000504540 m=nil [GC worker (idle)]:
runtime.gopark(0x6dd7faac0d78?, 0x1?, 0x95?, 0x54?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000116f50 sp=0xc000116f30 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000116fe0 sp=0xc000116f50 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000116fe8 sp=0xc000116fe0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 21 gp=0xc0004b7880 m=nil [GC worker (idle)]:
runtime.gopark(0x6dd7faaa5360?, 0x3?, 0xb3?, 0x83?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000075f50 sp=0xc000075f30 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000075fe0 sp=0xc000075f50 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 65 gp=0xc000602000 m=nil [GC worker (idle), 3 minutes]:
runtime.gopark(0x6dc6ff6e9ce9?, 0x3?, 0xc4?, 0x11?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000608750 sp=0xc000608730 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0006087e0 sp=0xc000608750 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0006087e8 sp=0xc0006087e0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 51 gp=0xc000504700 m=nil [GC worker (idle)]:
runtime.gopark(0x6dd7faab6fe0?, 0x1?, 0x1d?, 0x86?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000117750 sp=0xc000117730 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0001177e0 sp=0xc000117750 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0001177e8 sp=0xc0001177e0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 22 gp=0xc0004b7a40 m=nil [GC worker (idle)]:
runtime.gopark(0xae4f8a0?, 0x1?, 0x30?, 0x71?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000076750 sp=0xc000076730 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0000767e0 sp=0xc000076750 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 23 gp=0xc0004b7c00 m=nil [GC worker (idle)]:
runtime.gopark(0x6dd7faaa550f?, 0x3?, 0xae?, 0x1e?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000076f50 sp=0xc000076f30 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000076fe0 sp=0xc000076f50 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 24 gp=0xc0004b7dc0 m=nil [GC worker (idle), 3 minutes]:
runtime.gopark(0x6dd7faa833dd?, 0x3?, 0xfc?, 0xce?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000077750 sp=0xc000077730 pc=0x959b88e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0000777e0 sp=0xc000077750 pc=0x957e0c5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x95cefa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 29 gp=0xc000603880 m=nil [select]:
runtime.gopark(0xc00060bf20?, 0x4?, 0x51?, 0xc6?, 0xc00060bed0?)
	runtime/proc.go:402 +0xce fp=0xc00060bd68 sp=0xc00060bd48 pc=0x959b88e
runtime.selectgo(0xc00060bf20, 0xc00060bec8, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00060be88 sp=0xc00060bd68 pc=0x95acb65
github.com/restic/restic/internal/repository.(*locker).monitorLockRefresh(0xad55de0, {0xa5c1010, 0xc000014050}, 0xc0001b80c0, 0xc000292000, 0xc000292060, 0xa5abeb0)
	github.com/restic/restic/internal/repository/lock.go:208 +0x20a fp=0xc00060bf98 sp=0xc00060be88 pc=0x9b3856a
github.com/restic/restic/internal/repository.(*locker).Lock.gowrap2()
	github.com/restic/restic/internal/repository/lock.go:106 +0x38 fp=0xc00060bfe0 sp=0xc00060bf98 pc=0x9b37b38
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00060bfe8 sp=0xc00060bfe0 pc=0x95cefa1
created by github.com/restic/restic/internal/repository.(*locker).Lock in goroutine 1
	github.com/restic/restic/internal/repository/lock.go:106 +0x757

goroutine 28 gp=0xc000603a40 m=nil [select, 3 minutes]:
runtime.gopark(0xc0000d4f00?, 0x3?, 0x60?, 0x0?, 0xc0000d4e62?)
	runtime/proc.go:402 +0xce fp=0xc0000d4cf0 sp=0xc0000d4cd0 pc=0x959b88e
runtime.selectgo(0xc0000d4f00, 0xc0000d4e5c, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc0000d4e10 sp=0xc0000d4cf0 pc=0x95acb65
github.com/restic/restic/internal/repository.(*locker).refreshLocks(0xad55de0, {0xa5c1010, 0xc000014050}, {0xa5c98c8, 0xc0000a2c90}, 0xc0001b80c0, 0xc000292000, 0xc000292060, 0xa5abeb0)
	github.com/restic/restic/internal/repository/lock.go:144 +0x215 fp=0xc0000d4f88 sp=0xc0000d4e10 pc=0x9b37df5
github.com/restic/restic/internal/repository.(*locker).Lock.gowrap1()
	github.com/restic/restic/internal/repository/lock.go:105 +0x45 fp=0xc0000d4fe0 sp=0xc0000d4f88 pc=0x9b37ba5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000d4fe8 sp=0xc0000d4fe0 pc=0x95cefa1
created by github.com/restic/restic/internal/repository.(*locker).Lock in goroutine 1
	github.com/restic/restic/internal/repository/lock.go:105 +0x69a

rax    0x2000003
rbx    0xc000e41270
rcx    0x7ff7b79a1738
rdx    0x4
rdi    0xa
rsi    0xc05573e000
rbp    0x7ff7b79a1750
rsp    0x7ff7b79a1738
r8     0xadecbe0
r9     0x0
r10    0x95e5b00
r11    0x246
r12    0xc000e41420
r13    0x0
r14    0xc000105a40
r15    0xffffffff
rip    0x7ff80c33ff7c
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
```

**Comment by MichaelEischer** [comment]
Thanks a lot for testing! The `List(key) failed: context canceled` is just a cosmetic bug caused by https://github.com/restic/restic/pull/4784 . I'll fix that, but it's unrelated to the problem here.

Did you try to stop restic using Ctrl-C? Judging from the stacktrace the answer is no. 

What is very, very weird is that the stacktrace of goroutine 0 and 146 appear to be identical, yet one is idle and the other one waits for the syscall. Other than that, the stacktrace shows nothing particularly suspicious, only that restic tries to read data from the fuse socket.

To debug that further, I'd need a `DEBUG_LOG` from restic. I'm only interested in the lines containing `fuse: `. That will however contain quite a bit of information on the data stored in the repository (primarily filenames not content). (You can also send me an email with the log excerpt).

**Comment by akrabu** [comment]
@MichaelEischer At first I was having trouble reproducing it in debug mode, but of course in the recording I made to show you how I couldn't reproduce it in debug mode... I reproduced it haha.  It happens way faster with debug mode off, for some reason - generally within viewing 2-3 images, it'll disconnect the share.  No idea why it takes longer with debug mode on, but apparently it operates on "a watched pot never boils" physics 😂

Screen recording:
https://dropover.cloud/d70d91

The preview window was covering it, but this is what popped up underneath:

Screenshot 2024-05-26 at 12 27 57 PM

Debug log via `cat restic.log | rg -i "fuse:" > restic-filtered.log` (expires in 24 hours):
https://dropover.cloud/d70d91

**Comment by MichaelEischer** [comment]
Thanks for the log! I think I've found the problem: `short kernel write: written=8192/32784 error="" stack=`. I'll see what I can do about that.

**Comment by MichaelEischer** [comment]
I've added a small patch to the FUSE library (see https://github.com/MichaelEischer/fuse/commits/workaround-short-writes/ . All commits except the top one are from https://github.com/anacrolix/fuse) that should handle the short write error. Can you give it another try?

**Comment by akrabu** [comment]
Okay, I have to admit, I think I'm stuck.  This is just a wee bit more advanced than I know what to do with.  I cloned your repository, but I'm not quite sure how to build it.  I know how to build things like Restic that just output a tool, but I have no idea how to build something like this - it's sort of a library, right?  I don't see a makefile or anything, so I tried just "go build" but that didn't quite seem to do anything.  I'm going to need a little more guidance, I'm afraid.  Thanks!

**Comment by MichaelEischer** [comment]
Sorry for the confusion, it's actually sufficient to just compile restic using the latest code from this PR (make sure that your local checkout includes the changes from https://github.com/restic/restic/pull/4825/commits/cf9188bc2a1255cc1f9271609a444e2b1a582e5e ). The patched FUSE library is referenced by the just mentioned commit and will automatically be downloaded by go during compilation of restic.

In short: just check out the current state of this PR and build it using `go build ./cmd/restic`.

> Okay after some back and forth with ChatGPT (lol... this should be interesting) I did `go build -o libfuse-t.dylib` and `go build -o libfuse-t.a`, backed up my existing copies and replaced them in /usr/local/lib.

Oh dear, that is absolutely, 1000% completely wrong :joy: (sorry) . Neither of my code changes modified libfuse-t itself, so there's no point at all messing around with that (restic would also never use the libraries). So please move the backed up files back in place...

**Comment by akrabu** [comment]
> In short: just check out the current state of this PR and build it using `go build ./cmd/restic`.

Hahaha I should have known I was overcomplicating things...

> Oh dear, that is absolutely, 1000% completely wrong 😂 (sorry) . Neither of my code changes modified libfuse-t itself, so there's no point at all messing around with that (restic would also never use the libraries). So please move the backed up files back in place...

I was fairly certain it was going to have me do something dumb - but one time it really did help me compile this obscure compression algorithm (libbsc) when I couldn't get it to work on my Mac.  I was wondering if I'd stump it this time lol

But hey, so far...  no more freezes!  I think this patch might have done it!  🥳

**Comment by MichaelEischer** [comment]
> But hey, after doing it the right way... no more freezes so far! I think this patch might have done it! 🥳

Nice, thanks a lot for testing! Can you report back in a few days whether the freezes are definitely gone?

**Comment by MichaelEischer** [comment]
@akrabu Did you notice any new problems so far?

**Comment by akrabu** [comment]
So far so good!  Tested on my Intel home Mac and M1 work Mac.  Should probably try to restore a large folder at work and see how it does.  I’ll make a note to do that tomorrow 👍

**Review by MichaelEischer — COMMENTED** [review]
LGTM.

**Comment by akrabu** [comment]
@MichaelEischer Not sure if this is where I should post it or not, but now I'm getting this:

```
tree -d -P "*Illumina105*" -P "Illumina112" --ignore-case -o ~/Downloads/tree.txt --matchdirs --prune
nfs server fuse-t:/restic: not responding
nfs server fuse-t:/restic: is alive again
nfs server fuse-t:/restic: not responding
nfs server fuse-t:/restic: is alive again
nfs server fuse-t:/restic: not responding
nfs server fuse-t:/restic: is alive again
nfs server fuse-t:/restic: not responding
nfs server fuse-t:/restic: is alive again
nfs server fuse-t:/restic: not responding
nfs server fuse-t:/restic: is alive again
```

I also get the graphical disconnected message periodically via MacOS.  Not certain if it will continue and properly output things, or if I'm going to have missing data from the tree.

**Comment by MichaelEischer** [comment]
@akrabu Can you open an issue for that? Juding from the behavior, it feels like this could be some performance problem in either restic or fuse-t. Does restic consume lots of CPU or downloads a lot of data during those freezes?

**Pull request merged**
